// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
// source: protobuf/rfc6350/vcard/v1/contact.proto, protobuf/rfc6350/vcard/v1/contact_address.proto, protobuf/rfc6350/vcard/v1/contact_location.proto, protobuf/rfc6350/vcard/v1/contact_method.proto, protobuf/rfc6350/vcard/v1/contact_name.proto, protobuf/rfc6350/vcard/v1/contact_property.proto, protobuf/rfc6350/vcard/v1/contact_relation.proto, protobuf/rfc6350/vcard/v1/contact_speech.proto, protobuf/rfc6350/vcard/v1/date_or_text.proto, protobuf/rfc6350/vcard/v1/types.proto, protobuf/rfc6350/vcard/v1/vcard.proto
//
// database: rfc
// schema:   vcard
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package vcard

import (
	"context"

	"github.com/oh-tarnished/freebusy/internal/database/rfcgorm/gormx"
	"gorm.io/gorm"
)

// OrganizationStoreIface is the full data-access surface of Organization: everything
// OrganizationStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedOrganizationStore struct {
//		OrganizationStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewOrganizationStore returns the concrete
// *OrganizationStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type OrganizationStoreIface interface {
	Create(ctx context.Context, m *Organization) error
	List(ctx context.Context, opts gormx.ListOptions) ([]Organization, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *Organization) error
	GetByID(ctx context.Context, id string) (*Organization, error)
	DeleteByID(ctx context.Context, id string) error
	ListByContactID(ctx context.Context, id string, opts gormx.ListOptions) ([]Organization, error)
}

// OrganizationStore provides typed CRUD access to Organization records.
// Organization is the ORG property, RFC 6350 section 6.6.4 <https://www.rfc-editor.org/rfc/rfc6350.html#section-6.6.4>. Semicolon-separated on the wire: the first component is the organization, the rest are progressively narrower units. Reference: RFC 6350 "vCard Format Specification", section 6.6.4. https://www.rfc-editor.org/rfc/rfc6350.html#section-6.6.4
type OrganizationStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewOrganizationStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that OrganizationStore implements its own interface. Without it a
// signature could drift from OrganizationStoreIface and only break in whichever downstream
// package decorates it.
var _ OrganizationStoreIface = (*OrganizationStore)(nil)

// Compile-time proof that OrganizationStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Organization] = (*OrganizationStore)(nil)

// NewOrganizationStore returns a OrganizationStore backed by db.
func NewOrganizationStore(db *gorm.DB) *OrganizationStore { return &OrganizationStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *OrganizationStore) WithTelemetry(t gormx.Telemetry) *OrganizationStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *OrganizationStore) Create(ctx context.Context, m *Organization) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the Organization records matching opts.
func (s *OrganizationStore) List(ctx context.Context, opts gormx.ListOptions) ([]Organization, error) {
	var out []Organization
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Organization records matching opts.Where
// (pagination and ordering are ignored).
func (s *OrganizationStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	db := s.DB.WithContext(ctx).Model(&Organization{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *OrganizationStore) Update(ctx context.Context, m *Organization) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the Organization with the given primary key.
func (s *OrganizationStore) GetByID(ctx context.Context, id string) (*Organization, error) {
	var m Organization
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Organization with the given primary key.
func (s *OrganizationStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&Organization{}, "id = ?", id).Error
}

// ListByContactID returns the Organization records whose contact_id matches id, with opts applied.
func (s *OrganizationStore) ListByContactID(ctx context.Context, id string, opts gormx.ListOptions) ([]Organization, error) {
	var out []Organization
	q := opts.Apply(s.DB.WithContext(ctx).Where("contact_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
