// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  unitslinkql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package unitslinkql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for PropertyUnitsLink. Build predicates like Id.Eq(v) and combine
// them with And/Or/Not.
var (
	Id         = graphql.StringField{Col: "id"}
	PropertyId = graphql.StringField{Col: "propertyId"}
	UnitId     = graphql.StringField{Col: "unitId"}
	UnitName   = graphql.StringField{Col: "unitName"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
