// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: protobuf/rfc9073/resource/v1/resource.proto, protobuf/rfc9073/resource/v1/types.proto
//
// database: rfc
// schema:   resource
//
// Proto-facing repository interfaces; adapters compose the generated gorm and GraphQL outputs.
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package resource

import (
	"context"
	"github.com/oh-tarnished/freebusy/internal/database/rfcgorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/rfcrepo/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc9073/resource/v1/resourcepbv1"
	"gorm.io/gorm"
)

// ResourceRepository is the provider-agnostic persistence surface for
// Resource (resources/{resource}): full-message writes, AIP-160/AIP-132 lists with
// opaque page tokens, field-mask updates, and etag optimistic concurrency.
type ResourceRepository interface {
	// Create persists m and returns the stored record.
	Create(ctx context.Context, m *resourcepbv1.Resource) (*resourcepbv1.Resource, error)
	// Get returns the record addressed by its resource name, or
	// repox.ErrNotFound.
	Get(ctx context.Context, name string) (*resourcepbv1.Resource, error)
	// List returns one page of records.
	List(ctx context.Context, in repox.ListInput) ([]*resourcepbv1.Resource, string, error)
	// Update persists the masked fields of m; an empty mask replaces every
	// mutable field. m.Etag, when set, guards against concurrent writes
	// (repox.ErrConflict).
	Update(ctx context.Context, m *resourcepbv1.Resource, paths []string) (*resourcepbv1.Resource, error)
	// Delete removes the record addressed by its resource name.
	Delete(ctx context.Context, name string) error
}

// ResourceHooks lets custom logic run inside the generated Resource
// adapters without editing them: normalization/derivation before writes,
// derived fields after reads, and guards before deletes. Nil funcs are skipped.
type ResourceHooks struct {
	// BeforeCreate runs after name/id resolution, before the row is written.
	BeforeCreate func(ctx context.Context, m *resourcepbv1.Resource) error
	// AfterRead runs on every record a read returns (Get, List, and the
	// re-reads writes return).
	AfterRead func(ctx context.Context, m *resourcepbv1.Resource) error
	// BeforeUpdate runs after the mask is applied to the merged record,
	// before it is written.
	BeforeUpdate func(ctx context.Context, existing, merged *resourcepbv1.Resource, paths []string) error
	// BeforeDelete runs before the row is removed; returning an error vetoes.
	BeforeDelete func(ctx context.Context, name string) error
}

// Repositories bundles this schema's repository surfaces behind one factory.
type Repositories struct {
	Resources ResourceRepository
}

// options collects the per-resource customizations the factories thread into
// the adapters they build.
type options struct {
	resourceHooks     ResourceHooks
	resourceOverrides map[string]filterx.SQLHandler
}

// Option customizes the adapters a factory builds.
type Option func(*options)

// WithResourceHooks installs h on the Resource adapters.
func WithResourceHooks(h ResourceHooks) Option {
	return func(o *options) { o.resourceHooks = h }
}

// WithResourceListOverride substitutes the generated filter dispatch for one
// Resource filter field (e.g. a derived state computed via subqueries).
func WithResourceListOverride(field string, h filterx.SQLHandler) Option {
	return func(o *options) {
		if o.resourceOverrides == nil {
			o.resourceOverrides = map[string]filterx.SQLHandler{}
		}
		o.resourceOverrides[field] = h
	}
}

// New picks the adapter set for the live handle in conn.
func New(conn repox.Conn, opts ...Option) Repositories {
	return NewGorm(conn.Gorm, opts...)
}

// NewGorm builds the GORM adapter set over db.
func NewGorm(db *gorm.DB, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Resources: &GormResourceRepository{DB: db, Hooks: o.resourceHooks, ListOverrides: o.resourceOverrides},
	}
}
