// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
// source: protobuf/rfc7953/availability/v1/availability.proto, protobuf/rfc7953/availability/v1/available.proto, protobuf/rfc7953/availability/v1/types.proto
//
// database: rfc
// schema:   availability
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package availability

import (
	"time"

	"github.com/lib/pq"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc7953/availability/v1/rfcavailabilitypbv1"
	"google.golang.org/genproto/googleapis/type/date"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// BusyTypeFromProto maps the proto enum onto its stored form ("" for
// unspecified or unknown values, so the column is omitted / left to default).
func BusyTypeFromProto(v rfcavailabilitypbv1.BusyType) BusyType {
	switch v {
	case rfcavailabilitypbv1.BusyType_BUSY_TYPE_BUSY:
		return BusyTypeBusy
	case rfcavailabilitypbv1.BusyType_BUSY_TYPE_BUSY_UNAVAILABLE:
		return BusyTypeBusyUnavailable
	case rfcavailabilitypbv1.BusyType_BUSY_TYPE_BUSY_TENTATIVE:
		return BusyTypeBusyTentative
	}
	return ""
}

// BusyTypeToProto maps the stored form back onto the proto enum
// (unspecified for empty or unknown values).
func BusyTypeToProto(v BusyType) rfcavailabilitypbv1.BusyType {
	switch v {
	case BusyTypeBusy:
		return rfcavailabilitypbv1.BusyType_BUSY_TYPE_BUSY
	case BusyTypeBusyUnavailable:
		return rfcavailabilitypbv1.BusyType_BUSY_TYPE_BUSY_UNAVAILABLE
	case BusyTypeBusyTentative:
		return rfcavailabilitypbv1.BusyType_BUSY_TYPE_BUSY_TENTATIVE
	}
	return 0
}

// BusyTypePtrFromProto is BusyTypeFromProto for nullable columns:
// unspecified maps to nil.
func BusyTypePtrFromProto(v rfcavailabilitypbv1.BusyType) *BusyType {
	if s := BusyTypeFromProto(v); s != "" {
		return &s
	}
	return nil
}

// BusyTypePtrToProto is BusyTypeToProto for nullable columns.
func BusyTypePtrToProto(v *BusyType) rfcavailabilitypbv1.BusyType {
	if v == nil {
		return 0
	}
	return BusyTypeToProto(*v)
}

// AvailabilityToProto converts the stored row (with its belongs-to associations,
// when preloaded) to its proto message. Nil in, nil out.
func AvailabilityToProto(m *Availability) *rfcavailabilitypbv1.Availability {
	if m == nil {
		return nil
	}
	out := &rfcavailabilitypbv1.Availability{}
	out.Name = m.Name
	out.Uid = fromPtr(m.UID)
	out.IcalUid = fromPtr(m.IcalUID)
	out.BusyType = BusyTypePtrToProto(m.BusyType)
	if v := goToDur(m.Duration); v != nil {
		out.EndForm = &rfcavailabilitypbv1.Availability_Duration{Duration: v}
	}
	out.Summary = fromPtr(m.Summary)
	out.Description = fromPtr(m.Description)
	out.Organizer = fromPtr(m.Organizer)
	out.Priority = fromPtr(m.Priority)
	out.Categories = []string(m.Categories)
	out.Etag = fromPtr(m.Etag)
	out.DeleteTime = goToTs(m.DeleteTime)
	out.ExpireTime = goToTs(m.ExpireTime)
	out.CreateTime = goValToTs(m.CreateTime)
	out.UpdateTime = goValToTs(m.UpdateTime)
	out.Start = CalendarTimeToProto(m.Start)
	if v := CalendarTimeToProto(m.End); v != nil {
		out.EndForm = &rfcavailabilitypbv1.Availability_End{End: v}
	}
	return out
}

// AvailabilityFromProto maps the proto message's data fields onto a fresh row.
// It never invents keys or relations: primary keys, resource references, and
// sub-row graph wiring stay with the caller. Nil in, nil out.
func AvailabilityFromProto(pb *rfcavailabilitypbv1.Availability) *Availability {
	if pb == nil {
		return nil
	}
	m := &Availability{}
	// not mapped here: start (sub-row graph), end (sub-row graph)
	m.Name = pb.GetName()
	m.UID = toPtr(pb.GetUid())
	m.IcalUID = toPtr(pb.GetIcalUid())
	m.BusyType = BusyTypePtrFromProto(pb.GetBusyType())
	m.Duration = durToGo(pb.GetDuration())
	m.Summary = toPtr(pb.GetSummary())
	m.Description = toPtr(pb.GetDescription())
	m.Organizer = toPtr(pb.GetOrganizer())
	m.Priority = toPtr(pb.GetPriority())
	m.Categories = pq.StringArray(pb.GetCategories())
	m.Etag = toPtr(pb.GetEtag())
	m.DeleteTime = tsToGo(pb.GetDeleteTime())
	m.ExpireTime = tsToGo(pb.GetExpireTime())
	return m
}

// CalendarTimeToProto converts the stored row (with its belongs-to associations,
// when preloaded) to its proto message. Nil in, nil out.
func CalendarTimeToProto(m *CalendarTime) *rfcavailabilitypbv1.CalendarTime {
	if m == nil {
		return nil
	}
	out := &rfcavailabilitypbv1.CalendarTime{}
	// not mapped here: date_time
	if v := goToDate(m.Date); v != nil {
		out.Value = &rfcavailabilitypbv1.CalendarTime_Date{Date: v}
	}
	return out
}

// CalendarTimeFromProto maps the proto message's data fields onto a fresh row.
// It never invents keys or relations: primary keys, resource references, and
// sub-row graph wiring stay with the caller. Nil in, nil out.
func CalendarTimeFromProto(pb *rfcavailabilitypbv1.CalendarTime) *CalendarTime {
	if pb == nil {
		return nil
	}
	m := &CalendarTime{}
	// not mapped here: date_time
	m.Date = dateToGo(pb.GetDate())
	return m
}

// AvailablePeriodToProto converts the stored row (with its belongs-to associations,
// when preloaded) to its proto message. Nil in, nil out.
func AvailablePeriodToProto(m *AvailablePeriod) *rfcavailabilitypbv1.AvailablePeriod {
	if m == nil {
		return nil
	}
	out := &rfcavailabilitypbv1.AvailablePeriod{}
	out.IcalUid = fromPtr(m.IcalUID)
	if v := goToDur(m.Duration); v != nil {
		out.EndForm = &rfcavailabilitypbv1.AvailablePeriod_Duration{Duration: v}
	}
	out.Summary = fromPtr(m.Summary)
	out.Description = fromPtr(m.Description)
	out.Location = fromPtr(m.Location)
	out.RecurrenceRule = fromPtr(m.RecurrenceRule)
	out.Categories = []string(m.Categories)
	out.Comments = []string(m.Comments)
	out.Start = CalendarTimeToProto(m.Start)
	if v := CalendarTimeToProto(m.End); v != nil {
		out.EndForm = &rfcavailabilitypbv1.AvailablePeriod_End{End: v}
	}
	return out
}

// AvailablePeriodFromProto maps the proto message's data fields onto a fresh row.
// It never invents keys or relations: primary keys, resource references, and
// sub-row graph wiring stay with the caller. Nil in, nil out.
func AvailablePeriodFromProto(pb *rfcavailabilitypbv1.AvailablePeriod) *AvailablePeriod {
	if pb == nil {
		return nil
	}
	m := &AvailablePeriod{}
	// not mapped here: start (sub-row graph), end (sub-row graph)
	m.IcalUID = toPtr(pb.GetIcalUid())
	m.Duration = durToGo(pb.GetDuration())
	m.Summary = toPtr(pb.GetSummary())
	m.Description = toPtr(pb.GetDescription())
	m.Location = toPtr(pb.GetLocation())
	m.RecurrenceRule = toPtr(pb.GetRecurrenceRule())
	m.Categories = pq.StringArray(pb.GetCategories())
	m.Comments = pq.StringArray(pb.GetComments())
	return m
}

// ExtensionPropertyToProto converts the stored row (with its belongs-to associations,
// when preloaded) to its proto message. Nil in, nil out.
func ExtensionPropertyToProto(m *ExtensionProperty) *rfcavailabilitypbv1.ExtensionProperty {
	if m == nil {
		return nil
	}
	out := &rfcavailabilitypbv1.ExtensionProperty{}
	// not mapped here: parameters
	out.Key = m.Key
	out.Values = []string(m.Values)
	return out
}

// ExtensionPropertyFromProto maps the proto message's data fields onto a fresh row.
// It never invents keys or relations: primary keys, resource references, and
// sub-row graph wiring stay with the caller. Nil in, nil out.
func ExtensionPropertyFromProto(pb *rfcavailabilitypbv1.ExtensionProperty) *ExtensionProperty {
	if pb == nil {
		return nil
	}
	m := &ExtensionProperty{}
	// not mapped here: parameters
	m.Key = pb.GetKey()
	m.Values = pq.StringArray(pb.GetValues())
	return m
}

// toPtr returns a pointer to v, or nil for the zero value — a nullable column
// stores absence, not the proto zero.
func toPtr[T comparable](v T) *T {
	var zero T
	if v == zero {
		return nil
	}
	return &v
}

// fromPtr dereferences p, returning the zero value for nil.
func fromPtr[T any](p *T) T {
	if p == nil {
		var zero T
		return zero
	}
	return *p
}

// tsToGo maps a proto timestamp onto a nullable TIMESTAMPTZ value.
func tsToGo(ts *timestamppb.Timestamp) *time.Time {
	if ts == nil {
		return nil
	}
	t := ts.AsTime()
	return &t
}

// tsToGoVal maps a proto timestamp onto a NOT NULL TIMESTAMPTZ value.
func tsToGoVal(ts *timestamppb.Timestamp) time.Time {
	if ts == nil {
		return time.Time{}
	}
	return ts.AsTime()
}

// goToTs maps a nullable TIMESTAMPTZ value back onto a proto timestamp.
func goToTs(t *time.Time) *timestamppb.Timestamp {
	if t == nil || t.IsZero() {
		return nil
	}
	return timestamppb.New(*t)
}

// goValToTs maps a NOT NULL TIMESTAMPTZ value back onto a proto timestamp.
func goValToTs(t time.Time) *timestamppb.Timestamp {
	if t.IsZero() {
		return nil
	}
	return timestamppb.New(t)
}

// dateToGo maps a proto date onto a nullable DATE value (UTC midnight).
func dateToGo(d *date.Date) *time.Time {
	if d == nil || (d.GetYear() == 0 && d.GetMonth() == 0 && d.GetDay() == 0) {
		return nil
	}
	t := time.Date(int(d.GetYear()), time.Month(d.GetMonth()), int(d.GetDay()), 0, 0, 0, 0, time.UTC)
	return &t
}

// goToDate maps a nullable DATE value back onto a proto date.
func goToDate(t *time.Time) *date.Date {
	if t == nil || t.IsZero() {
		return nil
	}
	return &date.Date{Year: int32(t.Year()), Month: int32(t.Month()), Day: int32(t.Day())}
}

// durToGo maps a proto duration onto a nullable INTERVAL-as-text value
// (Go duration syntax, e.g. "1h30m0s").
func durToGo(d *durationpb.Duration) *string {
	if d == nil {
		return nil
	}
	s := d.AsDuration().String()
	return &s
}

// goToDur parses a stored Go duration string back onto a proto duration.
func goToDur(s *string) *durationpb.Duration {
	if s == nil || *s == "" {
		return nil
	}
	d, err := time.ParseDuration(*s)
	if err != nil {
		return nil
	}
	return durationpb.New(d)
}
