// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  linksql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package linksql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one EventLinks row.
type CreateInput struct {
	// EventId sets the "eventId" column (required).
	EventId string `json:"eventId"`
	// FormatType sets the "formatType" column; the zero value is omitted (column default / NULL).
	FormatType string `json:"formatType,omitzero"`
	// IcalUid sets the "icalUid" column; the zero value is omitted (column default / NULL).
	IcalUid string `json:"icalUid,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// Label sets the "label" column; the zero value is omitted (column default / NULL).
	Label string `json:"label,omitzero"`
	// LanguageCode sets the "languageCode" column; the zero value is omitted (column default / NULL).
	LanguageCode string `json:"languageCode,omitzero"`
	// Relation sets the "relation" column (required).
	Relation string `json:"relation"`
	// Uri sets the "uri" column; the zero value is omitted (column default / NULL).
	Uri string `json:"uri,omitzero"`
	// ValueCase sets the "valueCase" column; the zero value is omitted (column default / NULL).
	ValueCase string `json:"valueCase,omitzero"`
	// XmlReference sets the "xmlReference" column; the zero value is omitted (column default / NULL).
	XmlReference string `json:"xmlReference,omitzero"`
}

// UpdateInput holds the fields to change on a EventLinks row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'event_id' column in the 'event_links' collection.
	EventId graphql.Nullable[string] `json:"eventId"`
	// Update the 'format_type' column in the 'event_links' collection.
	FormatType graphql.Nullable[string] `json:"formatType"`
	// Update the 'ical_uid' column in the 'event_links' collection.
	IcalUid graphql.Nullable[string] `json:"icalUid"`
	// Update the 'id' column in the 'event_links' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'label' column in the 'event_links' collection.
	Label graphql.Nullable[string] `json:"label"`
	// Update the 'language_code' column in the 'event_links' collection.
	LanguageCode graphql.Nullable[string] `json:"languageCode"`
	// Update the 'relation' column in the 'event_links' collection.
	Relation graphql.Nullable[string] `json:"relation"`
	// Update the 'uri' column in the 'event_links' collection.
	Uri graphql.Nullable[string] `json:"uri"`
	// Update the 'value_case' column in the 'event_links' collection.
	ValueCase graphql.Nullable[string] `json:"valueCase"`
	// Update the 'xml_reference' column in the 'event_links' collection.
	XmlReference graphql.Nullable[string] `json:"xmlReference"`
}
