// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  linksql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package linksql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteEventLinksByIdResponse — Responses from the 'delete_event_links_by_id' procedure
type DeleteEventLinksByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// EventId selects the "eventId" field.
		EventId string `graphql:"eventId"`
		// FormatType selects the "formatType" field; nil when the column is NULL.
		FormatType *string `graphql:"formatType"`
		// IcalUid selects the "icalUid" field; nil when the column is NULL.
		IcalUid *string `graphql:"icalUid"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Label selects the "label" field; nil when the column is NULL.
		Label *string `graphql:"label"`
		// LanguageCode selects the "languageCode" field; nil when the column is NULL.
		LanguageCode *string `graphql:"languageCode"`
		// Relation selects the "relation" field.
		Relation string `graphql:"relation"`
		// Uri selects the "uri" field; nil when the column is NULL.
		Uri *string `graphql:"uri"`
		// ValueCase selects the "valueCase" field; nil when the column is NULL.
		ValueCase *string `graphql:"valueCase"`
		// XmlReference selects the "xmlReference" field; nil when the column is NULL.
		XmlReference *string `graphql:"xmlReference"`
	} `graphql:"returning"`
}

// EventLinks is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type EventLinks struct {
	// EventId selects the "eventId" field.
	EventId string `graphql:"eventId"`
	// FormatType selects the "formatType" field; nil when the column is NULL.
	FormatType *string `graphql:"formatType"`
	// IcalUid selects the "icalUid" field; nil when the column is NULL.
	IcalUid *string `graphql:"icalUid"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// Label selects the "label" field; nil when the column is NULL.
	Label *string `graphql:"label"`
	// LanguageCode selects the "languageCode" field; nil when the column is NULL.
	LanguageCode *string `graphql:"languageCode"`
	// Relation selects the "relation" field.
	Relation string `graphql:"relation"`
	// Uri selects the "uri" field; nil when the column is NULL.
	Uri *string `graphql:"uri"`
	// ValueCase selects the "valueCase" field; nil when the column is NULL.
	ValueCase *string `graphql:"valueCase"`
	// XmlReference selects the "xmlReference" field; nil when the column is NULL.
	XmlReference *string `graphql:"xmlReference"`
}

// EventLinksAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type EventLinksAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// EventId selects the "eventId" field.
	EventId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"eventId"`
	// FormatType selects the "formatType" field.
	FormatType struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"formatType"`
	// IcalUid selects the "icalUid" field.
	IcalUid struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"icalUid"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// Label selects the "label" field.
	Label struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"label"`
	// LanguageCode selects the "languageCode" field.
	LanguageCode struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"languageCode"`
	// Relation selects the "relation" field.
	Relation struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"relation"`
	// Uri selects the "uri" field.
	Uri struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"uri"`
	// ValueCase selects the "valueCase" field.
	ValueCase struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"valueCase"`
	// XmlReference selects the "xmlReference" field.
	XmlReference struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"xmlReference"`
}

// InsertEventLinksResponse — Responses from the 'insert_event_links' procedure
type InsertEventLinksResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// EventId selects the "eventId" field.
		EventId string `graphql:"eventId"`
		// FormatType selects the "formatType" field; nil when the column is NULL.
		FormatType *string `graphql:"formatType"`
		// IcalUid selects the "icalUid" field; nil when the column is NULL.
		IcalUid *string `graphql:"icalUid"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Label selects the "label" field; nil when the column is NULL.
		Label *string `graphql:"label"`
		// LanguageCode selects the "languageCode" field; nil when the column is NULL.
		LanguageCode *string `graphql:"languageCode"`
		// Relation selects the "relation" field.
		Relation string `graphql:"relation"`
		// Uri selects the "uri" field; nil when the column is NULL.
		Uri *string `graphql:"uri"`
		// ValueCase selects the "valueCase" field; nil when the column is NULL.
		ValueCase *string `graphql:"valueCase"`
		// XmlReference selects the "xmlReference" field; nil when the column is NULL.
		XmlReference *string `graphql:"xmlReference"`
	} `graphql:"returning"`
}

// UpdateEventLinksByIdResponse — Responses from the 'update_event_links_by_id' procedure
type UpdateEventLinksByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// EventId selects the "eventId" field.
		EventId string `graphql:"eventId"`
		// FormatType selects the "formatType" field; nil when the column is NULL.
		FormatType *string `graphql:"formatType"`
		// IcalUid selects the "icalUid" field; nil when the column is NULL.
		IcalUid *string `graphql:"icalUid"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Label selects the "label" field; nil when the column is NULL.
		Label *string `graphql:"label"`
		// LanguageCode selects the "languageCode" field; nil when the column is NULL.
		LanguageCode *string `graphql:"languageCode"`
		// Relation selects the "relation" field.
		Relation string `graphql:"relation"`
		// Uri selects the "uri" field; nil when the column is NULL.
		Uri *string `graphql:"uri"`
		// ValueCase selects the "valueCase" field; nil when the column is NULL.
		ValueCase *string `graphql:"valueCase"`
		// XmlReference selects the "xmlReference" field; nil when the column is NULL.
		XmlReference *string `graphql:"xmlReference"`
	} `graphql:"returning"`
}
