// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
// source: protobuf/rfc4519/group/v1/ldap_group.proto, protobuf/rfc7643/group/v1/group.proto
//
// database: rfc
// schema:   group
//
// Field-mask merge functions shared by every adapter of this schema.
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package group

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc4519/group/v1/ldapgrouppbv1"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc7643/group/v1/scimgrouppbv1"
)

// applyGroupMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths, and a oneof is
// replaced whole when the mask touches any of its arms — it holds at most one.
func applyGroupMask(merged, in *scimgrouppbv1.Group, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "external_uid") {
		merged.ExternalUid = in.GetExternalUid()
	}
	if repox.InMask(paths, "display_name") {
		merged.DisplayName = in.GetDisplayName()
	}
}

// applyLdapGroupMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths, and a oneof is
// replaced whole when the mask touches any of its arms — it holds at most one.
func applyLdapGroupMask(merged, in *ldapgrouppbv1.LdapGroup, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "display_names") {
		merged.DisplayNames = in.GetDisplayNames()
	}
	if repox.InMask(paths, "descriptions") {
		merged.Descriptions = in.GetDescriptions()
	}
	if repox.InMask(paths, "owners") {
		merged.Owners = in.GetOwners()
	}
	if repox.InMask(paths, "organization") {
		merged.Organization = in.GetOrganization()
	}
	if repox.InMask(paths, "business_categories") {
		merged.BusinessCategories = in.GetBusinessCategories()
	}
}
