// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: protobuf/shared/project/v1/project.proto
//
// database: rfc
// schema:   project
//
// GORM adapters composing the generated models, stores, converters, and filterx specs.
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package project

import (
	"context"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/rfc/project"
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/shared/project/v1/projectpbv1"
	"google.golang.org/protobuf/proto"
	"gorm.io/gorm"
)

// GormProjectRepository is the GORM adapter of ProjectRepository: flat
// CRUD over the generated model, store, converters, and filterx spec. Exported
// fields and helpers are the Tier-2 seam — embed it and override whole methods
// for behavior the schema cannot express; generated methods only call private
// helpers, never the public interface, so overrides never re-enter generated
// code.
type GormProjectRepository struct {
	DB    *gorm.DB
	Hooks ProjectHooks
	// ListOverrides substitute the generated dispatch for single filter fields
	// (e.g. a derived state computed via subqueries).
	ListOverrides map[string]filterx.SQLHandler
}

// NewGormProjectRepository returns the GORM adapter bound to db.
func NewGormProjectRepository(db *gorm.DB) *GormProjectRepository {
	return &GormProjectRepository{DB: db}
}

// Create persists in and returns the stored record.
func (r *GormProjectRepository) Create(ctx context.Context, in *projectpbv1.Project) (*projectpbv1.Project, error) {
	id := repox.NewULID()
	if in.GetName() != "" {
		ids, err := repox.SplitName(in.GetName(), "projects")
		if err != nil {
			return nil, err
		}
		id = ids[len(ids)-1]
	}
	in = proto.Clone(in).(*projectpbv1.Project)
	in.Name = FormatProjectName(id)
	if h := r.Hooks.BeforeCreate; h != nil {
		if err := h(ctx, in); err != nil {
			return nil, err
		}
	}
	m := project.ProjectFromProto(in)
	m.ID = id
	m.Name = in.GetName()
	m.Etag = repox.Ptr(repox.NewULID())
	if err := project.NewProjectStore(r.DB).Create(ctx, m); err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Get returns the record addressed by its resource name.
func (r *GormProjectRepository) Get(ctx context.Context, name string) (*projectpbv1.Project, error) {
	ids, err := repox.SplitName(name, "projects")
	if err != nil {
		return nil, err
	}
	return r.get(ctx, ids[len(ids)-1])
}

// get loads by surrogate key — the private read every generated method re-reads
// through, so Tier-2 overrides of Get never re-enter generated writes.
func (r *GormProjectRepository) get(ctx context.Context, id string) (*projectpbv1.Project, error) {
	var m project.Project
	if err := r.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.toProto(ctx, &m)
}

// toProto converts a loaded row, decorating reference names and running the
// AfterRead hook.
func (r *GormProjectRepository) toProto(ctx context.Context, m *project.Project) (*projectpbv1.Project, error) {
	out := project.ProjectToProto(m)
	if h := r.Hooks.AfterRead; h != nil {
		if err := h(ctx, out); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// List returns one page of records.
func (r *GormProjectRepository) List(ctx context.Context, in repox.ListInput) ([]*projectpbv1.Project, string, error) {
	return r.list(ctx, r.DB, in)
}

func (r *GormProjectRepository) list(ctx context.Context, scope *gorm.DB, in repox.ListInput) ([]*projectpbv1.Project, string, error) {
	conds, err := filterx.Parse(in.Filter)
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	eng := filterx.Gorm[project.Project](project.ProjectFilterSpec)
	for f, h := range r.ListOverrides {
		eng.Override(f, h)
	}
	rows, next, err := eng.List(ctx, scope, filterx.ListInput{
		PageSize:  in.PageSize,
		PageToken: in.PageToken,
		OrderBy:   in.OrderBy,
		Filter:    conds,
	})
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	items := make([]*projectpbv1.Project, 0, len(rows))
	for i := range rows {
		out, err := r.toProto(ctx, &rows[i])
		if err != nil {
			return nil, "", err
		}
		items = append(items, out)
	}
	return items, next, nil
}

// Update persists the masked fields of in; an empty mask replaces every
// mutable field. The write happens in one transaction guarded by in.Etag.
func (r *GormProjectRepository) Update(ctx context.Context, in *projectpbv1.Project, paths []string) (*projectpbv1.Project, error) {
	ids, err := repox.SplitName(in.GetName(), "projects")
	if err != nil {
		return nil, err
	}
	id := ids[len(ids)-1]
	err = r.DB.Transaction(func(tx *gorm.DB) error {
		var existing project.Project
		if err := tx.WithContext(ctx).First(&existing, "id = ?", id).Error; err != nil {
			return err
		}
		if in.GetEtag() != "" && existing.Etag != nil && *existing.Etag != in.GetEtag() {
			return repox.ErrConflict
		}
		existingPB := project.ProjectToProto(&existing)
		merged := proto.Clone(existingPB).(*projectpbv1.Project)
		applyProjectMask(merged, in, paths)
		if h := r.Hooks.BeforeUpdate; h != nil {
			if err := h(ctx, existingPB, merged, paths); err != nil {
				return err
			}
		}
		next := project.ProjectFromProto(merged)
		_ = next
		existing.Name = next.Name
		existing.DisplayName = next.DisplayName
		existing.Description = next.Description
		existing.Owner = next.Owner
		existing.StartTime = next.StartTime
		existing.EndTime = next.EndTime
		existing.Etag = repox.Ptr(repox.NewULID())
		return project.NewProjectStore(tx).Update(ctx, &existing)
	})
	if err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Delete removes the record addressed by its resource name.
func (r *GormProjectRepository) Delete(ctx context.Context, name string) error {
	ids, err := repox.SplitName(name, "projects")
	if err != nil {
		return err
	}
	if h := r.Hooks.BeforeDelete; h != nil {
		if err := h(ctx, name); err != nil {
			return err
		}
	}
	id := ids[len(ids)-1]
	var existing project.Project
	if err := r.DB.WithContext(ctx).First(&existing, "id = ?", id).Error; err != nil {
		return repox.MapGormErr(err)
	}
	return repox.MapGormErr(project.NewProjectStore(r.DB).DeleteByID(ctx, id))
}

// Compile-time proof the adapter satisfies the interface.
var _ ProjectRepository = (*GormProjectRepository)(nil)
