// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
// source: protobuf/shared/project/v1/project.proto
//
// database: rfc
// schema:   project
//
// Proto-facing repository interfaces; adapters compose the generated gorm and GraphQL outputs.
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package project

import (
	"context"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql"
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/shared/project/v1/projectpbv1"
	"gorm.io/gorm"
)

// ProjectRepository is the provider-agnostic persistence surface for
// Project (projects/{project}): full-message writes, AIP-160/AIP-132 lists with
// opaque page tokens, field-mask updates, and etag optimistic concurrency.
type ProjectRepository interface {
	// Create persists m and returns the stored record.
	Create(ctx context.Context, m *projectpbv1.Project) (*projectpbv1.Project, error)
	// Get returns the record addressed by its resource name, or
	// repox.ErrNotFound.
	Get(ctx context.Context, name string) (*projectpbv1.Project, error)
	// List returns one page of records.
	List(ctx context.Context, in repox.ListInput) ([]*projectpbv1.Project, string, error)
	// Update persists the masked fields of m; an empty mask replaces every
	// mutable field. m.Etag, when set, guards against concurrent writes
	// (repox.ErrConflict).
	Update(ctx context.Context, m *projectpbv1.Project, paths []string) (*projectpbv1.Project, error)
	// Delete removes the record addressed by its resource name.
	Delete(ctx context.Context, name string) error
}

// ProjectHooks lets custom logic run inside the generated Project
// adapters without editing them: normalization/derivation before writes,
// derived fields after reads, and guards before deletes. Nil funcs are skipped.
type ProjectHooks struct {
	// BeforeCreate runs after name/id resolution, before the row is written.
	BeforeCreate func(ctx context.Context, m *projectpbv1.Project) error
	// AfterRead runs on every record a read returns (Get, List, and the
	// re-reads writes return).
	AfterRead func(ctx context.Context, m *projectpbv1.Project) error
	// BeforeUpdate runs after the mask is applied to the merged record,
	// before it is written.
	BeforeUpdate func(ctx context.Context, existing, merged *projectpbv1.Project, paths []string) error
	// BeforeDelete runs before the row is removed; returning an error vetoes.
	BeforeDelete func(ctx context.Context, name string) error
}

// Repositories bundles this schema's repository surfaces behind one factory.
type Repositories struct {
	Projects ProjectRepository
}

// options collects the per-resource customizations the factories thread into
// the adapters they build.
type options struct {
	projectHooks        ProjectHooks
	projectOverrides    map[string]filterx.SQLHandler
	projectGQLOverrides map[string]filterx.GraphQLHandler
}

// Option customizes the adapters a factory builds.
type Option func(*options)

// WithProjectHooks installs h on the Project adapters.
func WithProjectHooks(h ProjectHooks) Option {
	return func(o *options) { o.projectHooks = h }
}

// WithProjectListOverride substitutes the generated filter dispatch for one
// Project filter field (e.g. a derived state computed via subqueries).
func WithProjectListOverride(field string, h filterx.SQLHandler) Option {
	return func(o *options) {
		if o.projectOverrides == nil {
			o.projectOverrides = map[string]filterx.SQLHandler{}
		}
		o.projectOverrides[field] = h
	}
}

// WithProjectGraphQLListOverride substitutes the generated filter dispatch
// for one Project filter field on the GraphQL adapters.
func WithProjectGraphQLListOverride(field string, h filterx.GraphQLHandler) Option {
	return func(o *options) {
		if o.projectGQLOverrides == nil {
			o.projectGQLOverrides = map[string]filterx.GraphQLHandler{}
		}
		o.projectGQLOverrides[field] = h
	}
}

// New picks the adapter set for the live handle in conn: GraphQL when a
// client connection is present, otherwise GORM.
func New(conn repox.Conn, opts ...Option) Repositories {
	if conn.GraphQL != nil {
		return NewGraphQL(conn.GraphQL, opts...)
	}
	return NewGorm(conn.Gorm, opts...)
}

// NewGraphQL builds the GraphQL adapter set over svc.
func NewGraphQL(svc *freebusyql.Service, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Projects: &GraphQLProjectRepository{Svc: svc, Hooks: o.projectHooks, ListOverrides: o.projectGQLOverrides},
	}
}

// NewGorm builds the GORM adapter set over db.
func NewGorm(db *gorm.DB, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Projects: &GormProjectRepository{DB: db, Hooks: o.projectHooks, ListOverrides: o.projectOverrides},
	}
}
