// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
// source: protobuf/rfc5545/journal/v1/journal.proto, protobuf/rfc5545/journal/v1/types.proto
//
// database: rfc
// schema:   journal
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package journal

import (
	"context"

	"github.com/oh-tarnished/freebusy/internal/database/rfcgorm/gormx"
	"gorm.io/gorm"
)

// ExtensionPropertyStoreIface is the full data-access surface of ExtensionProperty: everything
// ExtensionPropertyStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedExtensionPropertyStore struct {
//		ExtensionPropertyStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewExtensionPropertyStore returns the concrete
// *ExtensionPropertyStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type ExtensionPropertyStoreIface interface {
	Create(ctx context.Context, m *ExtensionProperty) error
	List(ctx context.Context, opts gormx.ListOptions) ([]ExtensionProperty, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *ExtensionProperty) error
	GetByID(ctx context.Context, id string) (*ExtensionProperty, error)
	DeleteByID(ctx context.Context, id string) error
	ListByJournalID(ctx context.Context, id string, opts gormx.ListOptions) ([]ExtensionProperty, error)
}

// ExtensionPropertyStore provides typed CRUD access to ExtensionProperty records.
// Reference: RFC 5545 "Internet Calendaring and Scheduling Core Object Specification (iCalendar)", section 3.8.8.2. https://www.rfc-editor.org/rfc/rfc5545.html#section-3.8.8.2
type ExtensionPropertyStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewExtensionPropertyStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that ExtensionPropertyStore implements its own interface. Without it a
// signature could drift from ExtensionPropertyStoreIface and only break in whichever downstream
// package decorates it.
var _ ExtensionPropertyStoreIface = (*ExtensionPropertyStore)(nil)

// Compile-time proof that ExtensionPropertyStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[ExtensionProperty] = (*ExtensionPropertyStore)(nil)

// NewExtensionPropertyStore returns a ExtensionPropertyStore backed by db.
func NewExtensionPropertyStore(db *gorm.DB) *ExtensionPropertyStore {
	return &ExtensionPropertyStore{DB: db}
}

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *ExtensionPropertyStore) WithTelemetry(t gormx.Telemetry) *ExtensionPropertyStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *ExtensionPropertyStore) Create(ctx context.Context, m *ExtensionProperty) error {
	return s.DB.WithContext(ctx).Create(m).Error
}

// List returns the ExtensionProperty records matching opts.
func (s *ExtensionPropertyStore) List(ctx context.Context, opts gormx.ListOptions) ([]ExtensionProperty, error) {
	var out []ExtensionProperty
	if err := opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of ExtensionProperty records matching opts.Where
// (pagination and ordering are ignored).
func (s *ExtensionPropertyStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	db := s.DB.WithContext(ctx).Model(&ExtensionProperty{})
	if opts.Where != nil {
		db = db.Where(opts.Where, opts.Args...)
	}
	if err := db.Count(&n).Error; err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *ExtensionPropertyStore) Update(ctx context.Context, m *ExtensionProperty) error {
	return s.DB.WithContext(ctx).Save(m).Error
}

// GetByID fetches the ExtensionProperty with the given primary key.
func (s *ExtensionPropertyStore) GetByID(ctx context.Context, id string) (*ExtensionProperty, error) {
	var m ExtensionProperty
	if err := s.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the ExtensionProperty with the given primary key.
func (s *ExtensionPropertyStore) DeleteByID(ctx context.Context, id string) error {
	return s.DB.WithContext(ctx).Delete(&ExtensionProperty{}, "id = ?", id).Error
}

// ListByJournalID returns the ExtensionProperty records whose journal_id matches id, with opts applied.
func (s *ExtensionPropertyStore) ListByJournalID(ctx context.Context, id string, opts gormx.ListOptions) ([]ExtensionProperty, error) {
	var out []ExtensionProperty
	q := opts.Apply(s.DB.WithContext(ctx).Where("journal_id = ?", id))
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
