// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm dev
// 	protoc (unknown)
// source: freebusy/property/v1/property.proto
//
// database: freebusy
// schema:   property
//
// orm — https://github.com/the-protobuf-project/orm

package property

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// RateOverrideStore provides typed CRUD access to RateOverride records.
// A price override for a span of dates and/or specific weekdays, layered over a unit's base `price`. The price is still interpreted per the unit's pricing_unit (per night, per booking, per person).
type RateOverrideStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewRateOverrideStore(db).WithTelemetry(ormtelemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that RateOverrideStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[RateOverride] = (*RateOverrideStore)(nil)

// NewRateOverrideStore returns a RateOverrideStore backed by db.
func NewRateOverrideStore(db *gorm.DB) *RateOverrideStore { return &RateOverrideStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *RateOverrideStore) WithTelemetry(t gormx.Telemetry) *RateOverrideStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *RateOverrideStore) Create(ctx context.Context, m *RateOverride) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "property.RateOverride/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "property.rate_overrides", "create", time.Since(start), err)
	return err
}

// List returns the RateOverride records matching opts.
func (s *RateOverrideStore) List(ctx context.Context, opts gormx.ListOptions) ([]RateOverride, error) {
	var out []RateOverride
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "property.RateOverride/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "property.rate_overrides", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of RateOverride records matching opts.Where
// (pagination and ordering are ignored).
func (s *RateOverrideStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "property.RateOverride/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&RateOverride{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "property.rate_overrides", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *RateOverrideStore) Update(ctx context.Context, m *RateOverride) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "property.RateOverride/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "property.rate_overrides", "update", time.Since(start), err)
	return err
}

// GetByID fetches the RateOverride with the given primary key.
func (s *RateOverrideStore) GetByID(ctx context.Context, id string) (*RateOverride, error) {
	var m RateOverride
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "property.RateOverride/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "property.rate_overrides", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the RateOverride with the given primary key.
func (s *RateOverrideStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "property.RateOverride/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&RateOverride{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "property.rate_overrides", "delete", time.Since(start), err)
	return err
}

// ListByUnitID returns the RateOverride records whose unit_id matches id, with opts applied.
func (s *RateOverrideStore) ListByUnitID(ctx context.Context, id string, opts gormx.ListOptions) ([]RateOverride, error) {
	var out []RateOverride
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "property.RateOverride/ListByUnitID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("unit_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "property.rate_overrides", "list_by_unit_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListByDateRangeID returns the RateOverride records whose date_range_id matches id, with opts applied.
func (s *RateOverrideStore) ListByDateRangeID(ctx context.Context, id string, opts gormx.ListOptions) ([]RateOverride, error) {
	var out []RateOverride
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "property.RateOverride/ListByDateRangeID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("date_range_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "property.rate_overrides", "list_by_date_range_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListByPriceID returns the RateOverride records whose price_id matches id, with opts applied.
func (s *RateOverrideStore) ListByPriceID(ctx context.Context, id string, opts gormx.ListOptions) ([]RateOverride, error) {
	var out []RateOverride
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "property.RateOverride/ListByPriceID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("price_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "property.rate_overrides", "list_by_price_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}
