// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  usagelimitsql
//
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
//
// store — https://github.com/the-protobuf-project/store

package usagelimitsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PromocodeUsageLimits row.
type CreateInput struct {
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// MaxRedemptions sets the "maxRedemptions" column; the zero value is omitted (column default / NULL).
	MaxRedemptions graphql.Int64 `json:"maxRedemptions,omitzero"`
	// PerCustomerLimit sets the "perCustomerLimit" column; the zero value is omitted (column default / NULL).
	PerCustomerLimit int32 `json:"perCustomerLimit,omitzero"`
}

// UpdateInput holds the fields to change on a PromocodeUsageLimits row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'id' column in the 'promocode_usage_limits' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'max_redemptions' column in the 'promocode_usage_limits' collection.
	MaxRedemptions graphql.Nullable[graphql.Int64] `json:"maxRedemptions"`
	// Update the 'per_customer_limit' column in the 'promocode_usage_limits' collection.
	PerCustomerLimit graphql.Nullable[int32] `json:"perCustomerLimit"`
}
