// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// Field-mask merge functions shared by every adapter of this schema.
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package schedule

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/schedule/v1/schedulepbv1"
)

// applyAvailabilityExceptionMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths, and a oneof is
// replaced whole when the mask touches any of its arms — it holds at most one.
func applyAvailabilityExceptionMask(merged, in *schedulepbv1.AvailabilityException, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "kind") {
		merged.Kind = in.GetKind()
	}
	if repox.InMask(paths, "reason") {
		merged.Reason = in.GetReason()
	}
	if repox.GroupTouched(paths, "window") || repox.GroupTouched(paths, "date_range") {
		merged.Span = in.Span
	}
}
