// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// AIP resource-name codecs for this schema's repositories.
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package schedule

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
)

// FormatAvailabilityExceptionName builds "resources/{resource}/availabilityExceptions/{availability_exception}" from bare ids.
func FormatAvailabilityExceptionName(resource, availabilityException string) string {
	return "resources" + "/" + resource + "/" + "availabilityExceptions" + "/" + availabilityException
}

// ParseAvailabilityExceptionName splits a "resources/{resource}/availabilityExceptions/{availability_exception}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseAvailabilityExceptionName(name string) (resource, availabilityException string, err error) {
	ids, err := repox.SplitName(name, "resources", "availabilityExceptions")
	if err != nil {
		return
	}
	resource = ids[0]
	availabilityException = ids[1]
	return
}
