// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  namesql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package namesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one UserNames row.
type CreateInput struct {
	// DisplayName sets the "displayName" column; the zero value is omitted (column default / NULL).
	DisplayName string `json:"displayName,omitzero"`
	// FamilyName sets the "familyName" column; the zero value is omitted (column default / NULL).
	FamilyName string `json:"familyName,omitzero"`
	// GivenName sets the "givenName" column; the zero value is omitted (column default / NULL).
	GivenName string `json:"givenName,omitzero"`
	// HonorificPrefix sets the "honorificPrefix" column; the zero value is omitted (column default / NULL).
	HonorificPrefix string `json:"honorificPrefix,omitzero"`
	// HonorificSuffix sets the "honorificSuffix" column; the zero value is omitted (column default / NULL).
	HonorificSuffix string `json:"honorificSuffix,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// MiddleNames sets the "middleNames" column; the zero value is omitted (column default / NULL).
	MiddleNames string `json:"middleNames,omitzero"`
}

// UpdateInput holds the fields to change on a UserNames row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'display_name' column in the 'user_names' collection.
	DisplayName graphql.Nullable[string] `json:"displayName"`
	// Update the 'family_name' column in the 'user_names' collection.
	FamilyName graphql.Nullable[string] `json:"familyName"`
	// Update the 'given_name' column in the 'user_names' collection.
	GivenName graphql.Nullable[string] `json:"givenName"`
	// Update the 'honorific_prefix' column in the 'user_names' collection.
	HonorificPrefix graphql.Nullable[string] `json:"honorificPrefix"`
	// Update the 'honorific_suffix' column in the 'user_names' collection.
	HonorificSuffix graphql.Nullable[string] `json:"honorificSuffix"`
	// Update the 'id' column in the 'user_names' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'middle_names' column in the 'user_names' collection.
	MiddleNames graphql.Nullable[string] `json:"middleNames"`
}
