// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  namesql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package namesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteUserNamesByIdResponse — Responses from the 'delete_user_names_by_id' procedure
type DeleteUserNamesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// DisplayName selects the "displayName" field; nil when the column is NULL.
		DisplayName *string `graphql:"displayName"`
		// FamilyName selects the "familyName" field; nil when the column is NULL.
		FamilyName *string `graphql:"familyName"`
		// GivenName selects the "givenName" field; nil when the column is NULL.
		GivenName *string `graphql:"givenName"`
		// HonorificPrefix selects the "honorificPrefix" field; nil when the column is NULL.
		HonorificPrefix *string `graphql:"honorificPrefix"`
		// HonorificSuffix selects the "honorificSuffix" field; nil when the column is NULL.
		HonorificSuffix *string `graphql:"honorificSuffix"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// MiddleNames selects the "middleNames" field; nil when the column is NULL.
		MiddleNames *string `graphql:"middleNames"`
	} `graphql:"returning"`
}

// InsertUserNamesResponse — Responses from the 'insert_user_names' procedure
type InsertUserNamesResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// DisplayName selects the "displayName" field; nil when the column is NULL.
		DisplayName *string `graphql:"displayName"`
		// FamilyName selects the "familyName" field; nil when the column is NULL.
		FamilyName *string `graphql:"familyName"`
		// GivenName selects the "givenName" field; nil when the column is NULL.
		GivenName *string `graphql:"givenName"`
		// HonorificPrefix selects the "honorificPrefix" field; nil when the column is NULL.
		HonorificPrefix *string `graphql:"honorificPrefix"`
		// HonorificSuffix selects the "honorificSuffix" field; nil when the column is NULL.
		HonorificSuffix *string `graphql:"honorificSuffix"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// MiddleNames selects the "middleNames" field; nil when the column is NULL.
		MiddleNames *string `graphql:"middleNames"`
	} `graphql:"returning"`
}

// UpdateUserNamesByIdResponse — Responses from the 'update_user_names_by_id' procedure
type UpdateUserNamesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// DisplayName selects the "displayName" field; nil when the column is NULL.
		DisplayName *string `graphql:"displayName"`
		// FamilyName selects the "familyName" field; nil when the column is NULL.
		FamilyName *string `graphql:"familyName"`
		// GivenName selects the "givenName" field; nil when the column is NULL.
		GivenName *string `graphql:"givenName"`
		// HonorificPrefix selects the "honorificPrefix" field; nil when the column is NULL.
		HonorificPrefix *string `graphql:"honorificPrefix"`
		// HonorificSuffix selects the "honorificSuffix" field; nil when the column is NULL.
		HonorificSuffix *string `graphql:"honorificSuffix"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// MiddleNames selects the "middleNames" field; nil when the column is NULL.
		MiddleNames *string `graphql:"middleNames"`
	} `graphql:"returning"`
}

// UserNames is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type UserNames struct {
	// DisplayName selects the "displayName" field; nil when the column is NULL.
	DisplayName *string `graphql:"displayName"`
	// FamilyName selects the "familyName" field; nil when the column is NULL.
	FamilyName *string `graphql:"familyName"`
	// GivenName selects the "givenName" field; nil when the column is NULL.
	GivenName *string `graphql:"givenName"`
	// HonorificPrefix selects the "honorificPrefix" field; nil when the column is NULL.
	HonorificPrefix *string `graphql:"honorificPrefix"`
	// HonorificSuffix selects the "honorificSuffix" field; nil when the column is NULL.
	HonorificSuffix *string `graphql:"honorificSuffix"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// MiddleNames selects the "middleNames" field; nil when the column is NULL.
	MiddleNames *string `graphql:"middleNames"`
}

// UserNamesAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type UserNamesAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// DisplayName selects the "displayName" field.
	DisplayName struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"displayName"`
	// FamilyName selects the "familyName" field.
	FamilyName struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"familyName"`
	// GivenName selects the "givenName" field.
	GivenName struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"givenName"`
	// HonorificPrefix selects the "honorificPrefix" field.
	HonorificPrefix struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"honorificPrefix"`
	// HonorificSuffix selects the "honorificSuffix" field.
	HonorificSuffix struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"honorificSuffix"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// MiddleNames selects the "middleNames" field.
	MiddleNames struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"middleNames"`
}
