// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  namesql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package namesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for UserNames. Build predicates like DisplayName.Eq(v) and combine
// them with And/Or/Not.
var (
	DisplayName     = graphql.StringField{Col: "displayName"}
	FamilyName      = graphql.StringField{Col: "familyName"}
	GivenName       = graphql.StringField{Col: "givenName"}
	HonorificPrefix = graphql.StringField{Col: "honorificPrefix"}
	HonorificSuffix = graphql.StringField{Col: "honorificSuffix"}
	Id              = graphql.StringField{Col: "id"}
	MiddleNames     = graphql.StringField{Col: "middleNames"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
