// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
// source: freebusy/shared/v1/idempotency.proto, freebusy/shared/v1/types.proto
//
// database: freebusy
// schema:   shared
//
// Field-mask merge functions shared by every adapter of this schema.
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
//
// store — https://github.com/the-protobuf-project/store

package shared

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/shared/v1/sharedpbv1"
)

// applyIdempotencyKeyMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths.
func applyIdempotencyKeyMask(merged, in *sharedpbv1.IdempotencyKey, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "method") {
		merged.Method = in.GetMethod()
	}
	if repox.InMask(paths, "request_id") {
		merged.RequestId = in.GetRequestId()
	}
	if repox.InMask(paths, "state") {
		merged.State = in.GetState()
	}
	if repox.InMask(paths, "response") {
		merged.Response = in.GetResponse()
	}
}
