// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: freebusy/shared/v1/idempotency.proto, freebusy/shared/v1/types.proto
//
// database: freebusy
// schema:   shared
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package shared

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// PriceComponentStoreIface is the full data-access surface of PriceComponent: everything
// PriceComponentStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedPriceComponentStore struct {
//		PriceComponentStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewPriceComponentStore returns the concrete
// *PriceComponentStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type PriceComponentStoreIface interface {
	Create(ctx context.Context, m *PriceComponent) error
	List(ctx context.Context, opts gormx.ListOptions) ([]PriceComponent, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *PriceComponent) error
	GetByID(ctx context.Context, id string) (*PriceComponent, error)
	DeleteByID(ctx context.Context, id string) error
	ListByBookingID(ctx context.Context, id string, opts gormx.ListOptions) ([]PriceComponent, error)
	ListByAmountID(ctx context.Context, id string, opts gormx.ListOptions) ([]PriceComponent, error)
}

// PriceComponentStore provides typed CRUD access to PriceComponent records.
// One line in a price breakdown: a base charge, a fee, a tax, or a discount. Clients branch on `type` and `code`; the signed `amount` rolls up to the booking total (charges positive, discounts negative).
type PriceComponentStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewPriceComponentStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that PriceComponentStore implements its own interface. Without it a
// signature could drift from PriceComponentStoreIface and only break in whichever downstream
// package decorates it.
var _ PriceComponentStoreIface = (*PriceComponentStore)(nil)

// Compile-time proof that PriceComponentStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[PriceComponent] = (*PriceComponentStore)(nil)

// NewPriceComponentStore returns a PriceComponentStore backed by db.
func NewPriceComponentStore(db *gorm.DB) *PriceComponentStore { return &PriceComponentStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *PriceComponentStore) WithTelemetry(t gormx.Telemetry) *PriceComponentStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *PriceComponentStore) Create(ctx context.Context, m *PriceComponent) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "shared.PriceComponent/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "shared.price_components", "create", time.Since(start), err)
	return err
}

// List returns the PriceComponent records matching opts.
func (s *PriceComponentStore) List(ctx context.Context, opts gormx.ListOptions) ([]PriceComponent, error) {
	var out []PriceComponent
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "shared.PriceComponent/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "shared.price_components", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of PriceComponent records matching opts.Where
// (pagination and ordering are ignored).
func (s *PriceComponentStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "shared.PriceComponent/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&PriceComponent{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "shared.price_components", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *PriceComponentStore) Update(ctx context.Context, m *PriceComponent) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "shared.PriceComponent/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "shared.price_components", "update", time.Since(start), err)
	return err
}

// GetByID fetches the PriceComponent with the given primary key.
func (s *PriceComponentStore) GetByID(ctx context.Context, id string) (*PriceComponent, error) {
	var m PriceComponent
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "shared.PriceComponent/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "shared.price_components", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the PriceComponent with the given primary key.
func (s *PriceComponentStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "shared.PriceComponent/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&PriceComponent{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "shared.price_components", "delete", time.Since(start), err)
	return err
}

// ListByBookingID returns the PriceComponent records whose booking_id matches id, with opts applied.
func (s *PriceComponentStore) ListByBookingID(ctx context.Context, id string, opts gormx.ListOptions) ([]PriceComponent, error) {
	var out []PriceComponent
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "shared.PriceComponent/ListByBookingID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("booking_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "shared.price_components", "list_by_booking_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListByAmountID returns the PriceComponent records whose amount_id matches id, with opts applied.
func (s *PriceComponentStore) ListByAmountID(ctx context.Context, id string, opts gormx.ListOptions) ([]PriceComponent, error) {
	var out []PriceComponent
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "shared.PriceComponent/ListByAmountID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("amount_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "shared.price_components", "list_by_amount_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}
