// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
//
// database: freebusyql
// package:  emailsql
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package emailsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one VcardEmails row.
type CreateInput struct {
	// ContactId sets the "contactId" column (required).
	ContactId string `json:"contactId"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// Pref sets the "pref" column; the zero value is omitted (column default / NULL).
	Pref int32 `json:"pref,omitzero"`
	// Types sets the "types" column; the zero value is omitted (column default / NULL).
	Types string `json:"types,omitzero"`
	// Value sets the "value" column (required).
	Value string `json:"value"`
}

// UpdateInput holds the fields to change on a VcardEmails row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'contact_id' column in the 'vcard_emails' collection.
	ContactId graphql.Nullable[string] `json:"contactId"`
	// Update the 'id' column in the 'vcard_emails' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'pref' column in the 'vcard_emails' collection.
	Pref graphql.Nullable[int32] `json:"pref"`
	// Update the 'types' column in the 'vcard_emails' collection.
	Types graphql.Nullable[string] `json:"types"`
	// Update the 'value' column in the 'vcard_emails' collection.
	Value graphql.Nullable[string] `json:"value"`
}
