// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
// source: google/type/money.proto, google/type/postal_address.proto
//
// database: freebusy
// schema:   common
//
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package common

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// MoneyStoreIface is the full data-access surface of Money: everything
// MoneyStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedMoneyStore struct {
//		MoneyStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewMoneyStore returns the concrete
// *MoneyStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type MoneyStoreIface interface {
	Create(ctx context.Context, m *Money) error
	List(ctx context.Context, opts gormx.ListOptions) ([]Money, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *Money) error
	GetByID(ctx context.Context, id string) (*Money, error)
	DeleteByID(ctx context.Context, id string) error
}

// MoneyStore provides typed CRUD access to Money records.
// Represents an amount of money with its currency type.
type MoneyStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewMoneyStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that MoneyStore implements its own interface. Without it a
// signature could drift from MoneyStoreIface and only break in whichever downstream
// package decorates it.
var _ MoneyStoreIface = (*MoneyStore)(nil)

// Compile-time proof that MoneyStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Money] = (*MoneyStore)(nil)

// NewMoneyStore returns a MoneyStore backed by db.
func NewMoneyStore(db *gorm.DB) *MoneyStore { return &MoneyStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *MoneyStore) WithTelemetry(t gormx.Telemetry) *MoneyStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *MoneyStore) Create(ctx context.Context, m *Money) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "common.Money/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "common.moneys", "create", time.Since(start), err)
	return err
}

// List returns the Money records matching opts.
func (s *MoneyStore) List(ctx context.Context, opts gormx.ListOptions) ([]Money, error) {
	var out []Money
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "common.Money/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "common.moneys", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Money records matching opts.Where
// (pagination and ordering are ignored).
func (s *MoneyStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "common.Money/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&Money{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "common.moneys", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *MoneyStore) Update(ctx context.Context, m *Money) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "common.Money/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "common.moneys", "update", time.Since(start), err)
	return err
}

// GetByID fetches the Money with the given primary key.
func (s *MoneyStore) GetByID(ctx context.Context, id string) (*Money, error) {
	var m Money
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "common.Money/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "common.moneys", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Money with the given primary key.
func (s *MoneyStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "common.Money/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&Money{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "common.moneys", "delete", time.Since(start), err)
	return err
}
