// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  resourceql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package resourceql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs OrganizationResource query operations.
type QueryHandler interface {
	// List runs the "organizationResource" query.
	List(ctx context.Context, req ...*ListRequest) ([]OrganizationResource, error)
	// Find runs the "organizationResource" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*OrganizationResource, error)
	// Aggregate runs the "organizationResourceAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*OrganizationResourceAggExp, error)
	// Get runs the "organizationResourceById" query.
	Get(ctx context.Context, id string) (*OrganizationResource, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs OrganizationResource mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteOrganizationResourceById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (DeleteOrganizationResourceByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *DeleteOrganizationResourceByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertOrganizationResource" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (InsertOrganizationResourceResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *InsertOrganizationResourceResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateOrganizationResourceById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (UpdateOrganizationResourceByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (UpdateOrganizationResourceByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *UpdateOrganizationResourceByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs OrganizationResource subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "organizationResource" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "organizationResourceAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "organizationResourceById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[OrganizationResource] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, InsertOrganizationResourceResponse, UpdateOrganizationResourceByIdResponse, DeleteOrganizationResourceByIdResponse] = (*mutationHandler)(nil)
