// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: protobuf/rfc4519/membership/v1/membership.proto
//
// database: rfc
// schema:   membership
//
// Proto↔row/input converters for the GraphQL adapters, with the shared scalar codecs.
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package membership

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/membershipql/resourceql"
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc4519/membership/v1/membershippbv1"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"google.golang.org/protobuf/types/known/timestamppb"
	"time"
)

// tsToStr / strToTs cross the timestamptz boundary as RFC 3339 strings.
func tsToStr(ts *timestamppb.Timestamp) string {
	if ts == nil {
		return ""
	}
	return ts.AsTime().UTC().Format(time.RFC3339Nano)
}

func strToTs(s string) *timestamppb.Timestamp {
	if s == "" {
		return nil
	}
	for _, layout := range []string{time.RFC3339Nano, time.RFC3339, "2006-01-02T15:04:05.999999Z07:00", "2006-01-02T15:04:05"} {
		if t, err := time.Parse(layout, s); err == nil {
			return timestamppb.New(t)
		}
	}
	return nil
}

// membershipToCreateInput maps the proto onto the client's insert input.
// Identity (id, name resolution), parentage, audit timestamps, and etag are
// set by the adapter.
func membershipToCreateInput(in *membershippbv1.Membership) resourceql.CreateInput {
	var ci resourceql.CreateInput
	ci.Name = in.GetName()
	ci.Member = in.GetMember()
	ci.Role = in.GetRole()
	return ci
}

// membershipToUpdatePatch maps the merged proto onto a replace-write
// patch of every mutable column (mask semantics already applied to merged),
// mirroring the gorm adapter's write-back exactly.
func membershipToUpdatePatch(merged *membershippbv1.Membership) resourceql.UpdateInput {
	var patch resourceql.UpdateInput
	patch.Name = graphql.Value(merged.GetName())
	patch.Member = graphql.Value(merged.GetMember())
	if v := merged.GetRole(); v != "" {
		patch.Role = graphql.Value(v)
	} else {
		patch.Role = graphql.Null[string]()
	}
	return patch
}

// membershipFromRow re-hydrates the proto from a client row, decorating
// reference names from their stored bare ids.
func membershipFromRow(row *resourceql.MembershipResource) *membershippbv1.Membership {
	if row == nil {
		return nil
	}
	out := &membershippbv1.Membership{}
	out.Name = row.Name
	out.Member = row.Member
	out.Role = repox.Deref(row.Role)
	out.Etag = repox.Deref(row.Etag)
	out.CreateTime = strToTs(row.CreateTime)
	out.UpdateTime = strToTs(row.UpdateTime)
	return out
}
