// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  extensionpropertiesql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package extensionpropertiesql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs VcardExtensionProperties query operations.
type QueryHandler interface {
	// List runs the "vcardExtensionProperties" query.
	List(ctx context.Context, req ...*ListRequest) ([]VcardExtensionProperties, error)
	// Find runs the "vcardExtensionProperties" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*VcardExtensionProperties, error)
	// Aggregate runs the "vcardExtensionPropertiesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*VcardExtensionPropertiesAggExp, error)
	// Get runs the "vcardExtensionPropertiesById" query.
	Get(ctx context.Context, id string) (*VcardExtensionProperties, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs VcardExtensionProperties mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteVcardExtensionPropertiesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (DeleteVcardExtensionPropertiesByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *DeleteVcardExtensionPropertiesByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertVcardExtensionProperties" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (InsertVcardExtensionPropertiesResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *InsertVcardExtensionPropertiesResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateVcardExtensionPropertiesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (UpdateVcardExtensionPropertiesByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (UpdateVcardExtensionPropertiesByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *UpdateVcardExtensionPropertiesByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs VcardExtensionProperties subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "vcardExtensionProperties" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "vcardExtensionPropertiesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "vcardExtensionPropertiesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[VcardExtensionProperties] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, InsertVcardExtensionPropertiesResponse, UpdateVcardExtensionPropertiesByIdResponse, DeleteVcardExtensionPropertiesByIdResponse] = (*mutationHandler)(nil)
