// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  extensionpropertiesql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package extensionpropertiesql

import (
	"encoding/json"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteJournalExtensionPropertiesByIdResponse — Responses from the 'delete_journal_extension_properties_by_id' procedure
type DeleteJournalExtensionPropertiesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// JournalId selects the "journalId" field.
		JournalId string `graphql:"journalId"`
		// Key selects the "key" field.
		Key string `graphql:"key"`
		// Parameters selects the "parameters" field; nil when the column is NULL.
		Parameters *json.RawMessage `graphql:"parameters" scalar:"true"`
		// Values selects the "values" field.
		Values []*string `graphql:"values"`
	} `graphql:"returning"`
}

// InsertJournalExtensionPropertiesResponse — Responses from the 'insert_journal_extension_properties' procedure
type InsertJournalExtensionPropertiesResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// JournalId selects the "journalId" field.
		JournalId string `graphql:"journalId"`
		// Key selects the "key" field.
		Key string `graphql:"key"`
		// Parameters selects the "parameters" field; nil when the column is NULL.
		Parameters *json.RawMessage `graphql:"parameters" scalar:"true"`
		// Values selects the "values" field.
		Values []*string `graphql:"values"`
	} `graphql:"returning"`
}

// JournalExtensionProperties is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type JournalExtensionProperties struct {
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// JournalId selects the "journalId" field.
	JournalId string `graphql:"journalId"`
	// Key selects the "key" field.
	Key string `graphql:"key"`
	// Parameters selects the "parameters" field; nil when the column is NULL.
	Parameters *json.RawMessage `graphql:"parameters" scalar:"true"`
	// Values selects the "values" field.
	Values []*string `graphql:"values"`
}

// JournalExtensionPropertiesAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type JournalExtensionPropertiesAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// JournalId selects the "journalId" field.
	JournalId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"journalId"`
	// Key selects the "key" field.
	Key struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"key"`
	// Parameters selects the "parameters" field.
	Parameters struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
	} `graphql:"parameters"`
}

// UpdateJournalExtensionPropertiesByIdResponse — Responses from the 'update_journal_extension_properties_by_id' procedure
type UpdateJournalExtensionPropertiesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// JournalId selects the "journalId" field.
		JournalId string `graphql:"journalId"`
		// Key selects the "key" field.
		Key string `graphql:"key"`
		// Parameters selects the "parameters" field; nil when the column is NULL.
		Parameters *json.RawMessage `graphql:"parameters" scalar:"true"`
		// Values selects the "values" field.
		Values []*string `graphql:"values"`
	} `graphql:"returning"`
}
