// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
//
// database: freebusyql
// package:  entityql
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package entityql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for ResourceEntity. Build predicates like Calendar.Eq(v) and combine
// them with And/Or/Not.
var (
	Calendar           = graphql.StringField{Col: "calendar"}
	CreateTime         = graphql.StringField{Col: "createTime"}
	DeleteTime         = graphql.StringField{Col: "deleteTime"}
	Description        = graphql.StringField{Col: "description"}
	DisplayName        = graphql.StringField{Col: "displayName"}
	Etag               = graphql.StringField{Col: "etag"}
	ExpireTime         = graphql.StringField{Col: "expireTime"}
	IcalUid            = graphql.StringField{Col: "icalUid"}
	Id                 = graphql.StringField{Col: "id"}
	Name               = graphql.StringField{Col: "name"}
	OrganizationalUnit = graphql.StringField{Col: "organizationalUnit"}
	Position           = graphql.StringField{Col: "position"}
	Uid                = graphql.StringField{Col: "uid"}
	UpdateTime         = graphql.StringField{Col: "updateTime"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
