// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
// source: freebusy/pricing/v1/pricing.proto
//
// database: freebusy
// schema:   pricing
//
// GORM adapters composing the generated models, stores, converters, and filterx specs.
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
//
// store — https://github.com/the-protobuf-project/store

package pricing

import (
	"context"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/freebusy/common"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/freebusy/pricing"
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/pricing/v1/pricingpbv1"
	"google.golang.org/protobuf/proto"
	"gorm.io/gorm"
)

// GormRatePlanRepository is the GORM adapter of RatePlanRepository: flat
// CRUD over the generated model, store, converters, and filterx spec. Exported
// fields and helpers are the Tier-2 seam — embed it and override whole methods
// for behavior the schema cannot express; generated methods only call private
// helpers, never the public interface, so overrides never re-enter generated
// code.
type GormRatePlanRepository struct {
	DB    *gorm.DB
	Hooks RatePlanHooks
	// ListOverrides substitute the generated dispatch for single filter fields
	// (e.g. a derived state computed via subqueries).
	ListOverrides map[string]filterx.SQLHandler
}

// NewGormRatePlanRepository returns the GORM adapter bound to db.
func NewGormRatePlanRepository(db *gorm.DB) *GormRatePlanRepository {
	return &GormRatePlanRepository{DB: db}
}

// Create persists in and returns the stored record.
func (r *GormRatePlanRepository) Create(ctx context.Context, in *pricingpbv1.RatePlan) (*pricingpbv1.RatePlan, error) {
	id := repox.NewULID()
	if in.GetName() != "" {
		ids, err := repox.SplitName(in.GetName(), "ratePlans")
		if err != nil {
			return nil, err
		}
		id = ids[len(ids)-1]
	}
	in = proto.Clone(in).(*pricingpbv1.RatePlan)
	in.Name = FormatRatePlanName(id)
	if h := r.Hooks.BeforeCreate; h != nil {
		if err := h(ctx, in); err != nil {
			return nil, err
		}
	}
	m := pricing.RatePlanFromProto(in)
	m.ID = id
	m.Name = in.GetName()
	m.Etag = repox.Ptr(repox.NewULID())
	if err := r.DB.Transaction(func(tx *gorm.DB) error {
		if v := in.GetPrice(); v != nil {
			vo := common.MoneyFromProto(v)
			vo.ID = repox.NewULID()
			if err := tx.WithContext(ctx).Create(vo).Error; err != nil {
				return err
			}
			m.PriceID = vo.ID
		}
		return pricing.NewRatePlanStore(tx).Create(ctx, m)
	}); err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Get returns the record addressed by its resource name.
func (r *GormRatePlanRepository) Get(ctx context.Context, name string) (*pricingpbv1.RatePlan, error) {
	ids, err := repox.SplitName(name, "ratePlans")
	if err != nil {
		return nil, err
	}
	return r.get(ctx, ids[len(ids)-1])
}

// get loads by surrogate key — the private read every generated method re-reads
// through, so Tier-2 overrides of Get never re-enter generated writes.
func (r *GormRatePlanRepository) get(ctx context.Context, id string) (*pricingpbv1.RatePlan, error) {
	var m pricing.RatePlan
	if err := r.DB.WithContext(ctx).Preload("Price").First(&m, "id = ?", id).Error; err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.toProto(ctx, &m)
}

// toProto converts a loaded row, decorating reference names and running the
// AfterRead hook.
func (r *GormRatePlanRepository) toProto(ctx context.Context, m *pricing.RatePlan) (*pricingpbv1.RatePlan, error) {
	out := pricing.RatePlanToProto(m)
	if h := r.Hooks.AfterRead; h != nil {
		if err := h(ctx, out); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// List returns one page of records.
func (r *GormRatePlanRepository) List(ctx context.Context, in repox.ListInput) ([]*pricingpbv1.RatePlan, string, error) {
	return r.list(ctx, r.DB, in)
}

func (r *GormRatePlanRepository) list(ctx context.Context, scope *gorm.DB, in repox.ListInput) ([]*pricingpbv1.RatePlan, string, error) {
	conds, err := filterx.Parse(in.Filter)
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	eng := filterx.Gorm[pricing.RatePlan](pricing.RatePlanFilterSpec)
	for f, h := range r.ListOverrides {
		eng.Override(f, h)
	}
	rows, next, err := eng.List(ctx, scope.Preload("Price"), filterx.ListInput{
		PageSize:  in.PageSize,
		PageToken: in.PageToken,
		OrderBy:   in.OrderBy,
		Filter:    conds,
	})
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	items := make([]*pricingpbv1.RatePlan, 0, len(rows))
	for i := range rows {
		out, err := r.toProto(ctx, &rows[i])
		if err != nil {
			return nil, "", err
		}
		items = append(items, out)
	}
	return items, next, nil
}

// Update persists the masked fields of in; an empty mask replaces every
// mutable field. The write happens in one transaction guarded by in.Etag.
func (r *GormRatePlanRepository) Update(ctx context.Context, in *pricingpbv1.RatePlan, paths []string) (*pricingpbv1.RatePlan, error) {
	ids, err := repox.SplitName(in.GetName(), "ratePlans")
	if err != nil {
		return nil, err
	}
	id := ids[len(ids)-1]
	err = r.DB.Transaction(func(tx *gorm.DB) error {
		var existing pricing.RatePlan
		if err := tx.WithContext(ctx).Preload("Price").First(&existing, "id = ?", id).Error; err != nil {
			return err
		}
		var stalePrice string
		if in.GetEtag() != "" && existing.Etag != nil && *existing.Etag != in.GetEtag() {
			return repox.ErrConflict
		}
		existingPB := pricing.RatePlanToProto(&existing)
		merged := proto.Clone(existingPB).(*pricingpbv1.RatePlan)
		applyRatePlanMask(merged, in, paths)
		if h := r.Hooks.BeforeUpdate; h != nil {
			if err := h(ctx, existingPB, merged, paths); err != nil {
				return err
			}
		}
		next := pricing.RatePlanFromProto(merged)
		_ = next
		existing.Name = next.Name
		existing.Resource = next.Resource
		existing.DisplayName = next.DisplayName
		existing.Description = next.Description
		existing.PricingUnit = next.PricingUnit
		if repox.GroupTouched(paths, "price") {
			stalePrice = existing.PriceID
			if v := merged.GetPrice(); v != nil {
				vo := common.MoneyFromProto(v)
				vo.ID = repox.NewULID()
				if err := tx.WithContext(ctx).Create(vo).Error; err != nil {
					return err
				}
				existing.PriceID = vo.ID
			}
		}
		existing.Etag = repox.Ptr(repox.NewULID())
		if err := pricing.NewRatePlanStore(tx).Update(ctx, &existing); err != nil {
			return err
		}
		if stalePrice != "" {
			if err := tx.WithContext(ctx).Delete(&common.Money{}, "id = ?", stalePrice).Error; err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Delete removes the record addressed by its resource name.
func (r *GormRatePlanRepository) Delete(ctx context.Context, name string) error {
	ids, err := repox.SplitName(name, "ratePlans")
	if err != nil {
		return err
	}
	if h := r.Hooks.BeforeDelete; h != nil {
		if err := h(ctx, name); err != nil {
			return err
		}
	}
	id := ids[len(ids)-1]
	var existing pricing.RatePlan
	if err := r.DB.WithContext(ctx).First(&existing, "id = ?", id).Error; err != nil {
		return repox.MapGormErr(err)
	}
	return repox.MapGormErr(r.DB.Transaction(func(tx *gorm.DB) error {
		if err := pricing.NewRatePlanStore(tx).DeleteByID(ctx, id); err != nil {
			return err
		}
		if existing.PriceID != "" {
			if err := tx.WithContext(ctx).Delete(&common.Money{}, "id = ?", existing.PriceID).Error; err != nil {
				return err
			}
		}
		return nil
	}))
}

// Compile-time proof the adapter satisfies the interface.
var _ RatePlanRepository = (*GormRatePlanRepository)(nil)
