// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
// source: freebusy/pricing/v1/pricing.proto
//
// database: freebusy
// schema:   pricing
//
// Field-mask merge functions shared by every adapter of this schema.
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
//
// store — https://github.com/the-protobuf-project/store

package pricing

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/pricing/v1/pricingpbv1"
)

// applyRatePlanMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths.
func applyRatePlanMask(merged, in *pricingpbv1.RatePlan, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "resource") {
		merged.Resource = in.GetResource()
	}
	if repox.InMask(paths, "display_name") {
		merged.DisplayName = in.GetDisplayName()
	}
	if repox.InMask(paths, "description") {
		merged.Description = in.GetDescription()
	}
	if repox.InMask(paths, "pricing_unit") {
		merged.PricingUnit = in.GetPricingUnit()
	}
	if repox.GroupTouched(paths, "price") {
		merged.Price = in.GetPrice()
	}
}
