// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  cardql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package cardql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/cardql/namecomponentsql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/cardql/namesql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/cardql/resourceql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/cardql/speechesql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// Model type aliases for this domain, re-exported from the owning resource packages.
type CardNameComponents = namecomponentsql.CardNameComponents
type CardNameComponentsAggExp = namecomponentsql.CardNameComponentsAggExp
type DeleteCardNameComponentsByIdResponse = namecomponentsql.DeleteCardNameComponentsByIdResponse
type InsertCardNameComponentsResponse = namecomponentsql.InsertCardNameComponentsResponse
type UpdateCardNameComponentsByIdResponse = namecomponentsql.UpdateCardNameComponentsByIdResponse
type CardNames = namesql.CardNames
type CardNamesAggExp = namesql.CardNamesAggExp
type DeleteCardNamesByIdResponse = namesql.DeleteCardNamesByIdResponse
type InsertCardNamesResponse = namesql.InsertCardNamesResponse
type UpdateCardNamesByIdResponse = namesql.UpdateCardNamesByIdResponse
type CardResource = resourceql.CardResource
type CardResourceAggExp = resourceql.CardResourceAggExp
type DeleteCardResourceByIdResponse = resourceql.DeleteCardResourceByIdResponse
type InsertCardResourceResponse = resourceql.InsertCardResourceResponse
type UpdateCardResourceByIdResponse = resourceql.UpdateCardResourceByIdResponse
type CardSpeeches = speechesql.CardSpeeches
type CardSpeechesAggExp = speechesql.CardSpeechesAggExp
type DeleteCardSpeechesByIdResponse = speechesql.DeleteCardSpeechesByIdResponse
type InsertCardSpeechesResponse = speechesql.InsertCardSpeechesResponse
type UpdateCardSpeechesByIdResponse = speechesql.UpdateCardSpeechesByIdResponse

// QueryHandler aggregates query handlers for the cardql domain.
type QueryHandler struct {
	NameComponents namecomponentsql.QueryHandler
	Names          namesql.QueryHandler
	Resource       resourceql.QueryHandler
	Speeches       speechesql.QueryHandler
}

// NewQuery wires every query handler in the domain.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler {
	return QueryHandler{
		NameComponents: namecomponentsql.NewQuery(gql),
		Names:          namesql.NewQuery(gql),
		Resource:       resourceql.NewQuery(gql),
		Speeches:       speechesql.NewQuery(gql),
	}
}

// MutationHandler aggregates mutation handlers for the cardql domain.
type MutationHandler struct {
	NameComponents namecomponentsql.MutationHandler
	Names          namesql.MutationHandler
	Resource       resourceql.MutationHandler
	Speeches       speechesql.MutationHandler
}

// NewMutation wires every mutation handler in the domain.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler {
	return MutationHandler{
		NameComponents: namecomponentsql.NewMutation(gql),
		Names:          namesql.NewMutation(gql),
		Resource:       resourceql.NewMutation(gql),
		Speeches:       speechesql.NewMutation(gql),
	}
}

// SubscriptionHandler aggregates subscription handlers for the cardql domain.
type SubscriptionHandler struct {
	NameComponents namecomponentsql.SubscriptionHandler
	Names          namesql.SubscriptionHandler
	Resource       resourceql.SubscriptionHandler
	Speeches       speechesql.SubscriptionHandler
}

// NewSubscription wires every subscription handler in the domain.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return SubscriptionHandler{
		NameComponents: namecomponentsql.NewSubscription(gql),
		Names:          namesql.NewSubscription(gql),
		Resource:       resourceql.NewSubscription(gql),
		Speeches:       speechesql.NewSubscription(gql),
	}
}
