// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  timezonesql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package timezonesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteVcardTimezonesByIdResponse — Responses from the 'delete_vcard_timezones_by_id' procedure
type DeleteVcardTimezonesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// ContactId selects the "contactId" field.
		ContactId string `graphql:"contactId"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Pref selects the "pref" field; nil when the column is NULL.
		Pref *int32 `graphql:"pref"`
		// Text selects the "text" field; nil when the column is NULL.
		Text *string `graphql:"text"`
		// Types selects the "types" field; nil when the column is NULL.
		Types *string `graphql:"types"`
		// Uri selects the "uri" field; nil when the column is NULL.
		Uri *string `graphql:"uri"`
		// UtcOffset selects the "utcOffset" field; nil when the column is NULL.
		UtcOffset *string `graphql:"utcOffset"`
		// ValueCase selects the "valueCase" field; nil when the column is NULL.
		ValueCase *string `graphql:"valueCase"`
	} `graphql:"returning"`
}

// InsertVcardTimezonesResponse — Responses from the 'insert_vcard_timezones' procedure
type InsertVcardTimezonesResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// ContactId selects the "contactId" field.
		ContactId string `graphql:"contactId"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Pref selects the "pref" field; nil when the column is NULL.
		Pref *int32 `graphql:"pref"`
		// Text selects the "text" field; nil when the column is NULL.
		Text *string `graphql:"text"`
		// Types selects the "types" field; nil when the column is NULL.
		Types *string `graphql:"types"`
		// Uri selects the "uri" field; nil when the column is NULL.
		Uri *string `graphql:"uri"`
		// UtcOffset selects the "utcOffset" field; nil when the column is NULL.
		UtcOffset *string `graphql:"utcOffset"`
		// ValueCase selects the "valueCase" field; nil when the column is NULL.
		ValueCase *string `graphql:"valueCase"`
	} `graphql:"returning"`
}

// UpdateVcardTimezonesByIdResponse — Responses from the 'update_vcard_timezones_by_id' procedure
type UpdateVcardTimezonesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// ContactId selects the "contactId" field.
		ContactId string `graphql:"contactId"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Pref selects the "pref" field; nil when the column is NULL.
		Pref *int32 `graphql:"pref"`
		// Text selects the "text" field; nil when the column is NULL.
		Text *string `graphql:"text"`
		// Types selects the "types" field; nil when the column is NULL.
		Types *string `graphql:"types"`
		// Uri selects the "uri" field; nil when the column is NULL.
		Uri *string `graphql:"uri"`
		// UtcOffset selects the "utcOffset" field; nil when the column is NULL.
		UtcOffset *string `graphql:"utcOffset"`
		// ValueCase selects the "valueCase" field; nil when the column is NULL.
		ValueCase *string `graphql:"valueCase"`
	} `graphql:"returning"`
}

// VcardTimezones is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type VcardTimezones struct {
	// ContactId selects the "contactId" field.
	ContactId string `graphql:"contactId"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// Pref selects the "pref" field; nil when the column is NULL.
	Pref *int32 `graphql:"pref"`
	// Text selects the "text" field; nil when the column is NULL.
	Text *string `graphql:"text"`
	// Types selects the "types" field; nil when the column is NULL.
	Types *string `graphql:"types"`
	// Uri selects the "uri" field; nil when the column is NULL.
	Uri *string `graphql:"uri"`
	// UtcOffset selects the "utcOffset" field; nil when the column is NULL.
	UtcOffset *string `graphql:"utcOffset"`
	// ValueCase selects the "valueCase" field; nil when the column is NULL.
	ValueCase *string `graphql:"valueCase"`
}

// VcardTimezonesAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type VcardTimezonesAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// ContactId selects the "contactId" field.
	ContactId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"contactId"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// Pref selects the "pref" field.
	Pref struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *int32 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *int32 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *int32 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *int32 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *int32 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Int64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"pref"`
	// Text selects the "text" field.
	Text struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"text"`
	// Types selects the "types" field.
	Types struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"types"`
	// Uri selects the "uri" field.
	Uri struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"uri"`
	// UtcOffset selects the "utcOffset" field.
	UtcOffset struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"utcOffset"`
	// ValueCase selects the "valueCase" field.
	ValueCase struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"valueCase"`
}
