// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: freebusy/channel/v1/channel.proto, freebusy/channel/v1/channel_messages.proto
//
// database: freebusy
// schema:   channel
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package channel

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// UnitMappingStoreIface is the full data-access surface of UnitMapping: everything
// UnitMappingStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedUnitMappingStore struct {
//		UnitMappingStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewUnitMappingStore returns the concrete
// *UnitMappingStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type UnitMappingStoreIface interface {
	Create(ctx context.Context, m *UnitMapping) error
	List(ctx context.Context, opts gormx.ListOptions) ([]UnitMapping, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *UnitMapping) error
	GetByID(ctx context.Context, id string) (*UnitMapping, error)
	DeleteByID(ctx context.Context, id string) error
	GetByName(ctx context.Context, v string) (*UnitMapping, error)
	ListByChannelID(ctx context.Context, id string, opts gormx.ListOptions) ([]UnitMapping, error)
}

// UnitMappingStore provides typed CRUD access to UnitMapping records.
// Maps a freebusy Unit to its counterpart on the channel. ARI for a unit only flows once a MAPPED mapping exists: the external room-type and rate-plan ids key the availability/rate/restriction push and resolve inbound reservations back to the right unit.
type UnitMappingStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewUnitMappingStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that UnitMappingStore implements its own interface. Without it a
// signature could drift from UnitMappingStoreIface and only break in whichever downstream
// package decorates it.
var _ UnitMappingStoreIface = (*UnitMappingStore)(nil)

// Compile-time proof that UnitMappingStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[UnitMapping] = (*UnitMappingStore)(nil)

// NewUnitMappingStore returns a UnitMappingStore backed by db.
func NewUnitMappingStore(db *gorm.DB) *UnitMappingStore { return &UnitMappingStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *UnitMappingStore) WithTelemetry(t gormx.Telemetry) *UnitMappingStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *UnitMappingStore) Create(ctx context.Context, m *UnitMapping) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "channel.UnitMapping/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "channel.unit_mappings", "create", time.Since(start), err)
	return err
}

// List returns the UnitMapping records matching opts.
func (s *UnitMappingStore) List(ctx context.Context, opts gormx.ListOptions) ([]UnitMapping, error) {
	var out []UnitMapping
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "channel.UnitMapping/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "channel.unit_mappings", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of UnitMapping records matching opts.Where
// (pagination and ordering are ignored).
func (s *UnitMappingStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "channel.UnitMapping/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&UnitMapping{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "channel.unit_mappings", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *UnitMappingStore) Update(ctx context.Context, m *UnitMapping) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "channel.UnitMapping/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "channel.unit_mappings", "update", time.Since(start), err)
	return err
}

// GetByID fetches the UnitMapping with the given primary key.
func (s *UnitMappingStore) GetByID(ctx context.Context, id string) (*UnitMapping, error) {
	var m UnitMapping
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "channel.UnitMapping/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "channel.unit_mappings", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the UnitMapping with the given primary key.
func (s *UnitMappingStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "channel.UnitMapping/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&UnitMapping{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "channel.unit_mappings", "delete", time.Since(start), err)
	return err
}

// GetByName fetches the UnitMapping with the given name (a unique column).
func (s *UnitMappingStore) GetByName(ctx context.Context, v string) (*UnitMapping, error) {
	var m UnitMapping
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "channel.UnitMapping/GetByName", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "name = ?", v).Error
	})
	tel.RecordOp(ctx, "channel.unit_mappings", "get_by_name", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// ListByChannelID returns the UnitMapping records whose channel_id matches id, with opts applied.
func (s *UnitMappingStore) ListByChannelID(ctx context.Context, id string, opts gormx.ListOptions) ([]UnitMapping, error) {
	var out []UnitMapping
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "channel.UnitMapping/ListByChannelID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("channel_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "channel.unit_mappings", "list_by_channel_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}
