// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  organizationsql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package organizationsql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs VcardOrganizations query operations.
type QueryHandler interface {
	// List runs the "vcardOrganizations" query.
	List(ctx context.Context, req ...*ListRequest) ([]VcardOrganizations, error)
	// Find runs the "vcardOrganizations" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*VcardOrganizations, error)
	// Aggregate runs the "vcardOrganizationsAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*VcardOrganizationsAggExp, error)
	// Get runs the "vcardOrganizationsById" query.
	Get(ctx context.Context, id string) (*VcardOrganizations, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs VcardOrganizations mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteVcardOrganizationsById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (DeleteVcardOrganizationsByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *DeleteVcardOrganizationsByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertVcardOrganizations" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (InsertVcardOrganizationsResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *InsertVcardOrganizationsResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateVcardOrganizationsById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (UpdateVcardOrganizationsByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (UpdateVcardOrganizationsByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *UpdateVcardOrganizationsByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs VcardOrganizations subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "vcardOrganizations" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "vcardOrganizationsAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "vcardOrganizationsById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[VcardOrganizations] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, InsertVcardOrganizationsResponse, UpdateVcardOrganizationsByIdResponse, DeleteVcardOrganizationsByIdResponse] = (*mutationHandler)(nil)
