// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  calendartimesql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package calendartimesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one TodoCalendarTimes row.
type CreateInput struct {
	// Date sets the "date" column; the zero value is omitted (column default / NULL).
	Date string `json:"date,omitzero"`
	// DateTime sets the "dateTime" column; the zero value is omitted (column default / NULL).
	DateTime string `json:"dateTime,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// ValueCase sets the "valueCase" column; the zero value is omitted (column default / NULL).
	ValueCase string `json:"valueCase,omitzero"`
}

// UpdateInput holds the fields to change on a TodoCalendarTimes row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'date' column in the 'todo_calendar_times' collection.
	Date graphql.Nullable[string] `json:"date"`
	// Update the 'date_time' column in the 'todo_calendar_times' collection.
	DateTime graphql.Nullable[string] `json:"dateTime"`
	// Update the 'id' column in the 'todo_calendar_times' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'value_case' column in the 'todo_calendar_times' collection.
	ValueCase graphql.Nullable[string] `json:"valueCase"`
}
