// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
// source: protobuf/rfc4519/organizational_unit/v1/organizational_unit.proto
//
// database: rfc
// schema:   organizational_unit
//
// GORM adapters composing the generated models, stores, converters, and filterx specs.
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package organizationalunit

import (
	"context"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/rfc/organizationalunit"
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc4519/organizational_unit/v1/orgunitpbv1"
	"google.golang.org/protobuf/proto"
	"gorm.io/gorm"
)

// GormOrganizationalUnitRepository is the GORM adapter of OrganizationalUnitRepository: flat
// CRUD over the generated model, store, converters, and filterx spec. Exported
// fields and helpers are the Tier-2 seam — embed it and override whole methods
// for behavior the schema cannot express; generated methods only call private
// helpers, never the public interface, so overrides never re-enter generated
// code.
type GormOrganizationalUnitRepository struct {
	DB    *gorm.DB
	Hooks OrganizationalUnitHooks
	// ListOverrides substitute the generated dispatch for single filter fields
	// (e.g. a derived state computed via subqueries).
	ListOverrides map[string]filterx.SQLHandler
}

// NewGormOrganizationalUnitRepository returns the GORM adapter bound to db.
func NewGormOrganizationalUnitRepository(db *gorm.DB) *GormOrganizationalUnitRepository {
	return &GormOrganizationalUnitRepository{DB: db}
}

// Create persists in and returns the stored record.
func (r *GormOrganizationalUnitRepository) Create(ctx context.Context, in *orgunitpbv1.OrganizationalUnit) (*orgunitpbv1.OrganizationalUnit, error) {
	id := repox.NewULID()
	if in.GetName() != "" {
		ids, err := repox.SplitName(in.GetName(), "organizationalUnits")
		if err != nil {
			return nil, err
		}
		id = ids[len(ids)-1]
	}
	in = proto.Clone(in).(*orgunitpbv1.OrganizationalUnit)
	in.Name = FormatOrganizationalUnitName(id)
	if h := r.Hooks.BeforeCreate; h != nil {
		if err := h(ctx, in); err != nil {
			return nil, err
		}
	}
	m := organizationalunit.OrganizationalUnitFromProto(in)
	m.ID = id
	m.Name = in.GetName()
	m.Etag = repox.Ptr(repox.NewULID())
	if err := organizationalunit.NewOrganizationalUnitStore(r.DB).Create(ctx, m); err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Get returns the record addressed by its resource name.
func (r *GormOrganizationalUnitRepository) Get(ctx context.Context, name string) (*orgunitpbv1.OrganizationalUnit, error) {
	ids, err := repox.SplitName(name, "organizationalUnits")
	if err != nil {
		return nil, err
	}
	return r.get(ctx, ids[len(ids)-1])
}

// get loads by surrogate key — the private read every generated method re-reads
// through, so Tier-2 overrides of Get never re-enter generated writes.
func (r *GormOrganizationalUnitRepository) get(ctx context.Context, id string) (*orgunitpbv1.OrganizationalUnit, error) {
	var m organizationalunit.OrganizationalUnit
	if err := r.DB.WithContext(ctx).First(&m, "id = ?", id).Error; err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.toProto(ctx, &m)
}

// toProto converts a loaded row, decorating reference names and running the
// AfterRead hook.
func (r *GormOrganizationalUnitRepository) toProto(ctx context.Context, m *organizationalunit.OrganizationalUnit) (*orgunitpbv1.OrganizationalUnit, error) {
	out := organizationalunit.OrganizationalUnitToProto(m)
	if h := r.Hooks.AfterRead; h != nil {
		if err := h(ctx, out); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// List returns one page of records.
func (r *GormOrganizationalUnitRepository) List(ctx context.Context, in repox.ListInput) ([]*orgunitpbv1.OrganizationalUnit, string, error) {
	return r.list(ctx, r.DB, in)
}

func (r *GormOrganizationalUnitRepository) list(ctx context.Context, scope *gorm.DB, in repox.ListInput) ([]*orgunitpbv1.OrganizationalUnit, string, error) {
	conds, err := filterx.Parse(in.Filter)
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	eng := filterx.Gorm[organizationalunit.OrganizationalUnit](organizationalunit.OrganizationalUnitFilterSpec)
	for f, h := range r.ListOverrides {
		eng.Override(f, h)
	}
	rows, next, err := eng.List(ctx, scope, filterx.ListInput{
		PageSize:  in.PageSize,
		PageToken: in.PageToken,
		OrderBy:   in.OrderBy,
		Filter:    conds,
	})
	if err != nil {
		return nil, "", repox.MapFilterxErr(err)
	}
	items := make([]*orgunitpbv1.OrganizationalUnit, 0, len(rows))
	for i := range rows {
		out, err := r.toProto(ctx, &rows[i])
		if err != nil {
			return nil, "", err
		}
		items = append(items, out)
	}
	return items, next, nil
}

// Update persists the masked fields of in; an empty mask replaces every
// mutable field. The write happens in one transaction guarded by in.Etag.
func (r *GormOrganizationalUnitRepository) Update(ctx context.Context, in *orgunitpbv1.OrganizationalUnit, paths []string) (*orgunitpbv1.OrganizationalUnit, error) {
	ids, err := repox.SplitName(in.GetName(), "organizationalUnits")
	if err != nil {
		return nil, err
	}
	id := ids[len(ids)-1]
	err = r.DB.Transaction(func(tx *gorm.DB) error {
		var existing organizationalunit.OrganizationalUnit
		if err := tx.WithContext(ctx).First(&existing, "id = ?", id).Error; err != nil {
			return err
		}
		if in.GetEtag() != "" && existing.Etag != nil && *existing.Etag != in.GetEtag() {
			return repox.ErrConflict
		}
		existingPB := organizationalunit.OrganizationalUnitToProto(&existing)
		merged := proto.Clone(existingPB).(*orgunitpbv1.OrganizationalUnit)
		applyOrganizationalUnitMask(merged, in, paths)
		if h := r.Hooks.BeforeUpdate; h != nil {
			if err := h(ctx, existingPB, merged, paths); err != nil {
				return err
			}
		}
		next := organizationalunit.OrganizationalUnitFromProto(merged)
		_ = next
		existing.Name = next.Name
		existing.DisplayNames = next.DisplayNames
		existing.Descriptions = next.Descriptions
		existing.BusinessCategories = next.BusinessCategories
		existing.SeeAlso = next.SeeAlso
		existing.Organization = next.Organization
		existing.Etag = repox.Ptr(repox.NewULID())
		return organizationalunit.NewOrganizationalUnitStore(tx).Update(ctx, &existing)
	})
	if err != nil {
		return nil, repox.MapGormErr(err)
	}
	return r.get(ctx, id)
}

// Delete removes the record addressed by its resource name.
func (r *GormOrganizationalUnitRepository) Delete(ctx context.Context, name string) error {
	ids, err := repox.SplitName(name, "organizationalUnits")
	if err != nil {
		return err
	}
	if h := r.Hooks.BeforeDelete; h != nil {
		if err := h(ctx, name); err != nil {
			return err
		}
	}
	id := ids[len(ids)-1]
	var existing organizationalunit.OrganizationalUnit
	if err := r.DB.WithContext(ctx).First(&existing, "id = ?", id).Error; err != nil {
		return repox.MapGormErr(err)
	}
	return repox.MapGormErr(organizationalunit.NewOrganizationalUnitStore(r.DB).DeleteByID(ctx, id))
}

// Compile-time proof the adapter satisfies the interface.
var _ OrganizationalUnitRepository = (*GormOrganizationalUnitRepository)(nil)
