// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  recurringrulesql
//
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
//
// store — https://github.com/the-protobuf-project/store

package recurringrulesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for ScheduleRecurringRules. Build predicates like Closes.Eq(v) and combine
// them with And/Or/Not.
var (
	Closes     = graphql.StringField{Col: "closes"}
	Id         = graphql.StringField{Col: "id"}
	Opens      = graphql.StringField{Col: "opens"}
	Rrule      = graphql.StringField{Col: "rrule"}
	ScheduleId = graphql.StringField{Col: "scheduleId"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
