// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
//
// database: freebusyql
// package:  telephonesql
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package telephonesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for VcardTelephones. Build predicates like ContactId.Eq(v) and combine
// them with And/Or/Not.
var (
	ContactId = graphql.StringField{Col: "contactId"}
	Features  = graphql.StringField{Col: "features"}
	Id        = graphql.StringField{Col: "id"}
	Pref      = graphql.Int64Field{Col: "pref"}
	Text      = graphql.StringField{Col: "text"}
	Types     = graphql.StringField{Col: "types"}
	Uri       = graphql.StringField{Col: "uri"}
	ValueCase = graphql.StringField{Col: "valueCase"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
