// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: protobuf/rfc7643/user/v1/enterprise.proto, protobuf/rfc7643/user/v1/types.proto, protobuf/rfc7643/user/v1/user.proto
//
// database: rfc
// schema:   user
//
// Field-mask merge functions shared by every adapter of this schema.
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package user

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc7643/user/v1/scimuserpbv1"
)

// applyUserMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths, and a oneof is
// replaced whole when the mask touches any of its arms — it holds at most one.
func applyUserMask(merged, in *scimuserpbv1.User, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "external_uid") {
		merged.ExternalUid = in.GetExternalUid()
	}
	if repox.InMask(paths, "username") {
		merged.Username = in.GetUsername()
	}
	if repox.InMask(paths, "display_name") {
		merged.DisplayName = in.GetDisplayName()
	}
	if repox.InMask(paths, "nickname") {
		merged.Nickname = in.GetNickname()
	}
	if repox.InMask(paths, "profile_uri") {
		merged.ProfileUri = in.GetProfileUri()
	}
	if repox.InMask(paths, "title") {
		merged.Title = in.GetTitle()
	}
	if repox.InMask(paths, "user_type") {
		merged.UserType = in.GetUserType()
	}
	if repox.InMask(paths, "preferred_language_code") {
		merged.PreferredLanguageCode = in.GetPreferredLanguageCode()
	}
	if repox.InMask(paths, "locale") {
		merged.Locale = in.GetLocale()
	}
	if repox.InMask(paths, "time_zone") {
		merged.TimeZone = in.GetTimeZone()
	}
	if repox.InMask(paths, "active") {
		merged.Active = in.GetActive()
	}
	if repox.InMask(paths, "password") {
		merged.Password = in.GetPassword()
	}
	if repox.GroupTouched(paths, "name_components") {
		merged.NameComponents = in.GetNameComponents()
	}
}
