// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  recurrencesql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package recurrencesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for EventRecurrences. Build predicates like BoundCase.Eq(v) and combine
// them with And/Or/Not.
var (
	BoundCase  = graphql.StringField{Col: "boundCase"}
	Count      = graphql.Int64Field{Col: "count"}
	Frequency  = graphql.StringField{Col: "frequency"}
	Id         = graphql.StringField{Col: "id"}
	Interval   = graphql.Int64Field{Col: "interval"}
	LeapMonths = graphql.StringField{Col: "leapMonths"}
	Months     = graphql.StringField{Col: "months"}
	Rscale     = graphql.StringField{Col: "rscale"}
	Skip       = graphql.StringField{Col: "skip"}
	UntilId    = graphql.StringField{Col: "untilId"}
	WeekStart  = graphql.StringField{Col: "weekStart"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
