// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: protobuf/rfc9553/card/v1/card.proto, protobuf/rfc9553/card/v1/name.proto, protobuf/rfc9553/card/v1/speech.proto
//
// database: rfc
// schema:   card
//
// Field-mask merge functions shared by every adapter of this schema.
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package card

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc9553/card/v1/cardpbv1"
)

// applyCardMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths, and a oneof is
// replaced whole when the mask touches any of its arms — it holds at most one.
func applyCardMask(merged, in *cardpbv1.Card, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "jscontact_uid") {
		merged.JscontactUid = in.GetJscontactUid()
	}
	if repox.InMask(paths, "kind") {
		merged.Kind = in.GetKind()
	}
	if repox.GroupTouched(paths, "nicknames") {
		merged.Nicknames = in.GetNicknames()
	}
	if repox.GroupTouched(paths, "organizations") {
		merged.Organizations = in.GetOrganizations()
	}
	if repox.GroupTouched(paths, "titles") {
		merged.Titles = in.GetTitles()
	}
	if repox.GroupTouched(paths, "emails") {
		merged.Emails = in.GetEmails()
	}
	if repox.GroupTouched(paths, "online_services") {
		merged.OnlineServices = in.GetOnlineServices()
	}
	if repox.GroupTouched(paths, "phones") {
		merged.Phones = in.GetPhones()
	}
	if repox.GroupTouched(paths, "preferred_languages") {
		merged.PreferredLanguages = in.GetPreferredLanguages()
	}
	if repox.GroupTouched(paths, "calendars") {
		merged.Calendars = in.GetCalendars()
	}
	if repox.GroupTouched(paths, "scheduling_addresses") {
		merged.SchedulingAddresses = in.GetSchedulingAddresses()
	}
	if repox.GroupTouched(paths, "addresses") {
		merged.Addresses = in.GetAddresses()
	}
	if repox.GroupTouched(paths, "crypto_keys") {
		merged.CryptoKeys = in.GetCryptoKeys()
	}
	if repox.GroupTouched(paths, "directories") {
		merged.Directories = in.GetDirectories()
	}
	if repox.GroupTouched(paths, "links") {
		merged.Links = in.GetLinks()
	}
	if repox.GroupTouched(paths, "media") {
		merged.Media = in.GetMedia()
	}
	if repox.GroupTouched(paths, "anniversaries") {
		merged.Anniversaries = in.GetAnniversaries()
	}
	if repox.InMask(paths, "keywords") {
		merged.Keywords = in.GetKeywords()
	}
	if repox.GroupTouched(paths, "notes") {
		merged.Notes = in.GetNotes()
	}
	if repox.GroupTouched(paths, "personal_info") {
		merged.PersonalInfo = in.GetPersonalInfo()
	}
	if repox.GroupTouched(paths, "relations") {
		merged.Relations = in.GetRelations()
	}
	if repox.InMask(paths, "members") {
		merged.Members = in.GetMembers()
	}
	if repox.InMask(paths, "language_code") {
		merged.LanguageCode = in.GetLanguageCode()
	}
	if repox.InMask(paths, "product_id") {
		merged.ProductId = in.GetProductId()
	}
	if repox.GroupTouched(paths, "jscontact_create_time") {
		merged.JscontactCreateTime = in.GetJscontactCreateTime()
	}
	if repox.GroupTouched(paths, "jscontact_update_time") {
		merged.JscontactUpdateTime = in.GetJscontactUpdateTime()
	}
	if repox.GroupTouched(paths, "jscontact_props") {
		merged.JscontactProps = in.GetJscontactProps()
	}
	if repox.GroupTouched(paths, "name_components") {
		merged.NameComponents = in.GetNameComponents()
	}
	if repox.GroupTouched(paths, "speech") {
		merged.Speech = in.GetSpeech()
	}
}
