// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
// source: protobuf/rfc9553/card/v1/card.proto, protobuf/rfc9553/card/v1/name.proto, protobuf/rfc9553/card/v1/speech.proto
//
// database: rfc
// schema:   card
//
// AIP resource-name codecs for this schema's repositories.
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package card

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
)

// FormatCardName builds "cards/{card}" from bare ids.
func FormatCardName(card string) string {
	return "cards" + "/" + card
}

// ParseCardName splits a "cards/{card}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseCardName(name string) (card string, err error) {
	ids, err := repox.SplitName(name, "cards")
	if err != nil {
		return
	}
	card = ids[0]
	return
}
