// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  resourceql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package resourceql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteMembershipResourceByIdResponse — Responses from the 'delete_membership_resource_by_id' procedure
type DeleteMembershipResourceByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// LdapGroupId selects the "ldapGroupId" field.
		LdapGroupId string `graphql:"ldapGroupId"`
		// Member selects the "member" field.
		Member string `graphql:"member"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// Role selects the "role" field; nil when the column is NULL.
		Role *string `graphql:"role"`
		// Uid selects the "uid" field; nil when the column is NULL.
		Uid *string `graphql:"uid"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}

// InsertMembershipResourceResponse — Responses from the 'insert_membership_resource' procedure
type InsertMembershipResourceResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// LdapGroupId selects the "ldapGroupId" field.
		LdapGroupId string `graphql:"ldapGroupId"`
		// Member selects the "member" field.
		Member string `graphql:"member"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// Role selects the "role" field; nil when the column is NULL.
		Role *string `graphql:"role"`
		// Uid selects the "uid" field; nil when the column is NULL.
		Uid *string `graphql:"uid"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}

// MembershipResource is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type MembershipResource struct {
	// CreateTime selects the "createTime" field.
	CreateTime string `graphql:"createTime"`
	// Etag selects the "etag" field; nil when the column is NULL.
	Etag *string `graphql:"etag"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// LdapGroupId selects the "ldapGroupId" field.
	LdapGroupId string `graphql:"ldapGroupId"`
	// Member selects the "member" field.
	Member string `graphql:"member"`
	// Name selects the "name" field.
	Name string `graphql:"name"`
	// Role selects the "role" field; nil when the column is NULL.
	Role *string `graphql:"role"`
	// Uid selects the "uid" field; nil when the column is NULL.
	Uid *string `graphql:"uid"`
	// UpdateTime selects the "updateTime" field.
	UpdateTime string `graphql:"updateTime"`
}

// MembershipResourceAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type MembershipResourceAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// CreateTime selects the "createTime" field.
	CreateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"createTime"`
	// Etag selects the "etag" field.
	Etag struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"etag"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// LdapGroupId selects the "ldapGroupId" field.
	LdapGroupId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"ldapGroupId"`
	// Member selects the "member" field.
	Member struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"member"`
	// Name selects the "name" field.
	Name struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"name"`
	// Role selects the "role" field.
	Role struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"role"`
	// Uid selects the "uid" field.
	Uid struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"uid"`
	// UpdateTime selects the "updateTime" field.
	UpdateTime struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"updateTime"`
}

// UpdateMembershipResourceByIdResponse — Responses from the 'update_membership_resource_by_id' procedure
type UpdateMembershipResourceByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CreateTime selects the "createTime" field.
		CreateTime string `graphql:"createTime"`
		// Etag selects the "etag" field; nil when the column is NULL.
		Etag *string `graphql:"etag"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// LdapGroupId selects the "ldapGroupId" field.
		LdapGroupId string `graphql:"ldapGroupId"`
		// Member selects the "member" field.
		Member string `graphql:"member"`
		// Name selects the "name" field.
		Name string `graphql:"name"`
		// Role selects the "role" field; nil when the column is NULL.
		Role *string `graphql:"role"`
		// Uid selects the "uid" field; nil when the column is NULL.
		Uid *string `graphql:"uid"`
		// UpdateTime selects the "updateTime" field.
		UpdateTime string `graphql:"updateTime"`
	} `graphql:"returning"`
}
