// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  membersql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package membersql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one GroupMembers row.
type CreateInput struct {
	// AttributeType sets the "attributeType" column; the zero value is omitted (column default / NULL).
	AttributeType string `json:"attributeType,omitzero"`
	// Display sets the "display" column; the zero value is omitted (column default / NULL).
	Display string `json:"display,omitzero"`
	// GroupId sets the "groupId" column (required).
	GroupId string `json:"groupId"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// ReferenceUri sets the "referenceUri" column; the zero value is omitted (column default / NULL).
	ReferenceUri string `json:"referenceUri,omitzero"`
	// Value sets the "value" column (required).
	Value string `json:"value"`
}

// UpdateInput holds the fields to change on a GroupMembers row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'attribute_type' column in the 'group_members' collection.
	AttributeType graphql.Nullable[string] `json:"attributeType"`
	// Update the 'display' column in the 'group_members' collection.
	Display graphql.Nullable[string] `json:"display"`
	// Update the 'group_id' column in the 'group_members' collection.
	GroupId graphql.Nullable[string] `json:"groupId"`
	// Update the 'id' column in the 'group_members' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'reference_uri' column in the 'group_members' collection.
	ReferenceUri graphql.Nullable[string] `json:"referenceUri"`
	// Update the 'value' column in the 'group_members' collection.
	Value graphql.Nullable[string] `json:"value"`
}
