// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
// source: freebusy/organisation/v1/organisation.proto
//
// database: freebusy
// schema:   organisation
//
// Field-mask merge functions shared by every adapter of this schema.
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package organisation

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/organisation/v1/orgpbv1"
)

// applyMemberMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths, and a oneof is
// replaced whole when the mask touches any of its arms — it holds at most one.
func applyMemberMask(merged, in *orgpbv1.Member, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "user") {
		merged.User = in.GetUser()
	}
	if repox.InMask(paths, "email") {
		merged.Email = in.GetEmail()
	}
	if repox.InMask(paths, "role") {
		merged.Role = in.GetRole()
	}
	if repox.InMask(paths, "inviter") {
		merged.Inviter = in.GetInviter()
	}
}

// applyOrganisationMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths, and a oneof is
// replaced whole when the mask touches any of its arms — it holds at most one.
func applyOrganisationMask(merged, in *orgpbv1.Organisation, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "display_name") {
		merged.DisplayName = in.GetDisplayName()
	}
	if repox.InMask(paths, "slug") {
		merged.Slug = in.GetSlug()
	}
	if repox.InMask(paths, "billing_email") {
		merged.BillingEmail = in.GetBillingEmail()
	}
	if repox.GroupTouched(paths, "settings") {
		merged.Settings = in.GetSettings()
	}
}
