// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  feesql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package feesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeletePricingFeesByIdResponse — Responses from the 'delete_pricing_fees_by_id' procedure
type DeletePricingFeesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// AmountId selects the "amountId" field; nil when the column is NULL.
		AmountId *string `graphql:"amountId"`
		// Code selects the "code" field.
		Code string `graphql:"code"`
		// DisplayName selects the "displayName" field; nil when the column is NULL.
		DisplayName *string `graphql:"displayName"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Percent selects the "percent" field; nil when the column is NULL.
		Percent *int32 `graphql:"percent"`
		// PricingUnit selects the "pricingUnit" field; nil when the column is NULL.
		PricingUnit *string `graphql:"pricingUnit"`
		// RatePlanId selects the "ratePlanId" field.
		RatePlanId string `graphql:"ratePlanId"`
		// Taxable selects the "taxable" field; nil when the column is NULL.
		Taxable *bool `graphql:"taxable"`
	} `graphql:"returning"`
}

// InsertPricingFeesResponse — Responses from the 'insert_pricing_fees' procedure
type InsertPricingFeesResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// AmountId selects the "amountId" field; nil when the column is NULL.
		AmountId *string `graphql:"amountId"`
		// Code selects the "code" field.
		Code string `graphql:"code"`
		// DisplayName selects the "displayName" field; nil when the column is NULL.
		DisplayName *string `graphql:"displayName"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Percent selects the "percent" field; nil when the column is NULL.
		Percent *int32 `graphql:"percent"`
		// PricingUnit selects the "pricingUnit" field; nil when the column is NULL.
		PricingUnit *string `graphql:"pricingUnit"`
		// RatePlanId selects the "ratePlanId" field.
		RatePlanId string `graphql:"ratePlanId"`
		// Taxable selects the "taxable" field; nil when the column is NULL.
		Taxable *bool `graphql:"taxable"`
	} `graphql:"returning"`
}

// PricingFees is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type PricingFees struct {
	// AmountId selects the "amountId" field; nil when the column is NULL.
	AmountId *string `graphql:"amountId"`
	// Code selects the "code" field.
	Code string `graphql:"code"`
	// DisplayName selects the "displayName" field; nil when the column is NULL.
	DisplayName *string `graphql:"displayName"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// Percent selects the "percent" field; nil when the column is NULL.
	Percent *int32 `graphql:"percent"`
	// PricingUnit selects the "pricingUnit" field; nil when the column is NULL.
	PricingUnit *string `graphql:"pricingUnit"`
	// RatePlanId selects the "ratePlanId" field.
	RatePlanId string `graphql:"ratePlanId"`
	// Taxable selects the "taxable" field; nil when the column is NULL.
	Taxable *bool `graphql:"taxable"`
}

// PricingFeesAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type PricingFeesAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// AmountId selects the "amountId" field.
	AmountId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"amountId"`
	// Code selects the "code" field.
	Code struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"code"`
	// DisplayName selects the "displayName" field.
	DisplayName struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"displayName"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// Percent selects the "percent" field.
	Percent struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *int32 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *int32 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *int32 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *int32 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *int32 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Int64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"percent"`
	// PricingUnit selects the "pricingUnit" field.
	PricingUnit struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"pricingUnit"`
	// RatePlanId selects the "ratePlanId" field.
	RatePlanId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"ratePlanId"`
	// Taxable selects the "taxable" field.
	Taxable struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// BoolAnd selects the "bool_and" field; nil when the column is NULL.
		BoolAnd *bool `graphql:"bool_and"`
		// BoolOr selects the "bool_or" field; nil when the column is NULL.
		BoolOr *bool `graphql:"bool_or"`
		// Every selects the "every" field; nil when the column is NULL.
		Every *bool `graphql:"every"`
	} `graphql:"taxable"`
}

// UpdatePricingFeesByIdResponse — Responses from the 'update_pricing_fees_by_id' procedure
type UpdatePricingFeesByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// AmountId selects the "amountId" field; nil when the column is NULL.
		AmountId *string `graphql:"amountId"`
		// Code selects the "code" field.
		Code string `graphql:"code"`
		// DisplayName selects the "displayName" field; nil when the column is NULL.
		DisplayName *string `graphql:"displayName"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Percent selects the "percent" field; nil when the column is NULL.
		Percent *int32 `graphql:"percent"`
		// PricingUnit selects the "pricingUnit" field; nil when the column is NULL.
		PricingUnit *string `graphql:"pricingUnit"`
		// RatePlanId selects the "ratePlanId" field.
		RatePlanId string `graphql:"ratePlanId"`
		// Taxable selects the "taxable" field; nil when the column is NULL.
		Taxable *bool `graphql:"taxable"`
	} `graphql:"returning"`
}
