// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm dev
// 	protoc (unknown)
// source: freebusy/identity/v1/guest.proto, freebusy/identity/v1/identity.proto
//
// database: freebusy
// schema:   identity
//
// orm — https://github.com/the-protobuf-project/orm

package identity

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// ForeignerDetailsStore provides typed CRUD access to ForeignerDetails records.
// Foreigner-registration details a hotel must capture for foreign nationals to file Form C with the FRRO within 24 hours of arrival (India). Nationals of exempt countries (e.g. Nepal, Bhutan) and diplomats may omit these.
type ForeignerDetailsStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewForeignerDetailsStore(db).WithTelemetry(ormtelemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that ForeignerDetailsStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[ForeignerDetails] = (*ForeignerDetailsStore)(nil)

// NewForeignerDetailsStore returns a ForeignerDetailsStore backed by db.
func NewForeignerDetailsStore(db *gorm.DB) *ForeignerDetailsStore {
	return &ForeignerDetailsStore{DB: db}
}

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *ForeignerDetailsStore) WithTelemetry(t gormx.Telemetry) *ForeignerDetailsStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *ForeignerDetailsStore) Create(ctx context.Context, m *ForeignerDetails) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "identity.ForeignerDetails/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "identity.foreigner_details", "create", time.Since(start), err)
	return err
}

// List returns the ForeignerDetails records matching opts.
func (s *ForeignerDetailsStore) List(ctx context.Context, opts gormx.ListOptions) ([]ForeignerDetails, error) {
	var out []ForeignerDetails
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "identity.ForeignerDetails/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "identity.foreigner_details", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of ForeignerDetails records matching opts.Where
// (pagination and ordering are ignored).
func (s *ForeignerDetailsStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "identity.ForeignerDetails/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&ForeignerDetails{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "identity.foreigner_details", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *ForeignerDetailsStore) Update(ctx context.Context, m *ForeignerDetails) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "identity.ForeignerDetails/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "identity.foreigner_details", "update", time.Since(start), err)
	return err
}

// GetByID fetches the ForeignerDetails with the given primary key.
func (s *ForeignerDetailsStore) GetByID(ctx context.Context, id string) (*ForeignerDetails, error) {
	var m ForeignerDetails
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "identity.ForeignerDetails/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "identity.foreigner_details", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the ForeignerDetails with the given primary key.
func (s *ForeignerDetailsStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "identity.ForeignerDetails/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&ForeignerDetails{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "identity.foreigner_details", "delete", time.Since(start), err)
	return err
}
