// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  namesql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package namesql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, req ...*ListRequest) ([]VcardNames, error) {
	var out []VcardNames
	var r ListRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.GetLimit()) {
		args["limit"] = graphql.VarPtr(r.GetLimit(), "Int")
	}
	if !graphql.IsOmitted(r.GetOffset()) {
		args["offset"] = graphql.VarPtr(r.GetOffset(), "Int")
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		args["order_by"] = graphql.VarPtr(r.GetOrderBy(), "[VcardNamesOrderByExp!]")
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		args["where"] = graphql.VarPtr(r.GetWhere(), "VcardNamesBoolExp")
	}
	res := <-h.gql.QueryFields(ctx, "vcardNames", &out, args)
	return out, res.Error
}

func (h *queryHandler) Find(ctx context.Context, req ...*ListRequest) (*VcardNames, error) {
	var out []VcardNames
	var r ListRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.GetOffset()) {
		args["offset"] = graphql.VarPtr(r.GetOffset(), "Int")
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		args["order_by"] = graphql.VarPtr(r.GetOrderBy(), "[VcardNamesOrderByExp!]")
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		args["where"] = graphql.VarPtr(r.GetWhere(), "VcardNamesBoolExp")
	}
	args["limit"] = graphql.VarPtr(1, "Int")
	res := <-h.gql.QueryFields(ctx, "vcardNames", &out, args)
	if res.Error != nil {
		return nil, res.Error
	}
	if len(out) == 0 {
		return nil, nil
	}
	return &out[0], nil
}

func (h *queryHandler) Aggregate(ctx context.Context, req ...*AggregateRequest) (*VcardNamesAggExp, error) {
	var out *VcardNamesAggExp
	var r AggregateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	filterInput := map[string]any{}
	if !graphql.IsOmitted(r.GetLimit()) {
		filterInput["limit"] = r.GetLimit()
	}
	if !graphql.IsOmitted(r.GetOffset()) {
		filterInput["offset"] = r.GetOffset()
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		filterInput["order_by"] = r.GetOrderBy()
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		filterInput["where"] = r.GetWhere()
	}
	if len(filterInput) > 0 {
		args["filter_input"] = graphql.VarPtr(filterInput, "VcardNamesFilterInput")
	}
	res := <-h.gql.QueryFields(ctx, "vcardNamesAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) Get(ctx context.Context, id string) (*VcardNames, error) {
	var out *VcardNames
	args := map[string]any{}
	args["id"] = graphql.Var(id, "String1")
	res := <-h.gql.QueryFields(ctx, "vcardNamesById", &out, args)
	return out, res.Error
}
