// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package schedule

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// AvailabilityExceptionStoreIface is the full data-access surface of AvailabilityException: everything
// AvailabilityExceptionStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedAvailabilityExceptionStore struct {
//		AvailabilityExceptionStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewAvailabilityExceptionStore returns the concrete
// *AvailabilityExceptionStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type AvailabilityExceptionStoreIface interface {
	Create(ctx context.Context, m *AvailabilityException) error
	List(ctx context.Context, opts gormx.ListOptions) ([]AvailabilityException, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *AvailabilityException) error
	GetByID(ctx context.Context, id string) (*AvailabilityException, error)
	DeleteByID(ctx context.Context, id string) error
	GetByName(ctx context.Context, v string) (*AvailabilityException, error)
	ListByWindowID(ctx context.Context, id string, opts gormx.ListOptions) ([]AvailabilityException, error)
	ListByDateRangeID(ctx context.Context, id string, opts gormx.ListOptions) ([]AvailabilityException, error)
}

// AvailabilityExceptionStore provides typed CRUD access to AvailabilityException records.
// An override of a unit's normal hours on a specific span: a blackout / holiday closure, or extra hours beyond the recurring rules.
type AvailabilityExceptionStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewAvailabilityExceptionStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that AvailabilityExceptionStore implements its own interface. Without it a
// signature could drift from AvailabilityExceptionStoreIface and only break in whichever downstream
// package decorates it.
var _ AvailabilityExceptionStoreIface = (*AvailabilityExceptionStore)(nil)

// Compile-time proof that AvailabilityExceptionStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[AvailabilityException] = (*AvailabilityExceptionStore)(nil)

// NewAvailabilityExceptionStore returns a AvailabilityExceptionStore backed by db.
func NewAvailabilityExceptionStore(db *gorm.DB) *AvailabilityExceptionStore {
	return &AvailabilityExceptionStore{DB: db}
}

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *AvailabilityExceptionStore) WithTelemetry(t gormx.Telemetry) *AvailabilityExceptionStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *AvailabilityExceptionStore) Create(ctx context.Context, m *AvailabilityException) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.AvailabilityException/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "schedule.availability_exceptions", "create", time.Since(start), err)
	return err
}

// List returns the AvailabilityException records matching opts.
func (s *AvailabilityExceptionStore) List(ctx context.Context, opts gormx.ListOptions) ([]AvailabilityException, error) {
	var out []AvailabilityException
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.AvailabilityException/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.availability_exceptions", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of AvailabilityException records matching opts.Where
// (pagination and ordering are ignored).
func (s *AvailabilityExceptionStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.AvailabilityException/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&AvailabilityException{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "schedule.availability_exceptions", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *AvailabilityExceptionStore) Update(ctx context.Context, m *AvailabilityException) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.AvailabilityException/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "schedule.availability_exceptions", "update", time.Since(start), err)
	return err
}

// GetByID fetches the AvailabilityException with the given primary key.
func (s *AvailabilityExceptionStore) GetByID(ctx context.Context, id string) (*AvailabilityException, error) {
	var m AvailabilityException
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.AvailabilityException/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.availability_exceptions", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the AvailabilityException with the given primary key.
func (s *AvailabilityExceptionStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.AvailabilityException/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&AvailabilityException{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.availability_exceptions", "delete", time.Since(start), err)
	return err
}

// GetByName fetches the AvailabilityException with the given name (a unique column).
func (s *AvailabilityExceptionStore) GetByName(ctx context.Context, v string) (*AvailabilityException, error) {
	var m AvailabilityException
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.AvailabilityException/GetByName", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "name = ?", v).Error
	})
	tel.RecordOp(ctx, "schedule.availability_exceptions", "get_by_name", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// ListByWindowID returns the AvailabilityException records whose window_id matches id, with opts applied.
func (s *AvailabilityExceptionStore) ListByWindowID(ctx context.Context, id string, opts gormx.ListOptions) ([]AvailabilityException, error) {
	var out []AvailabilityException
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.AvailabilityException/ListByWindowID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("window_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.availability_exceptions", "list_by_window_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListByDateRangeID returns the AvailabilityException records whose date_range_id matches id, with opts applied.
func (s *AvailabilityExceptionStore) ListByDateRangeID(ctx context.Context, id string, opts gormx.ListOptions) ([]AvailabilityException, error) {
	var out []AvailabilityException
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.AvailabilityException/ListByDateRangeID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("date_range_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.availability_exceptions", "list_by_date_range_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}
