// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package schedule

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// BufferSettingsStoreIface is the full data-access surface of BufferSettings: everything
// BufferSettingsStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedBufferSettingsStore struct {
//		BufferSettingsStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewBufferSettingsStore returns the concrete
// *BufferSettingsStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type BufferSettingsStoreIface interface {
	Create(ctx context.Context, m *BufferSettings) error
	List(ctx context.Context, opts gormx.ListOptions) ([]BufferSettings, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *BufferSettings) error
	GetByID(ctx context.Context, id string) (*BufferSettings, error)
	DeleteByID(ctx context.Context, id string) error
}

// BufferSettingsStore provides typed CRUD access to BufferSettings records.
// Buffer and notice settings applied around bookings.
type BufferSettingsStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewBufferSettingsStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that BufferSettingsStore implements its own interface. Without it a
// signature could drift from BufferSettingsStoreIface and only break in whichever downstream
// package decorates it.
var _ BufferSettingsStoreIface = (*BufferSettingsStore)(nil)

// Compile-time proof that BufferSettingsStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[BufferSettings] = (*BufferSettingsStore)(nil)

// NewBufferSettingsStore returns a BufferSettingsStore backed by db.
func NewBufferSettingsStore(db *gorm.DB) *BufferSettingsStore { return &BufferSettingsStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *BufferSettingsStore) WithTelemetry(t gormx.Telemetry) *BufferSettingsStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *BufferSettingsStore) Create(ctx context.Context, m *BufferSettings) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.BufferSettings/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "schedule.buffer_settings", "create", time.Since(start), err)
	return err
}

// List returns the BufferSettings records matching opts.
func (s *BufferSettingsStore) List(ctx context.Context, opts gormx.ListOptions) ([]BufferSettings, error) {
	var out []BufferSettings
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.BufferSettings/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.buffer_settings", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of BufferSettings records matching opts.Where
// (pagination and ordering are ignored).
func (s *BufferSettingsStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.BufferSettings/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&BufferSettings{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "schedule.buffer_settings", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *BufferSettingsStore) Update(ctx context.Context, m *BufferSettings) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.BufferSettings/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "schedule.buffer_settings", "update", time.Since(start), err)
	return err
}

// GetByID fetches the BufferSettings with the given primary key.
func (s *BufferSettingsStore) GetByID(ctx context.Context, id string) (*BufferSettings, error) {
	var m BufferSettings
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.BufferSettings/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.buffer_settings", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the BufferSettings with the given primary key.
func (s *BufferSettingsStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.BufferSettings/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&BufferSettings{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.buffer_settings", "delete", time.Since(start), err)
	return err
}
