// Code generated by protoc-gen-orm. DO NOT EDIT.
// versions:
// 	protoc-gen-orm dev
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// orm — https://github.com/the-protobuf-project/orm

package schedule

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// CancellationPolicyStore provides typed CRUD access to CancellationPolicy records.
// Refund rules graded by how far ahead of a booking's start it is cancelled.
type CancellationPolicyStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewCancellationPolicyStore(db).WithTelemetry(ormtelemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that CancellationPolicyStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[CancellationPolicy] = (*CancellationPolicyStore)(nil)

// NewCancellationPolicyStore returns a CancellationPolicyStore backed by db.
func NewCancellationPolicyStore(db *gorm.DB) *CancellationPolicyStore {
	return &CancellationPolicyStore{DB: db}
}

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *CancellationPolicyStore) WithTelemetry(t gormx.Telemetry) *CancellationPolicyStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *CancellationPolicyStore) Create(ctx context.Context, m *CancellationPolicy) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.CancellationPolicy/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "schedule.cancellation_policies", "create", time.Since(start), err)
	return err
}

// List returns the CancellationPolicy records matching opts.
func (s *CancellationPolicyStore) List(ctx context.Context, opts gormx.ListOptions) ([]CancellationPolicy, error) {
	var out []CancellationPolicy
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.CancellationPolicy/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.cancellation_policies", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of CancellationPolicy records matching opts.Where
// (pagination and ordering are ignored).
func (s *CancellationPolicyStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.CancellationPolicy/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&CancellationPolicy{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "schedule.cancellation_policies", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *CancellationPolicyStore) Update(ctx context.Context, m *CancellationPolicy) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.CancellationPolicy/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "schedule.cancellation_policies", "update", time.Since(start), err)
	return err
}

// GetByID fetches the CancellationPolicy with the given primary key.
func (s *CancellationPolicyStore) GetByID(ctx context.Context, id string) (*CancellationPolicy, error) {
	var m CancellationPolicy
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.CancellationPolicy/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.cancellation_policies", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the CancellationPolicy with the given primary key.
func (s *CancellationPolicyStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.CancellationPolicy/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&CancellationPolicy{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.cancellation_policies", "delete", time.Since(start), err)
	return err
}
