// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// AIP-160 filter / AIP-132 order_by specs — data for the shared filterx engines.
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package schedule

import (
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
)

// AvailabilityExceptionFilterSpec is AvailabilityException's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var AvailabilityExceptionFilterSpec = filterx.Spec{
	Table: `"schedule"."availability_exceptions"`,
	Fields: map[string]filterx.FieldSpec{
		"create_time": {Column: "create_time", Kind: filterx.KindTimestamp},
		"kind":        {Column: "kind", Kind: filterx.KindEnum, EnumPrefix: "EXCEPTION_KIND_"},
		"name":        {Column: "name", Kind: filterx.KindText},
		"reason":      {Column: "reason", Kind: filterx.KindText},
	},
	Search: []string{"reason"},
	Sort: map[string]filterx.SortSpec{
		"create_time": {Column: "create_time", Kind: filterx.KindTimestamp, NotNull: true},
		"kind":        {Column: "kind", Kind: filterx.KindEnum, NotNull: true},
		"name":        {Column: "name", Kind: filterx.KindText, NotNull: true},
		"reason":      {Column: "reason", Kind: filterx.KindText},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// ScheduleFilterSpec is Schedule's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var ScheduleFilterSpec = filterx.Spec{
	Table: `"schedule"."resource"`,
	Fields: map[string]filterx.FieldSpec{
		"etag": {Column: "etag", Kind: filterx.KindText},
		"name": {Column: "name", Kind: filterx.KindText},
	},
	Sort: map[string]filterx.SortSpec{
		"etag": {Column: "etag", Kind: filterx.KindText},
		"name": {Column: "name", Kind: filterx.KindText, NotNull: true},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// RecurringRuleFilterSpec is RecurringRule's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var RecurringRuleFilterSpec = filterx.Spec{
	Table: `"schedule"."recurring_rules"`,
	Fields: map[string]filterx.FieldSpec{
		"closes": {Column: "closes", Kind: filterx.KindText},
		"opens":  {Column: "opens", Kind: filterx.KindText},
		"rrule":  {Column: "rrule", Kind: filterx.KindText},
	},
	Sort: map[string]filterx.SortSpec{
		"closes": {Column: "closes", Kind: filterx.KindText},
		"opens":  {Column: "opens", Kind: filterx.KindText},
		"rrule":  {Column: "rrule", Kind: filterx.KindText, NotNull: true},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// StayConstraintsFilterSpec is StayConstraints's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var StayConstraintsFilterSpec = filterx.Spec{
	Table: `"schedule"."stay_constraints"`,
	Fields: map[string]filterx.FieldSpec{
		"advance_max_days": {Column: "advance_max_days", Kind: filterx.KindInt},
		"advance_min_days": {Column: "advance_min_days", Kind: filterx.KindInt},
		"max_nights":       {Column: "max_nights", Kind: filterx.KindInt},
		"min_nights":       {Column: "min_nights", Kind: filterx.KindInt},
	},
	Sort: map[string]filterx.SortSpec{
		"advance_max_days": {Column: "advance_max_days", Kind: filterx.KindInt},
		"advance_min_days": {Column: "advance_min_days", Kind: filterx.KindInt},
		"max_nights":       {Column: "max_nights", Kind: filterx.KindInt},
		"min_nights":       {Column: "min_nights", Kind: filterx.KindInt},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// RefundTierFilterSpec is RefundTier's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var RefundTierFilterSpec = filterx.Spec{
	Table: `"schedule"."refund_tiers"`,
	Fields: map[string]filterx.FieldSpec{
		"refund_percent": {Column: "refund_percent", Kind: filterx.KindInt},
	},
	Sort: map[string]filterx.SortSpec{
		"refund_percent": {Column: "refund_percent", Kind: filterx.KindInt, NotNull: true},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}
