// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package schedule

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// RecurringRuleStoreIface is the full data-access surface of RecurringRule: everything
// RecurringRuleStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedRecurringRuleStore struct {
//		RecurringRuleStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewRecurringRuleStore returns the concrete
// *RecurringRuleStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type RecurringRuleStoreIface interface {
	Create(ctx context.Context, m *RecurringRule) error
	List(ctx context.Context, opts gormx.ListOptions) ([]RecurringRule, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *RecurringRule) error
	GetByID(ctx context.Context, id string) (*RecurringRule, error)
	DeleteByID(ctx context.Context, id string) error
	ListByScheduleID(ctx context.Context, id string, opts gormx.ListOptions) ([]RecurringRule, error)
}

// RecurringRuleStore provides typed CRUD access to RecurringRule records.
// A recurring availability window expressed as an RRULE plus a daily open span. The freebusy engine expands these against the unit's timezone.
type RecurringRuleStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewRecurringRuleStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that RecurringRuleStore implements its own interface. Without it a
// signature could drift from RecurringRuleStoreIface and only break in whichever downstream
// package decorates it.
var _ RecurringRuleStoreIface = (*RecurringRuleStore)(nil)

// Compile-time proof that RecurringRuleStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[RecurringRule] = (*RecurringRuleStore)(nil)

// NewRecurringRuleStore returns a RecurringRuleStore backed by db.
func NewRecurringRuleStore(db *gorm.DB) *RecurringRuleStore { return &RecurringRuleStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *RecurringRuleStore) WithTelemetry(t gormx.Telemetry) *RecurringRuleStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *RecurringRuleStore) Create(ctx context.Context, m *RecurringRule) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.RecurringRule/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "schedule.recurring_rules", "create", time.Since(start), err)
	return err
}

// List returns the RecurringRule records matching opts.
func (s *RecurringRuleStore) List(ctx context.Context, opts gormx.ListOptions) ([]RecurringRule, error) {
	var out []RecurringRule
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.RecurringRule/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.recurring_rules", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of RecurringRule records matching opts.Where
// (pagination and ordering are ignored).
func (s *RecurringRuleStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.RecurringRule/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&RecurringRule{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "schedule.recurring_rules", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *RecurringRuleStore) Update(ctx context.Context, m *RecurringRule) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.RecurringRule/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "schedule.recurring_rules", "update", time.Since(start), err)
	return err
}

// GetByID fetches the RecurringRule with the given primary key.
func (s *RecurringRuleStore) GetByID(ctx context.Context, id string) (*RecurringRule, error) {
	var m RecurringRule
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.RecurringRule/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.recurring_rules", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the RecurringRule with the given primary key.
func (s *RecurringRuleStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.RecurringRule/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&RecurringRule{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.recurring_rules", "delete", time.Since(start), err)
	return err
}

// ListByScheduleID returns the RecurringRule records whose schedule_id matches id, with opts applied.
func (s *RecurringRuleStore) ListByScheduleID(ctx context.Context, id string, opts gormx.ListOptions) ([]RecurringRule, error) {
	var out []RecurringRule
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.RecurringRule/ListByScheduleID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("schedule_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.recurring_rules", "list_by_schedule_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}
