// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package schedule

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// ScheduleStoreIface is the full data-access surface of Schedule: everything
// ScheduleStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedScheduleStore struct {
//		ScheduleStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewScheduleStore returns the concrete
// *ScheduleStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type ScheduleStoreIface interface {
	Create(ctx context.Context, m *Schedule) error
	List(ctx context.Context, opts gormx.ListOptions) ([]Schedule, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *Schedule) error
	GetByID(ctx context.Context, id string) (*Schedule, error)
	DeleteByID(ctx context.Context, id string) error
	GetByName(ctx context.Context, v string) (*Schedule, error)
	ListByBuffersID(ctx context.Context, id string, opts gormx.ListOptions) ([]Schedule, error)
	ListByStayConstraintsID(ctx context.Context, id string, opts gormx.ListOptions) ([]Schedule, error)
	ListByCancellationPolicyID(ctx context.Context, id string, opts gormx.ListOptions) ([]Schedule, error)
}

// ScheduleStore provides typed CRUD access to Schedule records.
// Aggregate read view of a unit's availability configuration: the inputs the freebusy engine consumes. Modeled as a singleton resource, one per unit.
type ScheduleStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewScheduleStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that ScheduleStore implements its own interface. Without it a
// signature could drift from ScheduleStoreIface and only break in whichever downstream
// package decorates it.
var _ ScheduleStoreIface = (*ScheduleStore)(nil)

// Compile-time proof that ScheduleStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Schedule] = (*ScheduleStore)(nil)

// NewScheduleStore returns a ScheduleStore backed by db.
func NewScheduleStore(db *gorm.DB) *ScheduleStore { return &ScheduleStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *ScheduleStore) WithTelemetry(t gormx.Telemetry) *ScheduleStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *ScheduleStore) Create(ctx context.Context, m *Schedule) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.Schedule/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "schedule.resource", "create", time.Since(start), err)
	return err
}

// List returns the Schedule records matching opts.
func (s *ScheduleStore) List(ctx context.Context, opts gormx.ListOptions) ([]Schedule, error) {
	var out []Schedule
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.Schedule/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.resource", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Schedule records matching opts.Where
// (pagination and ordering are ignored).
func (s *ScheduleStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.Schedule/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&Schedule{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "schedule.resource", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *ScheduleStore) Update(ctx context.Context, m *Schedule) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.Schedule/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "schedule.resource", "update", time.Since(start), err)
	return err
}

// GetByID fetches the Schedule with the given primary key.
func (s *ScheduleStore) GetByID(ctx context.Context, id string) (*Schedule, error) {
	var m Schedule
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.Schedule/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.resource", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Schedule with the given primary key.
func (s *ScheduleStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.Schedule/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&Schedule{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.resource", "delete", time.Since(start), err)
	return err
}

// GetByName fetches the Schedule with the given name (a unique column).
func (s *ScheduleStore) GetByName(ctx context.Context, v string) (*Schedule, error) {
	var m Schedule
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.Schedule/GetByName", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "name = ?", v).Error
	})
	tel.RecordOp(ctx, "schedule.resource", "get_by_name", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// ListByBuffersID returns the Schedule records whose buffers_id matches id, with opts applied.
func (s *ScheduleStore) ListByBuffersID(ctx context.Context, id string, opts gormx.ListOptions) ([]Schedule, error) {
	var out []Schedule
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.Schedule/ListByBuffersID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("buffers_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.resource", "list_by_buffers_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListByStayConstraintsID returns the Schedule records whose stay_constraints_id matches id, with opts applied.
func (s *ScheduleStore) ListByStayConstraintsID(ctx context.Context, id string, opts gormx.ListOptions) ([]Schedule, error) {
	var out []Schedule
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.Schedule/ListByStayConstraintsID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("stay_constraints_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.resource", "list_by_stay_constraints_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListByCancellationPolicyID returns the Schedule records whose cancellation_policy_id matches id, with opts applied.
func (s *ScheduleStore) ListByCancellationPolicyID(ctx context.Context, id string, opts gormx.ListOptions) ([]Schedule, error) {
	var out []Schedule
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.Schedule/ListByCancellationPolicyID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("cancellation_policy_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.resource", "list_by_cancellation_policy_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}
