// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
// source: freebusy/schedule/v1/schedule.proto
//
// database: freebusy
// schema:   schedule
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package schedule

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// ScheduleExceptionsStoreIface is the full data-access surface of ScheduleExceptions: everything
// ScheduleExceptionsStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedScheduleExceptionsStore struct {
//		ScheduleExceptionsStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewScheduleExceptionsStore returns the concrete
// *ScheduleExceptionsStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type ScheduleExceptionsStoreIface interface {
	Create(ctx context.Context, m *ScheduleExceptions) error
	List(ctx context.Context, opts gormx.ListOptions) ([]ScheduleExceptions, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *ScheduleExceptions) error
	GetByID(ctx context.Context, id string) (*ScheduleExceptions, error)
	DeleteByID(ctx context.Context, id string) error
	ListByScheduleID(ctx context.Context, id string, opts gormx.ListOptions) ([]ScheduleExceptions, error)
	ListByAvailabilityExceptionID(ctx context.Context, id string, opts gormx.ListOptions) ([]ScheduleExceptions, error)
}

// ScheduleExceptionsStore provides typed CRUD access to ScheduleExceptions records.
// Join table for the many-to-many relation Schedule.exceptions ↔ AvailabilityException.
type ScheduleExceptionsStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewScheduleExceptionsStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that ScheduleExceptionsStore implements its own interface. Without it a
// signature could drift from ScheduleExceptionsStoreIface and only break in whichever downstream
// package decorates it.
var _ ScheduleExceptionsStoreIface = (*ScheduleExceptionsStore)(nil)

// Compile-time proof that ScheduleExceptionsStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[ScheduleExceptions] = (*ScheduleExceptionsStore)(nil)

// NewScheduleExceptionsStore returns a ScheduleExceptionsStore backed by db.
func NewScheduleExceptionsStore(db *gorm.DB) *ScheduleExceptionsStore {
	return &ScheduleExceptionsStore{DB: db}
}

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *ScheduleExceptionsStore) WithTelemetry(t gormx.Telemetry) *ScheduleExceptionsStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *ScheduleExceptionsStore) Create(ctx context.Context, m *ScheduleExceptions) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.ScheduleExceptions/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "schedule.exceptions", "create", time.Since(start), err)
	return err
}

// List returns the ScheduleExceptions records matching opts.
func (s *ScheduleExceptionsStore) List(ctx context.Context, opts gormx.ListOptions) ([]ScheduleExceptions, error) {
	var out []ScheduleExceptions
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.ScheduleExceptions/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.exceptions", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of ScheduleExceptions records matching opts.Where
// (pagination and ordering are ignored).
func (s *ScheduleExceptionsStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.ScheduleExceptions/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&ScheduleExceptions{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "schedule.exceptions", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *ScheduleExceptionsStore) Update(ctx context.Context, m *ScheduleExceptions) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.ScheduleExceptions/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "schedule.exceptions", "update", time.Since(start), err)
	return err
}

// GetByID fetches the ScheduleExceptions with the given primary key.
func (s *ScheduleExceptionsStore) GetByID(ctx context.Context, id string) (*ScheduleExceptions, error) {
	var m ScheduleExceptions
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.ScheduleExceptions/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.exceptions", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the ScheduleExceptions with the given primary key.
func (s *ScheduleExceptionsStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.ScheduleExceptions/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&ScheduleExceptions{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "schedule.exceptions", "delete", time.Since(start), err)
	return err
}

// ListByScheduleID returns the ScheduleExceptions records whose schedule_id matches id, with opts applied.
func (s *ScheduleExceptionsStore) ListByScheduleID(ctx context.Context, id string, opts gormx.ListOptions) ([]ScheduleExceptions, error) {
	var out []ScheduleExceptions
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.ScheduleExceptions/ListByScheduleID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("schedule_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.exceptions", "list_by_schedule_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListByAvailabilityExceptionID returns the ScheduleExceptions records whose availability_exception_id matches id, with opts applied.
func (s *ScheduleExceptionsStore) ListByAvailabilityExceptionID(ctx context.Context, id string, opts gormx.ListOptions) ([]ScheduleExceptions, error) {
	var out []ScheduleExceptions
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "schedule.ScheduleExceptions/ListByAvailabilityExceptionID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("availability_exception_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "schedule.exceptions", "list_by_availability_exception_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}
