// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  scopesql
//
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
//
// store — https://github.com/the-protobuf-project/store

package scopesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PromocodeScopes row.
type CreateInput struct {
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// MinSubtotalId sets the "minSubtotalId" column; the zero value is omitted (column default / NULL).
	MinSubtotalId string `json:"minSubtotalId,omitzero"`
}

// UpdateInput holds the fields to change on a PromocodeScopes row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'id' column in the 'promocode_scopes' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'min_subtotal_id' column in the 'promocode_scopes' collection.
	MinSubtotalId graphql.Nullable[string] `json:"minSubtotalId"`
}
