// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: protobuf/rfc6350/vcard/v1/contact.proto, protobuf/rfc6350/vcard/v1/contact_address.proto, protobuf/rfc6350/vcard/v1/contact_location.proto, protobuf/rfc6350/vcard/v1/contact_method.proto, protobuf/rfc6350/vcard/v1/contact_name.proto, protobuf/rfc6350/vcard/v1/contact_property.proto, protobuf/rfc6350/vcard/v1/contact_relation.proto, protobuf/rfc6350/vcard/v1/contact_speech.proto, protobuf/rfc6350/vcard/v1/date_or_text.proto, protobuf/rfc6350/vcard/v1/types.proto, protobuf/rfc6350/vcard/v1/vcard.proto
//
// database: rfc
// schema:   vcard
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package vcard

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// AddressStoreIface is the full data-access surface of Address: everything
// AddressStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedAddressStore struct {
//		AddressStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewAddressStore returns the concrete
// *AddressStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type AddressStoreIface interface {
	Create(ctx context.Context, m *Address) error
	List(ctx context.Context, opts gormx.ListOptions) ([]Address, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *Address) error
	GetByID(ctx context.Context, id string) (*Address, error)
	DeleteByID(ctx context.Context, id string) error
	ListByContactID(ctx context.Context, id string, opts gormx.ListOptions) ([]Address, error)
}

// AddressStore provides typed CRUD access to Address records.
// Address is the ADR property, RFC 6350 section 6.3.1 <https://www.rfc-editor.org/rfc/rfc6350.html#section-6.3.1>, as extended by RFC 9554 section 2.1 <https://www.rfc-editor.org/rfc/rfc9554.html#section-2.1>. RFC 6350 fixed seven components in a defined order; RFC 9554 section 2.1 appends eleven more, so an address can name a room, a floor, a block or a landmark instead of flattening all of it into street_addresses. This is what makes addresses outside the seven-component Western model representable, and it is why google.type.PostalAddress was rejected for this package -- see docs/adding-data.md. Component order in the wire format is the order of the fields here. Reference: RFC 6350 "vCard Format Specification", section 6.3.1. https://www.rfc-editor.org/rfc/rfc6350.html#section-6.3.1 Reference: RFC 9554 "vCard Format Extensions for JSContact", section 2.1. https://www.rfc-editor.org/rfc/rfc9554.html#section-2.1
type AddressStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewAddressStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that AddressStore implements its own interface. Without it a
// signature could drift from AddressStoreIface and only break in whichever downstream
// package decorates it.
var _ AddressStoreIface = (*AddressStore)(nil)

// Compile-time proof that AddressStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[Address] = (*AddressStore)(nil)

// NewAddressStore returns a AddressStore backed by db.
func NewAddressStore(db *gorm.DB) *AddressStore { return &AddressStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *AddressStore) WithTelemetry(t gormx.Telemetry) *AddressStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *AddressStore) Create(ctx context.Context, m *Address) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "vcard.Address/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "vcard.address", "create", time.Since(start), err)
	return err
}

// List returns the Address records matching opts.
func (s *AddressStore) List(ctx context.Context, opts gormx.ListOptions) ([]Address, error) {
	var out []Address
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "vcard.Address/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "vcard.address", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of Address records matching opts.Where
// (pagination and ordering are ignored).
func (s *AddressStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "vcard.Address/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&Address{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "vcard.address", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *AddressStore) Update(ctx context.Context, m *Address) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "vcard.Address/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "vcard.address", "update", time.Since(start), err)
	return err
}

// GetByID fetches the Address with the given primary key.
func (s *AddressStore) GetByID(ctx context.Context, id string) (*Address, error) {
	var m Address
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "vcard.Address/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "vcard.address", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the Address with the given primary key.
func (s *AddressStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "vcard.Address/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&Address{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "vcard.address", "delete", time.Since(start), err)
	return err
}

// ListByContactID returns the Address records whose contact_id matches id, with opts applied.
func (s *AddressStore) ListByContactID(ctx context.Context, id string, opts gormx.ListOptions) ([]Address, error) {
	var out []Address
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "vcard.Address/ListByContactID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("contact_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "vcard.address", "list_by_contact_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}
