// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  resourceql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package resourceql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/resourceql/entityql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/resourceql/structureddatasql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// Model type aliases for this domain, re-exported from the owning resource packages.
type DeleteResourceEntityByIdResponse = entityql.DeleteResourceEntityByIdResponse
type InsertResourceEntityResponse = entityql.InsertResourceEntityResponse
type ResourceEntity = entityql.ResourceEntity
type ResourceEntityAggExp = entityql.ResourceEntityAggExp
type UpdateResourceEntityByIdResponse = entityql.UpdateResourceEntityByIdResponse
type DeleteResourceStructuredDatasByIdResponse = structureddatasql.DeleteResourceStructuredDatasByIdResponse
type InsertResourceStructuredDatasResponse = structureddatasql.InsertResourceStructuredDatasResponse
type ResourceStructuredDatas = structureddatasql.ResourceStructuredDatas
type ResourceStructuredDatasAggExp = structureddatasql.ResourceStructuredDatasAggExp
type UpdateResourceStructuredDatasByIdResponse = structureddatasql.UpdateResourceStructuredDatasByIdResponse

// QueryHandler aggregates query handlers for the resourceql domain.
type QueryHandler struct {
	Entity          entityql.QueryHandler
	StructuredDatas structureddatasql.QueryHandler
}

// NewQuery wires every query handler in the domain.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler {
	return QueryHandler{
		Entity:          entityql.NewQuery(gql),
		StructuredDatas: structureddatasql.NewQuery(gql),
	}
}

// MutationHandler aggregates mutation handlers for the resourceql domain.
type MutationHandler struct {
	Entity          entityql.MutationHandler
	StructuredDatas structureddatasql.MutationHandler
}

// NewMutation wires every mutation handler in the domain.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler {
	return MutationHandler{
		Entity:          entityql.NewMutation(gql),
		StructuredDatas: structureddatasql.NewMutation(gql),
	}
}

// SubscriptionHandler aggregates subscription handlers for the resourceql domain.
type SubscriptionHandler struct {
	Entity          entityql.SubscriptionHandler
	StructuredDatas structureddatasql.SubscriptionHandler
}

// NewSubscription wires every subscription handler in the domain.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return SubscriptionHandler{
		Entity:          entityql.NewSubscription(gql),
		StructuredDatas: structureddatasql.NewSubscription(gql),
	}
}
