// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: protobuf/rfc4519/organization/v1/organization.proto
//
// database: rfc
// schema:   organization
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package organization

import (
	"time"

	"github.com/lib/pq"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc4519/organization/v1/organizationpbv1"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// OrganizationToProto converts the stored row (with its belongs-to associations,
// when preloaded) to its proto message. Nil in, nil out.
func OrganizationToProto(m *Organization) *organizationpbv1.Organization {
	if m == nil {
		return nil
	}
	out := &organizationpbv1.Organization{}
	out.Name = m.Name
	out.Uid = fromPtr(m.UID)
	out.DisplayNames = []string(m.DisplayNames)
	out.Descriptions = []string(m.Descriptions)
	out.BusinessCategories = []string(m.BusinessCategories)
	out.SeeAlso = []string(m.SeeAlso)
	out.CreateTime = goValToTs(m.CreateTime)
	out.UpdateTime = goValToTs(m.UpdateTime)
	out.Etag = fromPtr(m.Etag)
	out.DeleteTime = goToTs(m.DeleteTime)
	out.ExpireTime = goToTs(m.ExpireTime)
	return out
}

// OrganizationFromProto maps the proto message's data fields onto a fresh row.
// It never invents keys or relations: primary keys, resource references, and
// sub-row graph wiring stay with the caller. Nil in, nil out.
func OrganizationFromProto(pb *organizationpbv1.Organization) *Organization {
	if pb == nil {
		return nil
	}
	m := &Organization{}
	m.Name = pb.GetName()
	m.UID = toPtr(pb.GetUid())
	m.DisplayNames = pq.StringArray(pb.GetDisplayNames())
	m.Descriptions = pq.StringArray(pb.GetDescriptions())
	m.BusinessCategories = pq.StringArray(pb.GetBusinessCategories())
	m.SeeAlso = pq.StringArray(pb.GetSeeAlso())
	m.Etag = toPtr(pb.GetEtag())
	m.DeleteTime = tsToGo(pb.GetDeleteTime())
	m.ExpireTime = tsToGo(pb.GetExpireTime())
	return m
}

// toPtr returns a pointer to v, or nil for the zero value — a nullable column
// stores absence, not the proto zero.
func toPtr[T comparable](v T) *T {
	var zero T
	if v == zero {
		return nil
	}
	return &v
}

// fromPtr dereferences p, returning the zero value for nil.
func fromPtr[T any](p *T) T {
	if p == nil {
		var zero T
		return zero
	}
	return *p
}

// tsToGo maps a proto timestamp onto a nullable TIMESTAMPTZ value.
func tsToGo(ts *timestamppb.Timestamp) *time.Time {
	if ts == nil {
		return nil
	}
	t := ts.AsTime()
	return &t
}

// tsToGoVal maps a proto timestamp onto a NOT NULL TIMESTAMPTZ value.
func tsToGoVal(ts *timestamppb.Timestamp) time.Time {
	if ts == nil {
		return time.Time{}
	}
	return ts.AsTime()
}

// goToTs maps a nullable TIMESTAMPTZ value back onto a proto timestamp.
func goToTs(t *time.Time) *timestamppb.Timestamp {
	if t == nil || t.IsZero() {
		return nil
	}
	return timestamppb.New(*t)
}

// goValToTs maps a NOT NULL TIMESTAMPTZ value back onto a proto timestamp.
func goValToTs(t time.Time) *timestamppb.Timestamp {
	if t.IsZero() {
		return nil
	}
	return timestamppb.New(t)
}
