// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
// source: protobuf/rfc7953/availability/v1/availability.proto, protobuf/rfc7953/availability/v1/available.proto, protobuf/rfc7953/availability/v1/types.proto
//
// database: rfc
// schema:   availability
//
// Proto-facing repository interfaces; adapters compose the generated gorm and GraphQL outputs.
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package availability

import (
	"context"
	"github.com/oh-tarnished/freebusy/internal/database/rfcgorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/rfcrepo/repox"
	availabilityv1 "github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc7953/availability/v1"
	"gorm.io/gorm"
)

// AvailabilityRepository is the provider-agnostic persistence surface for
// Availability (calendars/{calendar}/availabilities/{availability}): full-message writes, AIP-160/AIP-132 lists with
// opaque page tokens, field-mask updates, and etag optimistic concurrency.
type AvailabilityRepository interface {
	// Create persists m under parent and returns the stored record.
	Create(ctx context.Context, parent string, m *availabilityv1.Availability) (*availabilityv1.Availability, error)
	// Get returns the record addressed by its resource name, or
	// repox.ErrNotFound.
	Get(ctx context.Context, name string) (*availabilityv1.Availability, error)
	// List returns one page of records under parent.
	List(ctx context.Context, parent string, in repox.ListInput) ([]*availabilityv1.Availability, string, error)
	// Update persists the masked fields of m; an empty mask replaces every
	// mutable field. m.Etag, when set, guards against concurrent writes
	// (repox.ErrConflict).
	Update(ctx context.Context, m *availabilityv1.Availability, paths []string) (*availabilityv1.Availability, error)
	// Delete removes the record addressed by its resource name.
	Delete(ctx context.Context, name string) error
}

// AvailabilityHooks lets custom logic run inside the generated Availability
// adapters without editing them: normalization/derivation before writes,
// derived fields after reads, and guards before deletes. Nil funcs are skipped.
type AvailabilityHooks struct {
	// BeforeCreate runs after name/id resolution, before the row is written.
	BeforeCreate func(ctx context.Context, m *availabilityv1.Availability) error
	// AfterRead runs on every record a read returns (Get, List, and the
	// re-reads writes return).
	AfterRead func(ctx context.Context, m *availabilityv1.Availability) error
	// BeforeUpdate runs after the mask is applied to the merged record,
	// before it is written.
	BeforeUpdate func(ctx context.Context, existing, merged *availabilityv1.Availability, paths []string) error
	// BeforeDelete runs before the row is removed; returning an error vetoes.
	BeforeDelete func(ctx context.Context, name string) error
}

// Repositories bundles this schema's repository surfaces behind one factory.
type Repositories struct {
	Availabilities AvailabilityRepository
}

// options collects the per-resource customizations the factories thread into
// the adapters they build.
type options struct {
	availabilityHooks     AvailabilityHooks
	availabilityOverrides map[string]filterx.SQLHandler
}

// Option customizes the adapters a factory builds.
type Option func(*options)

// WithAvailabilityHooks installs h on the Availability adapters.
func WithAvailabilityHooks(h AvailabilityHooks) Option {
	return func(o *options) { o.availabilityHooks = h }
}

// WithAvailabilityListOverride substitutes the generated filter dispatch for one
// Availability filter field (e.g. a derived state computed via subqueries).
func WithAvailabilityListOverride(field string, h filterx.SQLHandler) Option {
	return func(o *options) {
		if o.availabilityOverrides == nil {
			o.availabilityOverrides = map[string]filterx.SQLHandler{}
		}
		o.availabilityOverrides[field] = h
	}
}

// New picks the adapter set for the live handle in conn.
func New(conn repox.Conn, opts ...Option) Repositories {
	return NewGorm(conn.Gorm, opts...)
}

// NewGorm builds the GORM adapter set over db.
func NewGorm(db *gorm.DB, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Availabilities: &GormAvailabilityRepository{DB: db, Hooks: o.availabilityHooks, ListOverrides: o.availabilityOverrides},
	}
}
