// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
// source: freebusy/channel/v1/channel.proto, freebusy/channel/v1/channel_messages.proto
//
// database: freebusy
// schema:   channel
//
// AIP resource-name codecs for this schema's repositories.
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
//
// store — https://github.com/the-protobuf-project/store

package channel

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
)

// FormatChannelName builds "channels/{channel}" from bare ids.
func FormatChannelName(channel string) string {
	return "channels" + "/" + channel
}

// ParseChannelName splits a "channels/{channel}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseChannelName(name string) (channel string, err error) {
	ids, err := repox.SplitName(name, "channels")
	if err != nil {
		return
	}
	channel = ids[0]
	return
}

// FormatUnitMappingName builds "channels/{channel}/unitMappings/{unit_mapping}" from bare ids.
func FormatUnitMappingName(channel, unitMapping string) string {
	return "channels" + "/" + channel + "/" + "unitMappings" + "/" + unitMapping
}

// ParseUnitMappingName splits a "channels/{channel}/unitMappings/{unit_mapping}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseUnitMappingName(name string) (channel, unitMapping string, err error) {
	ids, err := repox.SplitName(name, "channels", "unitMappings")
	if err != nil {
		return
	}
	channel = ids[0]
	unitMapping = ids[1]
	return
}
