// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
//
// database: freebusyql
// package:  pronounsql
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package pronounsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for VcardPronouns. Build predicates like ContactId.Eq(v) and combine
// them with And/Or/Not.
var (
	ContactId    = graphql.StringField{Col: "contactId"}
	Id           = graphql.StringField{Col: "id"}
	LanguageCode = graphql.StringField{Col: "languageCode"}
	Pref         = graphql.Int64Field{Col: "pref"}
	Types        = graphql.StringField{Col: "types"}
	Value        = graphql.StringField{Col: "value"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
