// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
// source: protobuf/rfc5545/journal/v1/journal.proto, protobuf/rfc5545/journal/v1/types.proto
//
// database: rfc
// schema:   journal
//
// Proto-facing repository interfaces; adapters compose the generated gorm and GraphQL outputs.
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package journal

import (
	"context"
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql"
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc5545/journal/v1/journalpbv1"
	"gorm.io/gorm"
)

// JournalRepository is the provider-agnostic persistence surface for
// Journal (calendars/{calendar}/journals/{journal}): full-message writes, AIP-160/AIP-132 lists with
// opaque page tokens, field-mask updates, and etag optimistic concurrency.
type JournalRepository interface {
	// Create persists m under parent and returns the stored record.
	Create(ctx context.Context, parent string, m *journalpbv1.Journal) (*journalpbv1.Journal, error)
	// Get returns the record addressed by its resource name, or
	// repox.ErrNotFound.
	Get(ctx context.Context, name string) (*journalpbv1.Journal, error)
	// List returns one page of records under parent.
	List(ctx context.Context, parent string, in repox.ListInput) ([]*journalpbv1.Journal, string, error)
	// Update persists the masked fields of m; an empty mask replaces every
	// mutable field. m.Etag, when set, guards against concurrent writes
	// (repox.ErrConflict).
	Update(ctx context.Context, m *journalpbv1.Journal, paths []string) (*journalpbv1.Journal, error)
	// Delete removes the record addressed by its resource name.
	Delete(ctx context.Context, name string) error
}

// JournalHooks lets custom logic run inside the generated Journal
// adapters without editing them: normalization/derivation before writes,
// derived fields after reads, and guards before deletes. Nil funcs are skipped.
type JournalHooks struct {
	// BeforeCreate runs after name/id resolution, before the row is written.
	BeforeCreate func(ctx context.Context, m *journalpbv1.Journal) error
	// AfterRead runs on every record a read returns (Get, List, and the
	// re-reads writes return).
	AfterRead func(ctx context.Context, m *journalpbv1.Journal) error
	// BeforeUpdate runs after the mask is applied to the merged record,
	// before it is written.
	BeforeUpdate func(ctx context.Context, existing, merged *journalpbv1.Journal, paths []string) error
	// BeforeDelete runs before the row is removed; returning an error vetoes.
	BeforeDelete func(ctx context.Context, name string) error
}

// Repositories bundles this schema's repository surfaces behind one factory.
type Repositories struct {
	Journals JournalRepository
}

// options collects the per-resource customizations the factories thread into
// the adapters they build.
type options struct {
	journalHooks        JournalHooks
	journalOverrides    map[string]filterx.SQLHandler
	journalGQLOverrides map[string]filterx.GraphQLHandler
}

// Option customizes the adapters a factory builds.
type Option func(*options)

// WithJournalHooks installs h on the Journal adapters.
func WithJournalHooks(h JournalHooks) Option {
	return func(o *options) { o.journalHooks = h }
}

// WithJournalListOverride substitutes the generated filter dispatch for one
// Journal filter field (e.g. a derived state computed via subqueries).
func WithJournalListOverride(field string, h filterx.SQLHandler) Option {
	return func(o *options) {
		if o.journalOverrides == nil {
			o.journalOverrides = map[string]filterx.SQLHandler{}
		}
		o.journalOverrides[field] = h
	}
}

// WithJournalGraphQLListOverride substitutes the generated filter dispatch
// for one Journal filter field on the GraphQL adapters.
func WithJournalGraphQLListOverride(field string, h filterx.GraphQLHandler) Option {
	return func(o *options) {
		if o.journalGQLOverrides == nil {
			o.journalGQLOverrides = map[string]filterx.GraphQLHandler{}
		}
		o.journalGQLOverrides[field] = h
	}
}

// New picks the adapter set for the live handle in conn: GraphQL when a
// client connection is present, otherwise GORM.
func New(conn repox.Conn, opts ...Option) Repositories {
	if conn.GraphQL != nil {
		return NewGraphQL(conn.GraphQL, opts...)
	}
	return NewGorm(conn.Gorm, opts...)
}

// NewGraphQL builds the GraphQL adapter set over svc.
func NewGraphQL(svc *freebusyql.Service, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Journals: &GraphQLJournalRepository{Svc: svc, Hooks: o.journalHooks, ListOverrides: o.journalGQLOverrides},
	}
}

// NewGorm builds the GORM adapter set over db.
func NewGorm(db *gorm.DB, opts ...Option) Repositories {
	var o options
	for _, opt := range opts {
		opt(&o)
	}
	return Repositories{
		Journals: &GormJournalRepository{DB: db, Hooks: o.journalHooks, ListOverrides: o.journalOverrides},
	}
}
