// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
// source: freebusy/pricing/v1/pricing.proto
//
// database: freebusy
// schema:   pricing
//
// AIP-160 filter / AIP-132 order_by specs — data for the shared filterx engines.
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package pricing

import (
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
)

// RatePlanFilterSpec is RatePlan's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var RatePlanFilterSpec = filterx.Spec{
	Table: `"pricing"."rate_plans"`,
	Fields: map[string]filterx.FieldSpec{
		"create_time":  {Column: "create_time", Kind: filterx.KindTimestamp},
		"description":  {Column: "description", Kind: filterx.KindText},
		"display_name": {Column: "display_name", Kind: filterx.KindText},
		"etag":         {Column: "etag", Kind: filterx.KindText},
		"name":         {Column: "name", Kind: filterx.KindText},
		"pricing_unit": {Column: "pricing_unit", Kind: filterx.KindEnum, EnumPrefix: "PRICING_UNIT_"},
		"resource":     {Column: "resource", Kind: filterx.KindText},
		"state":        {Column: "state", Kind: filterx.KindEnum, EnumPrefix: "RATE_PLAN_STATE_"},
		"update_time":  {Column: "update_time", Kind: filterx.KindTimestamp},
	},
	Search: []string{"display_name"},
	Sort: map[string]filterx.SortSpec{
		"create_time":  {Column: "create_time", Kind: filterx.KindTimestamp, NotNull: true},
		"description":  {Column: "description", Kind: filterx.KindText},
		"display_name": {Column: "display_name", Kind: filterx.KindText, NotNull: true},
		"etag":         {Column: "etag", Kind: filterx.KindText},
		"name":         {Column: "name", Kind: filterx.KindText, NotNull: true},
		"pricing_unit": {Column: "pricing_unit", Kind: filterx.KindEnum},
		"resource":     {Column: "resource", Kind: filterx.KindText, NotNull: true},
		"state":        {Column: "state", Kind: filterx.KindEnum},
		"update_time":  {Column: "update_time", Kind: filterx.KindTimestamp, NotNull: true},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// LosDiscountFilterSpec is LosDiscount's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var LosDiscountFilterSpec = filterx.Spec{
	Table: `"pricing"."los_discounts"`,
	Fields: map[string]filterx.FieldSpec{
		"min_nights":  {Column: "min_nights", Kind: filterx.KindInt},
		"percent_off": {Column: "percent_off", Kind: filterx.KindInt},
	},
	Sort: map[string]filterx.SortSpec{
		"min_nights":  {Column: "min_nights", Kind: filterx.KindInt, NotNull: true},
		"percent_off": {Column: "percent_off", Kind: filterx.KindInt},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// FeeFilterSpec is Fee's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var FeeFilterSpec = filterx.Spec{
	Table: `"pricing"."fees"`,
	Fields: map[string]filterx.FieldSpec{
		"code":         {Column: "code", Kind: filterx.KindText},
		"display_name": {Column: "display_name", Kind: filterx.KindText},
		"percent":      {Column: "percent", Kind: filterx.KindInt},
		"pricing_unit": {Column: "pricing_unit", Kind: filterx.KindEnum, EnumPrefix: "PRICING_UNIT_"},
		"taxable":      {Column: "taxable", Kind: filterx.KindBool},
	},
	Sort: map[string]filterx.SortSpec{
		"code":         {Column: "code", Kind: filterx.KindText, NotNull: true},
		"display_name": {Column: "display_name", Kind: filterx.KindText},
		"percent":      {Column: "percent", Kind: filterx.KindInt},
		"pricing_unit": {Column: "pricing_unit", Kind: filterx.KindEnum},
		"taxable":      {Column: "taxable", Kind: filterx.KindBool},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// TaxFilterSpec is Tax's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var TaxFilterSpec = filterx.Spec{
	Table: `"pricing"."taxes"`,
	Fields: map[string]filterx.FieldSpec{
		"code":         {Column: "code", Kind: filterx.KindText},
		"display_name": {Column: "display_name", Kind: filterx.KindText},
		"percent":      {Column: "percent", Kind: filterx.KindFloat},
	},
	Sort: map[string]filterx.SortSpec{
		"code":         {Column: "code", Kind: filterx.KindText, NotNull: true},
		"display_name": {Column: "display_name", Kind: filterx.KindText},
		"percent":      {Column: "percent", Kind: filterx.KindFloat, NotNull: true},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// DynamicRuleFilterSpec is DynamicRule's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var DynamicRuleFilterSpec = filterx.Spec{
	Table: `"pricing"."dynamic_rules"`,
	Fields: map[string]filterx.FieldSpec{
		"trigger": {Column: "trigger", Kind: filterx.KindEnum, EnumPrefix: "DYNAMIC_TRIGGER_"},
	},
	Sort: map[string]filterx.SortSpec{
		"trigger": {Column: "trigger", Kind: filterx.KindEnum, NotNull: true},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// DateRangeFilterSpec is DateRange's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var DateRangeFilterSpec = filterx.Spec{
	Table: `"pricing"."date_ranges"`,
	Fields: map[string]filterx.FieldSpec{
		"end_date":   {Column: "end_date", Kind: filterx.KindDate},
		"start_date": {Column: "start_date", Kind: filterx.KindDate},
	},
	Sort: map[string]filterx.SortSpec{
		"end_date":   {Column: "end_date", Kind: filterx.KindDate, NotNull: true},
		"start_date": {Column: "start_date", Kind: filterx.KindDate, NotNull: true},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// DynamicBandFilterSpec is DynamicBand's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var DynamicBandFilterSpec = filterx.Spec{
	Table: `"pricing"."dynamic_bands"`,
	Fields: map[string]filterx.FieldSpec{
		"display_name":  {Column: "display_name", Kind: filterx.KindText},
		"max_threshold": {Column: "max_threshold", Kind: filterx.KindInt},
		"min_threshold": {Column: "min_threshold", Kind: filterx.KindInt},
	},
	Sort: map[string]filterx.SortSpec{
		"display_name":  {Column: "display_name", Kind: filterx.KindText},
		"max_threshold": {Column: "max_threshold", Kind: filterx.KindInt},
		"min_threshold": {Column: "min_threshold", Kind: filterx.KindInt, NotNull: true},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// AdjustmentFilterSpec is Adjustment's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var AdjustmentFilterSpec = filterx.Spec{
	Table: `"pricing"."adjustments"`,
	Fields: map[string]filterx.FieldSpec{
		"percent_delta": {Column: "percent_delta", Kind: filterx.KindInt},
	},
	Sort: map[string]filterx.SortSpec{
		"percent_delta": {Column: "percent_delta", Kind: filterx.KindInt},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}
