// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
// source: freebusy/pricing/v1/pricing.proto
//
// database: freebusy
// schema:   pricing
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package pricing

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// LosDiscountStoreIface is the full data-access surface of LosDiscount: everything
// LosDiscountStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedLosDiscountStore struct {
//		LosDiscountStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewLosDiscountStore returns the concrete
// *LosDiscountStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type LosDiscountStoreIface interface {
	Create(ctx context.Context, m *LosDiscount) error
	List(ctx context.Context, opts gormx.ListOptions) ([]LosDiscount, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *LosDiscount) error
	GetByID(ctx context.Context, id string) (*LosDiscount, error)
	DeleteByID(ctx context.Context, id string) error
	ListByRatePlanID(ctx context.Context, id string, opts gormx.ListOptions) ([]LosDiscount, error)
	ListByAmountOffID(ctx context.Context, id string, opts gormx.ListOptions) ([]LosDiscount, error)
}

// LosDiscountStore provides typed CRUD access to LosDiscount records.
// A discount applied once a stay reaches `min_nights`. Exactly one of `percent_off` or `amount_off` is set.
type LosDiscountStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewLosDiscountStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that LosDiscountStore implements its own interface. Without it a
// signature could drift from LosDiscountStoreIface and only break in whichever downstream
// package decorates it.
var _ LosDiscountStoreIface = (*LosDiscountStore)(nil)

// Compile-time proof that LosDiscountStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[LosDiscount] = (*LosDiscountStore)(nil)

// NewLosDiscountStore returns a LosDiscountStore backed by db.
func NewLosDiscountStore(db *gorm.DB) *LosDiscountStore { return &LosDiscountStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *LosDiscountStore) WithTelemetry(t gormx.Telemetry) *LosDiscountStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *LosDiscountStore) Create(ctx context.Context, m *LosDiscount) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "pricing.LosDiscount/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "pricing.los_discounts", "create", time.Since(start), err)
	return err
}

// List returns the LosDiscount records matching opts.
func (s *LosDiscountStore) List(ctx context.Context, opts gormx.ListOptions) ([]LosDiscount, error) {
	var out []LosDiscount
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "pricing.LosDiscount/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "pricing.los_discounts", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of LosDiscount records matching opts.Where
// (pagination and ordering are ignored).
func (s *LosDiscountStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "pricing.LosDiscount/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&LosDiscount{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "pricing.los_discounts", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *LosDiscountStore) Update(ctx context.Context, m *LosDiscount) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "pricing.LosDiscount/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "pricing.los_discounts", "update", time.Since(start), err)
	return err
}

// GetByID fetches the LosDiscount with the given primary key.
func (s *LosDiscountStore) GetByID(ctx context.Context, id string) (*LosDiscount, error) {
	var m LosDiscount
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "pricing.LosDiscount/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "pricing.los_discounts", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the LosDiscount with the given primary key.
func (s *LosDiscountStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "pricing.LosDiscount/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&LosDiscount{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "pricing.los_discounts", "delete", time.Since(start), err)
	return err
}

// ListByRatePlanID returns the LosDiscount records whose rate_plan_id matches id, with opts applied.
func (s *LosDiscountStore) ListByRatePlanID(ctx context.Context, id string, opts gormx.ListOptions) ([]LosDiscount, error) {
	var out []LosDiscount
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "pricing.LosDiscount/ListByRatePlanID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("rate_plan_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "pricing.los_discounts", "list_by_rate_plan_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListByAmountOffID returns the LosDiscount records whose amount_off_id matches id, with opts applied.
func (s *LosDiscountStore) ListByAmountOffID(ctx context.Context, id string, opts gormx.ListOptions) ([]LosDiscount, error) {
	var out []LosDiscount
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "pricing.LosDiscount/ListByAmountOffID", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx).Where("amount_off_id = ?", id)).Find(&out).Error
	})
	tel.RecordOp(ctx, "pricing.los_discounts", "list_by_amount_off_id", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}
