// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  calendartimesql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package calendartimesql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs JournalCalendarTimes query operations.
type QueryHandler interface {
	// List runs the "journalCalendarTimes" query.
	List(ctx context.Context, req ...*ListRequest) ([]JournalCalendarTimes, error)
	// Find runs the "journalCalendarTimes" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*JournalCalendarTimes, error)
	// Aggregate runs the "journalCalendarTimesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*JournalCalendarTimesAggExp, error)
	// Get runs the "journalCalendarTimesById" query.
	Get(ctx context.Context, id string) (*JournalCalendarTimes, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs JournalCalendarTimes mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteJournalCalendarTimesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (DeleteJournalCalendarTimesByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *DeleteJournalCalendarTimesByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertJournalCalendarTimes" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (InsertJournalCalendarTimesResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *InsertJournalCalendarTimesResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateJournalCalendarTimesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (UpdateJournalCalendarTimesByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (UpdateJournalCalendarTimesByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *UpdateJournalCalendarTimesByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs JournalCalendarTimes subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "journalCalendarTimes" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "journalCalendarTimesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "journalCalendarTimesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[JournalCalendarTimes] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, InsertJournalCalendarTimesResponse, UpdateJournalCalendarTimesByIdResponse, DeleteJournalCalendarTimesByIdResponse] = (*mutationHandler)(nil)
