// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  calendarql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package calendarql

import (
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/calendarql/extensionpropertiesql"
	"github.com/oh-tarnished/freebusy/internal/database/hasura/freebusyql/calendarql/resourceql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// Model type aliases for this domain, re-exported from the owning resource packages.
type CalendarExtensionProperties = extensionpropertiesql.CalendarExtensionProperties
type CalendarExtensionPropertiesAggExp = extensionpropertiesql.CalendarExtensionPropertiesAggExp
type DeleteCalendarExtensionPropertiesByIdResponse = extensionpropertiesql.DeleteCalendarExtensionPropertiesByIdResponse
type InsertCalendarExtensionPropertiesResponse = extensionpropertiesql.InsertCalendarExtensionPropertiesResponse
type UpdateCalendarExtensionPropertiesByIdResponse = extensionpropertiesql.UpdateCalendarExtensionPropertiesByIdResponse
type CalendarResource = resourceql.CalendarResource
type CalendarResourceAggExp = resourceql.CalendarResourceAggExp
type DeleteCalendarResourceByIdResponse = resourceql.DeleteCalendarResourceByIdResponse
type InsertCalendarResourceResponse = resourceql.InsertCalendarResourceResponse
type UpdateCalendarResourceByIdResponse = resourceql.UpdateCalendarResourceByIdResponse

// QueryHandler aggregates query handlers for the calendarql domain.
type QueryHandler struct {
	ExtensionProperties extensionpropertiesql.QueryHandler
	Resource            resourceql.QueryHandler
}

// NewQuery wires every query handler in the domain.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler {
	return QueryHandler{
		ExtensionProperties: extensionpropertiesql.NewQuery(gql),
		Resource:            resourceql.NewQuery(gql),
	}
}

// MutationHandler aggregates mutation handlers for the calendarql domain.
type MutationHandler struct {
	ExtensionProperties extensionpropertiesql.MutationHandler
	Resource            resourceql.MutationHandler
}

// NewMutation wires every mutation handler in the domain.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler {
	return MutationHandler{
		ExtensionProperties: extensionpropertiesql.NewMutation(gql),
		Resource:            resourceql.NewMutation(gql),
	}
}

// SubscriptionHandler aggregates subscription handlers for the calendarql domain.
type SubscriptionHandler struct {
	ExtensionProperties extensionpropertiesql.SubscriptionHandler
	Resource            resourceql.SubscriptionHandler
}

// NewSubscription wires every subscription handler in the domain.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return SubscriptionHandler{
		ExtensionProperties: extensionpropertiesql.NewSubscription(gql),
		Resource:            resourceql.NewSubscription(gql),
	}
}
