// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
// source: freebusy/scheduling/v1/scheduling.proto
//
// database: freebusy
// schema:   scheduling
//
// AIP resource-name codecs for this schema's repositories.
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package scheduling

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
)

// FormatBookingName builds "bookings/{booking}" from bare ids.
func FormatBookingName(booking string) string {
	return "bookings" + "/" + booking
}

// ParseBookingName splits a "bookings/{booking}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseBookingName(name string) (booking string, err error) {
	ids, err := repox.SplitName(name, "bookings")
	if err != nil {
		return
	}
	booking = ids[0]
	return
}
