// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
//
// database: freebusyql
// package:  extensionpropertiesql
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package extensionpropertiesql

import (
	"encoding/json"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one EventExtensionProperties row.
type CreateInput struct {
	// EventId sets the "eventId" column (required).
	EventId string `json:"eventId"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// Key sets the "key" column (required).
	Key string `json:"key"`
	// Parameters sets the "parameters" column; the zero value is omitted (column default / NULL).
	Parameters json.RawMessage `json:"parameters,omitzero"`
	// Values sets the "values" column; the zero value is omitted (column default / NULL).
	Values []*string `json:"values,omitzero"`
}

// UpdateInput holds the fields to change on a EventExtensionProperties row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'event_id' column in the 'event_extension_properties' collection.
	EventId graphql.Nullable[string] `json:"eventId"`
	// Update the 'id' column in the 'event_extension_properties' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'key' column in the 'event_extension_properties' collection.
	Key graphql.Nullable[string] `json:"key"`
	// Update the 'parameters' column in the 'event_extension_properties' collection.
	Parameters graphql.Nullable[json.RawMessage] `json:"parameters"`
	// Update the 'values' column in the 'event_extension_properties' collection.
	Values graphql.Nullable[[]*string] `json:"values"`
}
