// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
//
// database: freebusyql
// package:  extensionpropertiesql
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package extensionpropertiesql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

type queryHandler struct {
	gql *runtime.GraphQLClient
}

func (h *queryHandler) List(ctx context.Context, req ...*ListRequest) ([]EventExtensionProperties, error) {
	var out []EventExtensionProperties
	var r ListRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.GetLimit()) {
		args["limit"] = graphql.VarPtr(r.GetLimit(), "Int")
	}
	if !graphql.IsOmitted(r.GetOffset()) {
		args["offset"] = graphql.VarPtr(r.GetOffset(), "Int")
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		args["order_by"] = graphql.VarPtr(r.GetOrderBy(), "[EventExtensionPropertiesOrderByExp!]")
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		args["where"] = graphql.VarPtr(r.GetWhere(), "EventExtensionPropertiesBoolExp")
	}
	res := <-h.gql.QueryFields(ctx, "eventExtensionProperties", &out, args)
	return out, res.Error
}

func (h *queryHandler) Find(ctx context.Context, req ...*ListRequest) (*EventExtensionProperties, error) {
	var out []EventExtensionProperties
	var r ListRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	if !graphql.IsOmitted(r.GetOffset()) {
		args["offset"] = graphql.VarPtr(r.GetOffset(), "Int")
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		args["order_by"] = graphql.VarPtr(r.GetOrderBy(), "[EventExtensionPropertiesOrderByExp!]")
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		args["where"] = graphql.VarPtr(r.GetWhere(), "EventExtensionPropertiesBoolExp")
	}
	args["limit"] = graphql.VarPtr(1, "Int")
	res := <-h.gql.QueryFields(ctx, "eventExtensionProperties", &out, args)
	if res.Error != nil {
		return nil, res.Error
	}
	if len(out) == 0 {
		return nil, nil
	}
	return &out[0], nil
}

func (h *queryHandler) Aggregate(ctx context.Context, req ...*AggregateRequest) (*EventExtensionPropertiesAggExp, error) {
	var out *EventExtensionPropertiesAggExp
	var r AggregateRequest
	if len(req) > 0 && req[0] != nil {
		r = *req[0]
	}
	args := map[string]any{}
	filterInput := map[string]any{}
	if !graphql.IsOmitted(r.GetLimit()) {
		filterInput["limit"] = r.GetLimit()
	}
	if !graphql.IsOmitted(r.GetOffset()) {
		filterInput["offset"] = r.GetOffset()
	}
	if !graphql.IsOmitted(r.GetOrderBy()) {
		filterInput["order_by"] = r.GetOrderBy()
	}
	if !graphql.IsOmitted(r.GetWhere()) {
		filterInput["where"] = r.GetWhere()
	}
	if len(filterInput) > 0 {
		args["filter_input"] = graphql.VarPtr(filterInput, "EventExtensionPropertiesFilterInput")
	}
	res := <-h.gql.QueryFields(ctx, "eventExtensionPropertiesAggregate", &out, args)
	return out, res.Error
}

func (h *queryHandler) Get(ctx context.Context, id string) (*EventExtensionProperties, error) {
	var out *EventExtensionProperties
	args := map[string]any{}
	args["id"] = graphql.Var(id, "String1")
	res := <-h.gql.QueryFields(ctx, "eventExtensionPropertiesById", &out, args)
	return out, res.Error
}
