// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.1
// 	protoc (unknown)
//
// database: freebusyql
// package:  adjustmentsql
//
// annotations: entity.v1 v1.5.1, store.v1 v1.5.1
// engine:      protokit v1.2.1
//
// store — https://github.com/the-protobuf-project/store

package adjustmentsql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs PricingAdjustments query operations.
type QueryHandler interface {
	// List runs the "pricingAdjustments" query.
	List(ctx context.Context, req ...*ListRequest) ([]PricingAdjustments, error)
	// Find runs the "pricingAdjustments" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*PricingAdjustments, error)
	// Aggregate runs the "pricingAdjustmentsAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*PricingAdjustmentsAggExp, error)
	// Get runs the "pricingAdjustmentsById" query.
	Get(ctx context.Context, id string) (*PricingAdjustments, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs PricingAdjustments mutation operations.
type MutationHandler interface {
	// Delete runs the "deletePricingAdjustmentsById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (DeletePricingAdjustmentsByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *DeletePricingAdjustmentsByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertPricingAdjustments" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (InsertPricingAdjustmentsResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *InsertPricingAdjustmentsResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updatePricingAdjustmentsById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (UpdatePricingAdjustmentsByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (UpdatePricingAdjustmentsByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *UpdatePricingAdjustmentsByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs PricingAdjustments subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "pricingAdjustments" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "pricingAdjustmentsAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "pricingAdjustmentsById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[PricingAdjustments] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, InsertPricingAdjustmentsResponse, UpdatePricingAdjustmentsByIdResponse, DeletePricingAdjustmentsByIdResponse] = (*mutationHandler)(nil)
