// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  adjustmentsql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package adjustmentsql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PricingAdjustments row.
type CreateInput struct {
	// AmountDeltaId sets the "amountDeltaId" column; the zero value is omitted (column default / NULL).
	AmountDeltaId string `json:"amountDeltaId,omitzero"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// PercentDelta sets the "percentDelta" column; the zero value is omitted (column default / NULL).
	PercentDelta int32 `json:"percentDelta,omitzero"`
}

// UpdateInput holds the fields to change on a PricingAdjustments row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'amount_delta_id' column in the 'pricing_adjustments' collection.
	AmountDeltaId graphql.Nullable[string] `json:"amountDeltaId"`
	// Update the 'id' column in the 'pricing_adjustments' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'percent_delta' column in the 'pricing_adjustments' collection.
	PercentDelta graphql.Nullable[int32] `json:"percentDelta"`
}
