// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
//
// database: freebusyql
// package:  cancellationpoliciesql
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package cancellationpoliciesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one ScheduleCancellationPolicies row.
type CreateInput struct {
	// Id sets the "id" column (required).
	Id string `json:"id"`
}

// UpdateInput holds the fields to change on a ScheduleCancellationPolicies row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'id' column in the 'schedule_cancellation_policies' collection.
	Id graphql.Nullable[string] `json:"id"`
}
