// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  occupanciesql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package occupanciesql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs SchedulingOccupancies query operations.
type QueryHandler interface {
	// List runs the "schedulingOccupancies" query.
	List(ctx context.Context, req ...*ListRequest) ([]SchedulingOccupancies, error)
	// Find runs the "schedulingOccupancies" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*SchedulingOccupancies, error)
	// Aggregate runs the "schedulingOccupanciesAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*SchedulingOccupanciesAggExp, error)
	// Get runs the "schedulingOccupanciesById" query.
	Get(ctx context.Context, id string) (*SchedulingOccupancies, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs SchedulingOccupancies mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteSchedulingOccupanciesById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (DeleteSchedulingOccupanciesByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *DeleteSchedulingOccupanciesByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertSchedulingOccupancies" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (InsertSchedulingOccupanciesResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *InsertSchedulingOccupanciesResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateSchedulingOccupanciesById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (UpdateSchedulingOccupanciesByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (UpdateSchedulingOccupanciesByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *UpdateSchedulingOccupanciesByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs SchedulingOccupancies subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "schedulingOccupancies" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "schedulingOccupanciesAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "schedulingOccupanciesById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[SchedulingOccupancies] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, InsertSchedulingOccupanciesResponse, UpdateSchedulingOccupanciesByIdResponse, DeleteSchedulingOccupanciesByIdResponse] = (*mutationHandler)(nil)
