// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
// source: protobuf/rfc5545/event/v1/alarm.proto, protobuf/rfc5545/event/v1/event.proto, protobuf/rfc5545/event/v1/links.proto, protobuf/rfc5545/event/v1/participant.proto, protobuf/rfc5545/event/v1/publishing.proto, protobuf/rfc5545/event/v1/publishing_types.proto, protobuf/rfc5545/event/v1/recurrence.proto, protobuf/rfc5545/event/v1/recurrence_parts.proto, protobuf/rfc5545/event/v1/types.proto
//
// database: rfc
// schema:   event
//
// Field-mask merge functions shared by every adapter of this schema.
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package event

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
	"github.com/oh-tarnished/freebusy/protobuf/generated/go/protobuf/rfc5545/event/v1/eventpbv1"
)

// applyEventMask merges the masked fields of in onto merged. An empty
// mask replaces every mutable field; identity, parentage, timestamps, and etag
// are repository-managed and never masked. Message-typed fields are replaced
// wholesale when the mask touches them or any of their subpaths.
func applyEventMask(merged, in *eventpbv1.Event, paths []string) {
	if repox.InMask(paths, "name") {
		merged.Name = in.GetName()
	}
	if repox.InMask(paths, "ical_uid") {
		merged.IcalUid = in.GetIcalUid()
	}
	if repox.InMask(paths, "summary") {
		merged.Summary = in.GetSummary()
	}
	if repox.InMask(paths, "description") {
		merged.Description = in.GetDescription()
	}
	if repox.InMask(paths, "location") {
		merged.Location = in.GetLocation()
	}
	if repox.GroupTouched(paths, "duration") {
		merged.Duration = in.GetDuration()
	}
	if repox.InMask(paths, "confirmation") {
		merged.Confirmation = in.GetConfirmation()
	}
	if repox.InMask(paths, "classification") {
		merged.Classification = in.GetClassification()
	}
	if repox.InMask(paths, "transparency") {
		merged.Transparency = in.GetTransparency()
	}
	if repox.InMask(paths, "sequence") {
		merged.Sequence = in.GetSequence()
	}
	if repox.GroupTouched(paths, "position") {
		merged.Position = in.GetPosition()
	}
	if repox.InMask(paths, "concepts") {
		merged.Concepts = in.GetConcepts()
	}
	if repox.InMask(paths, "refids") {
		merged.Refids = in.GetRefids()
	}
	if repox.GroupTouched(paths, "organizer") {
		merged.Organizer = in.GetOrganizer()
	}
}
