// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
// source: protobuf/rfc4519/group/v1/ldap_group.proto, protobuf/rfc7643/group/v1/group.proto
//
// database: rfc
// schema:   group
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
// runtime:     gorm.io/gorm
//
// store — https://github.com/the-protobuf-project/store

package group

import (
	"context"
	"time"

	"github.com/oh-tarnished/freebusy/internal/database/gorm/gormx"
	"gorm.io/gorm"
)

// LdapGroupStoreIface is the full data-access surface of LdapGroup: everything
// LdapGroupStore does, as an interface.
//
// It exists so a decorator — caching, tracing, retries, a test double — can be
// written in its own package against this contract, without that package needing
// to edit anything in this tree. Embed it, override the methods you care about,
// and delegate the rest:
//
//	type cachedLdapGroupStore struct {
//		LdapGroupStoreIface
//		cache Cache
//	}
//
// Construction is deliberately absent. NewLdapGroupStore returns the concrete
// *LdapGroupStore, and WithTelemetry is a chainable setter that also returns it, so
// a caller keeps the full type at the point of wiring and narrows to this
// interface at the point of use — which is the direction that stays useful when
// a decorator is added later.
type LdapGroupStoreIface interface {
	Create(ctx context.Context, m *LdapGroup) error
	List(ctx context.Context, opts gormx.ListOptions) ([]LdapGroup, error)
	Count(ctx context.Context, opts gormx.ListOptions) (int64, error)
	Update(ctx context.Context, m *LdapGroup) error
	GetByID(ctx context.Context, id string) (*LdapGroup, error)
	DeleteByID(ctx context.Context, id string) error
	GetByName(ctx context.Context, v string) (*LdapGroup, error)
	GetByUID(ctx context.Context, v string) (*LdapGroup, error)
}

// LdapGroupStore provides typed CRUD access to LdapGroup records.
// LdapGroup is the LDAP 'groupOfNames' object class, RFC 4519 section 3.5 <https://www.rfc-editor.org/rfc/rfc4519.html#section-3.5>. Section 3.5 makes 'member' a mandatory multi-valued attribute of the group itself. This model deliberately does not: membership is Membership, a resource of its own. A repeated string of DNs cannot carry a role, cannot be created or revoked independently, and cannot be listed with a page token. Externalising it is the difference between a group that records who is in it and one that can answer why. A consequence: 'member' is mandatory in the RFC and absent here, so a LdapGroup with no Membership is representable in this API and is not a valid groupOfNames entry. The rule for an exporter: refuse, not synthesise. Section 3.5 gives no value that could stand in for an absent member -- inventing one (the group's own DN, an owner, a sentinel) asserts a membership nothing in this model states, which misleads every LDAP consumer of the export more than an explicit error would. An exporter targeting LDAP MUST reject a LdapGroup with zero Memberships rather than emit an invalid or fabricated entry. Reference: RFC 4519 "LDAP: Schema for User Applications", section 3.5. https://www.rfc-editor.org/rfc/rfc4519.html#section-3.5
type LdapGroupStore struct {
	DB *gorm.DB
	// Telemetry observes every operation; nil is a no-op. Wire the generated
	// adapter: NewLdapGroupStore(db).WithTelemetry(telemetry.New(o)).
	Telemetry gormx.Telemetry
}

// Compile-time proof that LdapGroupStore implements its own interface. Without it a
// signature could drift from LdapGroupStoreIface and only break in whichever downstream
// package decorates it.
var _ LdapGroupStoreIface = (*LdapGroupStore)(nil)

// Compile-time proof that LdapGroupStore satisfies the generic gormx.Store, so the
// generic engine can drive it alongside the typed finders below.
var _ gormx.Store[LdapGroup] = (*LdapGroupStore)(nil)

// NewLdapGroupStore returns a LdapGroupStore backed by db.
func NewLdapGroupStore(db *gorm.DB) *LdapGroupStore { return &LdapGroupStore{DB: db} }

// WithTelemetry sets the store's Telemetry and returns the store for chaining.
func (s *LdapGroupStore) WithTelemetry(t gormx.Telemetry) *LdapGroupStore {
	s.Telemetry = t
	return s
}

// Create inserts m.
func (s *LdapGroupStore) Create(ctx context.Context, m *LdapGroup) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "group.LdapGroup/Create", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Create(m).Error
	})
	tel.RecordOp(ctx, "group.ldap_groups", "create", time.Since(start), err)
	return err
}

// List returns the LdapGroup records matching opts.
func (s *LdapGroupStore) List(ctx context.Context, opts gormx.ListOptions) ([]LdapGroup, error) {
	var out []LdapGroup
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "group.LdapGroup/List", nil, func(ctx context.Context) error {
		return opts.Apply(s.DB.WithContext(ctx)).Find(&out).Error
	})
	tel.RecordOp(ctx, "group.ldap_groups", "list", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Count returns the number of LdapGroup records matching opts.Where
// (pagination and ordering are ignored).
func (s *LdapGroupStore) Count(ctx context.Context, opts gormx.ListOptions) (int64, error) {
	var n int64
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "group.LdapGroup/Count", nil, func(ctx context.Context) error {
		db := s.DB.WithContext(ctx).Model(&LdapGroup{})
		if opts.Where != nil {
			db = db.Where(opts.Where, opts.Args...)
		}
		return db.Count(&n).Error
	})
	tel.RecordOp(ctx, "group.ldap_groups", "count", time.Since(start), err)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// Update persists every field of m, which must carry its primary key.
func (s *LdapGroupStore) Update(ctx context.Context, m *LdapGroup) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "group.LdapGroup/Update", m, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Save(m).Error
	})
	tel.RecordOp(ctx, "group.ldap_groups", "update", time.Since(start), err)
	return err
}

// GetByID fetches the LdapGroup with the given primary key.
func (s *LdapGroupStore) GetByID(ctx context.Context, id string) (*LdapGroup, error) {
	var m LdapGroup
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "group.LdapGroup/GetByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "group.ldap_groups", "get", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// DeleteByID removes the LdapGroup with the given primary key.
func (s *LdapGroupStore) DeleteByID(ctx context.Context, id string) error {
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "group.LdapGroup/DeleteByID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).Delete(&LdapGroup{}, "id = ?", id).Error
	})
	tel.RecordOp(ctx, "group.ldap_groups", "delete", time.Since(start), err)
	return err
}

// GetByName fetches the LdapGroup with the given name (a unique column).
func (s *LdapGroupStore) GetByName(ctx context.Context, v string) (*LdapGroup, error) {
	var m LdapGroup
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "group.LdapGroup/GetByName", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "name = ?", v).Error
	})
	tel.RecordOp(ctx, "group.ldap_groups", "get_by_name", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}

// GetByUID fetches the LdapGroup with the given uid (a unique column).
func (s *LdapGroupStore) GetByUID(ctx context.Context, v string) (*LdapGroup, error) {
	var m LdapGroup
	tel := gormx.OrNop(s.Telemetry)
	start := time.Now()
	err := tel.Span(ctx, "group.LdapGroup/GetByUID", nil, func(ctx context.Context) error {
		return s.DB.WithContext(ctx).First(&m, "uid = ?", v).Error
	})
	tel.RecordOp(ctx, "group.ldap_groups", "get_by_uid", time.Since(start), err)
	if err != nil {
		return nil, err
	}
	return &m, nil
}
