// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
//
// database: freebusyql
// package:  bookingsql
//
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package bookingsql

import (
	"context"
	"github.com/the-protobuf-project/runtime-go/network/graphql"
	"github.com/the-protobuf-project/runtime-go/network/runtime"
)

// QueryHandler runs SchedulingBookings query operations.
type QueryHandler interface {
	// List runs the "schedulingBookings" query.
	List(ctx context.Context, req ...*ListRequest) ([]SchedulingBookings, error)
	// Find runs the "schedulingBookings" query and returns the first match, or nil if none.
	Find(ctx context.Context, req ...*ListRequest) (*SchedulingBookings, error)
	// Aggregate runs the "schedulingBookingsAggregate" query.
	Aggregate(ctx context.Context, req ...*AggregateRequest) (*SchedulingBookingsAggExp, error)
	// Get runs the "schedulingBookingsById" query.
	Get(ctx context.Context, id string) (*SchedulingBookings, error)
}

// NewQuery returns a QueryHandler bound to gql.
func NewQuery(gql *runtime.GraphQLClient) QueryHandler { return &queryHandler{gql: gql} }

// MutationHandler runs SchedulingBookings mutation operations.
type MutationHandler interface {
	// Delete runs the "deleteSchedulingBookingsById" mutation.
	Delete(ctx context.Context, keyId string, req ...*DeleteRequest) (DeleteSchedulingBookingsByIdResponse, error)
	// DeleteOp returns Delete as a deferred mutation for atomic batching via a Tx.
	DeleteOp(keyId string, result *DeleteSchedulingBookingsByIdResponse, req ...*DeleteRequest) runtime.BatchOp
	// Create runs the "insertSchedulingBookings" mutation.
	Create(ctx context.Context, obj CreateInput, req ...*CreateRequest) (InsertSchedulingBookingsResponse, error)
	// CreateOp returns Create as a deferred mutation for atomic batching via a Tx.
	CreateOp(obj CreateInput, result *InsertSchedulingBookingsResponse, req ...*CreateRequest) runtime.BatchOp
	// Update runs the "updateSchedulingBookingsById" mutation.
	Update(ctx context.Context, keyId string, patch UpdateInput, req ...*UpdateRequest) (UpdateSchedulingBookingsByIdResponse, error)
	// UpdateIfMatch runs Update guarded by an optimistic-concurrency precondition (e.g.
	// Etag.Eq(prev)), returning graphql.ErrConflict when no row matched.
	UpdateIfMatch(ctx context.Context, keyId string, patch UpdateInput, match graphql.Predicate) (UpdateSchedulingBookingsByIdResponse, error)
	// UpdateOp returns Update as a deferred mutation for atomic batching via a Tx.
	UpdateOp(keyId string, patch UpdateInput, result *UpdateSchedulingBookingsByIdResponse, req ...*UpdateRequest) runtime.BatchOp
}

// NewMutation returns a MutationHandler bound to gql.
func NewMutation(gql *runtime.GraphQLClient) MutationHandler { return &mutationHandler{gql: gql} }

// SubscriptionHandler runs SchedulingBookings subscription operations.
type SubscriptionHandler interface {
	// OnList runs the "schedulingBookings" subscription.
	OnList(ctx context.Context, req ...*OnListRequest) (*runtime.Subscription, error)
	// OnAggregate runs the "schedulingBookingsAggregate" subscription.
	OnAggregate(ctx context.Context, req ...*OnAggregateRequest) (*runtime.Subscription, error)
	// OnGet runs the "schedulingBookingsById" subscription.
	OnGet(ctx context.Context, id string) (*runtime.Subscription, error)
}

// NewSubscription returns a SubscriptionHandler bound to gql.
func NewSubscription(gql *runtime.GraphQLClient) SubscriptionHandler {
	return &subscriptionHandler{gql: gql}
}

// Compile-time proof the query handler satisfies the generic graphql.QueryHandler.
var _ graphql.QueryHandler[SchedulingBookings] = (*queryHandler)(nil)

// Compile-time proof the mutation handler satisfies the generic graphql.MutationHandler.
var _ graphql.MutationHandler[CreateInput, UpdateInput, InsertSchedulingBookingsResponse, UpdateSchedulingBookingsByIdResponse, DeleteSchedulingBookingsByIdResponse] = (*mutationHandler)(nil)
