// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.3
// 	protoc (unknown)
//
// database: freebusyql
// package:  addressql
//
// annotations: entity.v1 1.5.3, store.v1 1.5.3
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package addressql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteVcardAddressByIdResponse — Responses from the 'delete_vcard_address_by_id' procedure
type DeleteVcardAddressByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Apartments selects the "apartments" field.
		Apartments []*string `graphql:"apartments"`
		// Blocks selects the "blocks" field.
		Blocks []*string `graphql:"blocks"`
		// Buildings selects the "buildings" field.
		Buildings []*string `graphql:"buildings"`
		// ContactId selects the "contactId" field.
		ContactId string `graphql:"contactId"`
		// Countries selects the "countries" field.
		Countries []*string `graphql:"countries"`
		// Directions selects the "directions" field.
		Directions []*string `graphql:"directions"`
		// Districts selects the "districts" field.
		Districts []*string `graphql:"districts"`
		// ExtendedAddresses selects the "extendedAddresses" field.
		ExtendedAddresses []*string `graphql:"extendedAddresses"`
		// Floors selects the "floors" field.
		Floors []*string `graphql:"floors"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Label selects the "label" field; nil when the column is NULL.
		Label *string `graphql:"label"`
		// Landmarks selects the "landmarks" field.
		Landmarks []*string `graphql:"landmarks"`
		// Localities selects the "localities" field.
		Localities []*string `graphql:"localities"`
		// Phonetic selects the "phonetic" field; nil when the column is NULL.
		Phonetic *string `graphql:"phonetic"`
		// PostOfficeBox selects the "postOfficeBox" field.
		PostOfficeBox []*string `graphql:"postOfficeBox"`
		// PostalCodes selects the "postalCodes" field.
		PostalCodes []*string `graphql:"postalCodes"`
		// Pref selects the "pref" field; nil when the column is NULL.
		Pref *int32 `graphql:"pref"`
		// Regions selects the "regions" field.
		Regions []*string `graphql:"regions"`
		// Rooms selects the "rooms" field.
		Rooms []*string `graphql:"rooms"`
		// Script selects the "script" field; nil when the column is NULL.
		Script *string `graphql:"script"`
		// StreetAddresses selects the "streetAddresses" field.
		StreetAddresses []*string `graphql:"streetAddresses"`
		// StreetNumbers selects the "streetNumbers" field.
		StreetNumbers []*string `graphql:"streetNumbers"`
		// Streets selects the "streets" field.
		Streets []*string `graphql:"streets"`
		// Subdistricts selects the "subdistricts" field.
		Subdistricts []*string `graphql:"subdistricts"`
		// Types selects the "types" field; nil when the column is NULL.
		Types *string `graphql:"types"`
	} `graphql:"returning"`
}

// InsertVcardAddressResponse — Responses from the 'insert_vcard_address' procedure
type InsertVcardAddressResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Apartments selects the "apartments" field.
		Apartments []*string `graphql:"apartments"`
		// Blocks selects the "blocks" field.
		Blocks []*string `graphql:"blocks"`
		// Buildings selects the "buildings" field.
		Buildings []*string `graphql:"buildings"`
		// ContactId selects the "contactId" field.
		ContactId string `graphql:"contactId"`
		// Countries selects the "countries" field.
		Countries []*string `graphql:"countries"`
		// Directions selects the "directions" field.
		Directions []*string `graphql:"directions"`
		// Districts selects the "districts" field.
		Districts []*string `graphql:"districts"`
		// ExtendedAddresses selects the "extendedAddresses" field.
		ExtendedAddresses []*string `graphql:"extendedAddresses"`
		// Floors selects the "floors" field.
		Floors []*string `graphql:"floors"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Label selects the "label" field; nil when the column is NULL.
		Label *string `graphql:"label"`
		// Landmarks selects the "landmarks" field.
		Landmarks []*string `graphql:"landmarks"`
		// Localities selects the "localities" field.
		Localities []*string `graphql:"localities"`
		// Phonetic selects the "phonetic" field; nil when the column is NULL.
		Phonetic *string `graphql:"phonetic"`
		// PostOfficeBox selects the "postOfficeBox" field.
		PostOfficeBox []*string `graphql:"postOfficeBox"`
		// PostalCodes selects the "postalCodes" field.
		PostalCodes []*string `graphql:"postalCodes"`
		// Pref selects the "pref" field; nil when the column is NULL.
		Pref *int32 `graphql:"pref"`
		// Regions selects the "regions" field.
		Regions []*string `graphql:"regions"`
		// Rooms selects the "rooms" field.
		Rooms []*string `graphql:"rooms"`
		// Script selects the "script" field; nil when the column is NULL.
		Script *string `graphql:"script"`
		// StreetAddresses selects the "streetAddresses" field.
		StreetAddresses []*string `graphql:"streetAddresses"`
		// StreetNumbers selects the "streetNumbers" field.
		StreetNumbers []*string `graphql:"streetNumbers"`
		// Streets selects the "streets" field.
		Streets []*string `graphql:"streets"`
		// Subdistricts selects the "subdistricts" field.
		Subdistricts []*string `graphql:"subdistricts"`
		// Types selects the "types" field; nil when the column is NULL.
		Types *string `graphql:"types"`
	} `graphql:"returning"`
}

// UpdateVcardAddressByIdResponse — Responses from the 'update_vcard_address_by_id' procedure
type UpdateVcardAddressByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// Apartments selects the "apartments" field.
		Apartments []*string `graphql:"apartments"`
		// Blocks selects the "blocks" field.
		Blocks []*string `graphql:"blocks"`
		// Buildings selects the "buildings" field.
		Buildings []*string `graphql:"buildings"`
		// ContactId selects the "contactId" field.
		ContactId string `graphql:"contactId"`
		// Countries selects the "countries" field.
		Countries []*string `graphql:"countries"`
		// Directions selects the "directions" field.
		Directions []*string `graphql:"directions"`
		// Districts selects the "districts" field.
		Districts []*string `graphql:"districts"`
		// ExtendedAddresses selects the "extendedAddresses" field.
		ExtendedAddresses []*string `graphql:"extendedAddresses"`
		// Floors selects the "floors" field.
		Floors []*string `graphql:"floors"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// Label selects the "label" field; nil when the column is NULL.
		Label *string `graphql:"label"`
		// Landmarks selects the "landmarks" field.
		Landmarks []*string `graphql:"landmarks"`
		// Localities selects the "localities" field.
		Localities []*string `graphql:"localities"`
		// Phonetic selects the "phonetic" field; nil when the column is NULL.
		Phonetic *string `graphql:"phonetic"`
		// PostOfficeBox selects the "postOfficeBox" field.
		PostOfficeBox []*string `graphql:"postOfficeBox"`
		// PostalCodes selects the "postalCodes" field.
		PostalCodes []*string `graphql:"postalCodes"`
		// Pref selects the "pref" field; nil when the column is NULL.
		Pref *int32 `graphql:"pref"`
		// Regions selects the "regions" field.
		Regions []*string `graphql:"regions"`
		// Rooms selects the "rooms" field.
		Rooms []*string `graphql:"rooms"`
		// Script selects the "script" field; nil when the column is NULL.
		Script *string `graphql:"script"`
		// StreetAddresses selects the "streetAddresses" field.
		StreetAddresses []*string `graphql:"streetAddresses"`
		// StreetNumbers selects the "streetNumbers" field.
		StreetNumbers []*string `graphql:"streetNumbers"`
		// Streets selects the "streets" field.
		Streets []*string `graphql:"streets"`
		// Subdistricts selects the "subdistricts" field.
		Subdistricts []*string `graphql:"subdistricts"`
		// Types selects the "types" field; nil when the column is NULL.
		Types *string `graphql:"types"`
	} `graphql:"returning"`
}

// VcardAddress is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type VcardAddress struct {
	// Apartments selects the "apartments" field.
	Apartments []*string `graphql:"apartments"`
	// Blocks selects the "blocks" field.
	Blocks []*string `graphql:"blocks"`
	// Buildings selects the "buildings" field.
	Buildings []*string `graphql:"buildings"`
	// ContactId selects the "contactId" field.
	ContactId string `graphql:"contactId"`
	// Countries selects the "countries" field.
	Countries []*string `graphql:"countries"`
	// Directions selects the "directions" field.
	Directions []*string `graphql:"directions"`
	// Districts selects the "districts" field.
	Districts []*string `graphql:"districts"`
	// ExtendedAddresses selects the "extendedAddresses" field.
	ExtendedAddresses []*string `graphql:"extendedAddresses"`
	// Floors selects the "floors" field.
	Floors []*string `graphql:"floors"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// Label selects the "label" field; nil when the column is NULL.
	Label *string `graphql:"label"`
	// Landmarks selects the "landmarks" field.
	Landmarks []*string `graphql:"landmarks"`
	// Localities selects the "localities" field.
	Localities []*string `graphql:"localities"`
	// Phonetic selects the "phonetic" field; nil when the column is NULL.
	Phonetic *string `graphql:"phonetic"`
	// PostOfficeBox selects the "postOfficeBox" field.
	PostOfficeBox []*string `graphql:"postOfficeBox"`
	// PostalCodes selects the "postalCodes" field.
	PostalCodes []*string `graphql:"postalCodes"`
	// Pref selects the "pref" field; nil when the column is NULL.
	Pref *int32 `graphql:"pref"`
	// Regions selects the "regions" field.
	Regions []*string `graphql:"regions"`
	// Rooms selects the "rooms" field.
	Rooms []*string `graphql:"rooms"`
	// Script selects the "script" field; nil when the column is NULL.
	Script *string `graphql:"script"`
	// StreetAddresses selects the "streetAddresses" field.
	StreetAddresses []*string `graphql:"streetAddresses"`
	// StreetNumbers selects the "streetNumbers" field.
	StreetNumbers []*string `graphql:"streetNumbers"`
	// Streets selects the "streets" field.
	Streets []*string `graphql:"streets"`
	// Subdistricts selects the "subdistricts" field.
	Subdistricts []*string `graphql:"subdistricts"`
	// Types selects the "types" field; nil when the column is NULL.
	Types *string `graphql:"types"`
}

// VcardAddressAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type VcardAddressAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// ContactId selects the "contactId" field.
	ContactId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"contactId"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// Label selects the "label" field.
	Label struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"label"`
	// Phonetic selects the "phonetic" field.
	Phonetic struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"phonetic"`
	// Pref selects the "pref" field.
	Pref struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Avg selects the "avg" field; nil when the column is NULL.
		Avg *graphql.Bigdecimal `graphql:"avg"`
		// BitAnd selects the "bit_and" field; nil when the column is NULL.
		BitAnd *int32 `graphql:"bit_and"`
		// BitOr selects the "bit_or" field; nil when the column is NULL.
		BitOr *int32 `graphql:"bit_or"`
		// BitXor selects the "bit_xor" field; nil when the column is NULL.
		BitXor *int32 `graphql:"bit_xor"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *int32 `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *int32 `graphql:"min"`
		// Stddev selects the "stddev" field; nil when the column is NULL.
		Stddev *graphql.Bigdecimal `graphql:"stddev"`
		// StddevPop selects the "stddev_pop" field; nil when the column is NULL.
		StddevPop *graphql.Bigdecimal `graphql:"stddev_pop"`
		// StddevSamp selects the "stddev_samp" field; nil when the column is NULL.
		StddevSamp *graphql.Bigdecimal `graphql:"stddev_samp"`
		// Sum selects the "sum" field; nil when the column is NULL.
		Sum *graphql.Int64 `graphql:"sum"`
		// VarPop selects the "var_pop" field; nil when the column is NULL.
		VarPop *graphql.Bigdecimal `graphql:"var_pop"`
		// VarSamp selects the "var_samp" field; nil when the column is NULL.
		VarSamp *graphql.Bigdecimal `graphql:"var_samp"`
		// Variance selects the "variance" field; nil when the column is NULL.
		Variance *graphql.Bigdecimal `graphql:"variance"`
	} `graphql:"pref"`
	// Script selects the "script" field.
	Script struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"script"`
	// Types selects the "types" field.
	Types struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"types"`
}
