// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  daterangesql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package daterangesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// CreateInput holds the settable fields for creating one PricingDateRanges row.
type CreateInput struct {
	// EndDate sets the "endDate" column (required).
	EndDate string `json:"endDate"`
	// Id sets the "id" column (required).
	Id string `json:"id"`
	// StartDate sets the "startDate" column (required).
	StartDate string `json:"startDate"`
}

// UpdateInput holds the fields to change on a PricingDateRanges row; each set field becomes a column update.
type UpdateInput struct {
	// Update the 'end_date' column in the 'pricing_date_ranges' collection.
	EndDate graphql.Nullable[string] `json:"endDate"`
	// Update the 'id' column in the 'pricing_date_ranges' collection.
	Id graphql.Nullable[string] `json:"id"`
	// Update the 'start_date' column in the 'pricing_date_ranges' collection.
	StartDate graphql.Nullable[string] `json:"startDate"`
}
