// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: protobuf/shared/project/v1/project.proto
//
// database: rfc
// schema:   project
//
// AIP resource-name codecs for this schema's repositories.
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package project

import (
	"github.com/oh-tarnished/freebusy/internal/database/rfcrepo/repox"
)

// FormatProjectName builds "projects/{project}" from bare ids.
func FormatProjectName(project string) string {
	return "projects" + "/" + project
}

// ParseProjectName splits a "projects/{project}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseProjectName(name string) (project string, err error) {
	ids, err := repox.SplitName(name, "projects")
	if err != nil {
		return
	}
	project = ids[0]
	return
}
