// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store 1.5.4
// 	protoc (unknown)
// source: protobuf/rfc9073/resource/v1/resource.proto, protobuf/rfc9073/resource/v1/types.proto
//
// database: rfc
// schema:   resource
//
// AIP-160 filter / AIP-132 order_by specs — data for the shared filterx engines.
// annotations: entity.v1 1.5.4, store.v1 1.5.4
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package resource

import (
	"github.com/oh-tarnished/freebusy/internal/database/gorm/filterx"
)

// ResourceFilterSpec is Resource's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var ResourceFilterSpec = filterx.Spec{
	Table: `"resource"."entity"`,
	Fields: map[string]filterx.FieldSpec{
		"calendar":            {Column: "calendar", Kind: filterx.KindRef},
		"create_time":         {Column: "create_time", Kind: filterx.KindTimestamp},
		"delete_time":         {Column: "delete_time", Kind: filterx.KindTimestamp},
		"description":         {Column: "description", Kind: filterx.KindText},
		"display_name":        {Column: "display_name", Kind: filterx.KindText},
		"etag":                {Column: "etag", Kind: filterx.KindText},
		"expire_time":         {Column: "expire_time", Kind: filterx.KindTimestamp},
		"ical_uid":            {Column: "ical_uid", Kind: filterx.KindText},
		"name":                {Column: "name", Kind: filterx.KindText},
		"organizational_unit": {Column: "organizational_unit", Kind: filterx.KindRef},
		"resource_types":      {Column: "resource_types", Kind: filterx.KindTags},
		"uid":                 {Column: "uid", Kind: filterx.KindText},
		"update_time":         {Column: "update_time", Kind: filterx.KindTimestamp},
	},
	Sort: map[string]filterx.SortSpec{
		"create_time":  {Column: "create_time", Kind: filterx.KindTimestamp, NotNull: true},
		"delete_time":  {Column: "delete_time", Kind: filterx.KindTimestamp},
		"description":  {Column: "description", Kind: filterx.KindText},
		"display_name": {Column: "display_name", Kind: filterx.KindText},
		"etag":         {Column: "etag", Kind: filterx.KindText},
		"expire_time":  {Column: "expire_time", Kind: filterx.KindTimestamp},
		"ical_uid":     {Column: "ical_uid", Kind: filterx.KindText},
		"name":         {Column: "name", Kind: filterx.KindText, NotNull: true},
		"uid":          {Column: "uid", Kind: filterx.KindText},
		"update_time":  {Column: "update_time", Kind: filterx.KindTimestamp, NotNull: true},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}

// StructuredDataFilterSpec is StructuredData's AIP-160 filter / AIP-132 order_by surface,
// consumed by the filterx.Gorm and filterx.Hasura engines.
var StructuredDataFilterSpec = filterx.Spec{
	Table: `"resource"."structured_datas"`,
	Fields: map[string]filterx.FieldSpec{
		"format_type": {Column: "format_type", Kind: filterx.KindText},
		"schema":      {Column: "schema", Kind: filterx.KindText},
		"text":        {Column: "text", Kind: filterx.KindText},
		"uri":         {Column: "uri", Kind: filterx.KindText},
	},
	Sort: map[string]filterx.SortSpec{
		"format_type": {Column: "format_type", Kind: filterx.KindText},
		"schema":      {Column: "schema", Kind: filterx.KindText},
		"text":        {Column: "text", Kind: filterx.KindText},
		"uri":         {Column: "uri", Kind: filterx.KindText},
	},
	PK: []filterx.SortSpec{{Column: "id", Kind: filterx.KindText, NotNull: true}},
}
