// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
// source: freebusy/property/v1/property.proto
//
// database: freebusy
// schema:   property
//
// AIP resource-name codecs for this schema's repositories.
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package property

import (
	"github.com/oh-tarnished/freebusy/internal/database/repository/repox"
)

// FormatLicenceName builds "organizationalUnits/{organizational_unit}/licences/{licence}" from bare ids.
func FormatLicenceName(organizationalUnit, licence string) string {
	return "organizationalUnits" + "/" + organizationalUnit + "/" + "licences" + "/" + licence
}

// ParseLicenceName splits a "organizationalUnits/{organizational_unit}/licences/{licence}" resource name into its bare ids,
// rejecting other shapes with repox.ErrInvalidArgument.
func ParseLicenceName(name string) (organizationalUnit, licence string, err error) {
	ids, err := repox.SplitName(name, "organizationalUnits", "licences")
	if err != nil {
		return
	}
	organizationalUnit = ids[0]
	licence = ids[1]
	return
}
