// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  syncstatusesql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package syncstatusesql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// Filter fields for ChannelSyncStatuses. Build predicates like FailedCount.Eq(v) and combine
// them with And/Or/Not.
var (
	FailedCount  = graphql.Int64Field{Col: "failedCount"}
	Id           = graphql.StringField{Col: "id"}
	LastError    = graphql.StringField{Col: "lastError"}
	LastSyncTime = graphql.StringField{Col: "lastSyncTime"}
	Name         = graphql.StringField{Col: "name"}
	PendingCount = graphql.Int64Field{Col: "pendingCount"}
	State        = graphql.StringField{Col: "state"}
)

// And matches rows satisfying every predicate.
func And(p ...graphql.Predicate) graphql.Predicate { return graphql.And(p...) }

// Or matches rows satisfying any predicate.
func Or(p ...graphql.Predicate) graphql.Predicate { return graphql.Or(p...) }

// Not negates a predicate.
func Not(p graphql.Predicate) graphql.Predicate { return graphql.Not(p) }
