// Code generated by protoc-gen-store. DO NOT EDIT.
// versions:
// 	protoc-gen-store v1.5.4-0.20260906073202-9760202f187b+dirty
// 	protoc (unknown)
//
// database: freebusyql
// package:  enterpriseusersql
//
// annotations: entity.v1 v1.5.4-0.20260906073202-9760202f187b+dirty, store.v1 v1.5.4-0.20260906073202-9760202f187b+dirty
// engine:      protokit v1.3.1
//
// store — https://github.com/the-protobuf-project/store

package enterpriseusersql

import (
	"github.com/the-protobuf-project/runtime-go/network/graphql"
)

// DeleteUserEnterpriseUsersByIdResponse — Responses from the 'delete_user_enterprise_users_by_id' procedure
type DeleteUserEnterpriseUsersByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CostCenter selects the "costCenter" field; nil when the column is NULL.
		CostCenter *string `graphql:"costCenter"`
		// Department selects the "department" field; nil when the column is NULL.
		Department *string `graphql:"department"`
		// Division selects the "division" field; nil when the column is NULL.
		Division *string `graphql:"division"`
		// EmployeeNumber selects the "employeeNumber" field; nil when the column is NULL.
		EmployeeNumber *string `graphql:"employeeNumber"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// ManagerId selects the "managerId" field; nil when the column is NULL.
		ManagerId *string `graphql:"managerId"`
		// Organization selects the "organization" field; nil when the column is NULL.
		Organization *string `graphql:"organization"`
	} `graphql:"returning"`
}

// InsertUserEnterpriseUsersResponse — Responses from the 'insert_user_enterprise_users' procedure
type InsertUserEnterpriseUsersResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CostCenter selects the "costCenter" field; nil when the column is NULL.
		CostCenter *string `graphql:"costCenter"`
		// Department selects the "department" field; nil when the column is NULL.
		Department *string `graphql:"department"`
		// Division selects the "division" field; nil when the column is NULL.
		Division *string `graphql:"division"`
		// EmployeeNumber selects the "employeeNumber" field; nil when the column is NULL.
		EmployeeNumber *string `graphql:"employeeNumber"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// ManagerId selects the "managerId" field; nil when the column is NULL.
		ManagerId *string `graphql:"managerId"`
		// Organization selects the "organization" field; nil when the column is NULL.
		Organization *string `graphql:"organization"`
	} `graphql:"returning"`
}

// UpdateUserEnterpriseUsersByIdResponse — Responses from the 'update_user_enterprise_users_by_id' procedure
type UpdateUserEnterpriseUsersByIdResponse struct {
	// The number of rows affected by the mutation
	AffectedRows int32 `graphql:"affectedRows"`
	// Data from rows affected by the mutation
	Returning []struct {
		// CostCenter selects the "costCenter" field; nil when the column is NULL.
		CostCenter *string `graphql:"costCenter"`
		// Department selects the "department" field; nil when the column is NULL.
		Department *string `graphql:"department"`
		// Division selects the "division" field; nil when the column is NULL.
		Division *string `graphql:"division"`
		// EmployeeNumber selects the "employeeNumber" field; nil when the column is NULL.
		EmployeeNumber *string `graphql:"employeeNumber"`
		// Id selects the "id" field.
		Id string `graphql:"id"`
		// ManagerId selects the "managerId" field; nil when the column is NULL.
		ManagerId *string `graphql:"managerId"`
		// Organization selects the "organization" field; nil when the column is NULL.
		Organization *string `graphql:"organization"`
	} `graphql:"returning"`
}

// UserEnterpriseUsers is one row of the collection, selected with every scalar
// column; nullable columns are pointers so NULL stays distinguishable from a
// zero value.
type UserEnterpriseUsers struct {
	// CostCenter selects the "costCenter" field; nil when the column is NULL.
	CostCenter *string `graphql:"costCenter"`
	// Department selects the "department" field; nil when the column is NULL.
	Department *string `graphql:"department"`
	// Division selects the "division" field; nil when the column is NULL.
	Division *string `graphql:"division"`
	// EmployeeNumber selects the "employeeNumber" field; nil when the column is NULL.
	EmployeeNumber *string `graphql:"employeeNumber"`
	// Id selects the "id" field.
	Id string `graphql:"id"`
	// ManagerId selects the "managerId" field; nil when the column is NULL.
	ManagerId *string `graphql:"managerId"`
	// Organization selects the "organization" field; nil when the column is NULL.
	Organization *string `graphql:"organization"`
}

// UserEnterpriseUsersAggExp aggregates the collection's rows: the row count plus
// per-column counts, min/max, and numeric statistics.
type UserEnterpriseUsersAggExp struct {
	// Count selects the "_count" field.
	Count graphql.Int64 `graphql:"_count"`
	// CostCenter selects the "costCenter" field.
	CostCenter struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"costCenter"`
	// Department selects the "department" field.
	Department struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"department"`
	// Division selects the "division" field.
	Division struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"division"`
	// EmployeeNumber selects the "employeeNumber" field.
	EmployeeNumber struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"employeeNumber"`
	// Id selects the "id" field.
	Id struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"id"`
	// ManagerId selects the "managerId" field.
	ManagerId struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"managerId"`
	// Organization selects the "organization" field.
	Organization struct {
		// Count selects the "_count" field.
		Count graphql.Int64 `graphql:"_count"`
		// CountDistinct selects the "_count_distinct" field.
		CountDistinct graphql.Int64 `graphql:"_count_distinct"`
		// Max selects the "max" field; nil when the column is NULL.
		Max *string `graphql:"max"`
		// Min selects the "min" field; nil when the column is NULL.
		Min *string `graphql:"min"`
	} `graphql:"organization"`
}
